import React, { useState } from 'react';
import { Plus, X } from 'lucide-react';
import { Button } from '../../../../components/ui/Button';
import { craftMaterialsApi } from '../../../../services/api/craft-materials.api';
import type { MaterialCategory, MaterialCategoryType } from '../../../../types/craft-materials';

export function MaterialCategoryManager({ open, categories, onClose, onChanged }: { open: boolean; categories: MaterialCategory[]; onClose: () => void; onChanged: () => Promise<void> }) {
  const [name, setName] = useState(''); const [type, setType] = useState<MaterialCategoryType>('filament'); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [names, setNames] = useState<Record<number, string>>({});
  if (!open) return null; const create = async (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) return; setSaving(true); setError(null); try { await craftMaterialsApi.createCategory({ name, category_type: type }); setName(''); await onChanged(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Kategori tidak dapat dibuat.'); } finally { setSaving(false); } };
  const toggle = async (category: MaterialCategory) => { setSaving(true); setError(null); try { await craftMaterialsApi.updateCategory(category.id, { is_active: !category.is_active }); await onChanged(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Kategori tidak dapat diperbarui.'); } finally { setSaving(false); } };
  const rename = async (category: MaterialCategory) => { const next = (names[category.id] ?? category.name).trim(); if (!next || next === category.name) return; setSaving(true); setError(null); try { await craftMaterialsApi.updateCategory(category.id, { name: next }); await onChanged(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Kategori tidak dapat diubah.'); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4"><section className="w-full max-w-2xl rounded-xl bg-white shadow-xl"><header className="flex items-start justify-between border-b border-[var(--nexus-border)] p-5"><div><h2 className="font-bold text-[var(--nexus-charcoal)]">Kelola Kategori Material</h2><p className="mt-1 text-xs text-[var(--nexus-muted)]">Kategori yang sudah dipakai tidak dihapus; nonaktifkan bila tidak digunakan lagi.</p></div><button onClick={onClose} className="rounded p-1 text-[var(--nexus-muted)] hover:bg-gray-100"><X className="h-5 w-5" /></button></header><div className="max-h-[55vh] overflow-auto p-5"><div className="space-y-2">{categories.map((category) => <div className="flex flex-col gap-2 rounded-lg border border-[var(--nexus-border)] p-3 sm:flex-row sm:items-center sm:justify-between" key={category.id}><div className="min-w-0 flex-1"><input className="h-8 w-full rounded border border-transparent bg-transparent px-1 font-semibold text-[var(--nexus-charcoal)] outline-none focus:border-[var(--nexus-border)] focus:bg-white" value={names[category.id] ?? category.name} onChange={(event) => setNames((current) => ({ ...current, [category.id]: event.target.value }))} /><p className="material-code">{category.code} · {category.category_type} · {category.product_count} material</p></div><div className="flex gap-2"><Button size="sm" variant="outline" disabled={saving || !(names[category.id] ?? category.name).trim()} onClick={() => void rename(category)}>Simpan Nama</Button><Button size="sm" variant="outline" disabled={saving} onClick={() => void toggle(category)}>{category.is_active ? 'Nonaktifkan' : 'Aktifkan'}</Button></div></div>)}</div><form className="mt-5 grid gap-3 rounded-xl bg-[var(--nexus-cream-soft)] p-4 md:grid-cols-[1fr_170px_auto]" onSubmit={(event) => void create(event)}><label className="material-field"><span>Nama kategori baru</span><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Contoh: Flexible" /></label><label className="material-field"><span>Tipe</span><select value={type} onChange={(event) => setType(event.target.value as MaterialCategoryType)}>{(['filament', 'resin', 'hardware', 'packaging', 'consumable', 'other'] as MaterialCategoryType[]).map((item) => <option key={item}>{item}</option>)}</select></label><Button className="self-end" type="submit" disabled={saving || !name.trim()}><Plus className="h-4 w-4" />Tambah</Button></form>{error && <p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}</div></section></div>;
}
