import React, { useEffect, useState } from 'react';
import { X } from 'lucide-react';
import { Button } from '../../../../components/ui/Button';
import { craftMaterialsApi } from '../../../../services/api/craft-materials.api';
import type { CraftMaterial } from '../../../../types/craft-materials';

export function StockReceiptDialog({ material, open, onClose, onSaved }: { material: CraftMaterial | null; open: boolean; onClose: () => void; onSaved: () => Promise<void> }) {
  const [quantity, setQuantity] = useState(''); const [unitCost, setUnitCost] = useState(''); const [location, setLocation] = useState(''); const [notes, setNotes] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (open && material) { setQuantity(''); setUnitCost(String(material.default_unit_cost || '')); setLocation(''); setNotes(''); setError(null); } }, [material, open]);
  if (!open || !material) return null; const filament = material.category_type === 'filament';
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const parsed = Number(quantity); if (!(parsed > 0)) { setError('Jumlah penerimaan harus lebih dari 0.'); return; } setSaving(true); setError(null); try { await craftMaterialsApi.receiveStock(material.id, { quantity: parsed, unit_cost: Number(unitCost || material.default_unit_cost || 0), location_code: location || null, storage_location: location || null, notes: notes || null, create_spool: filament }); await onSaved(); onClose(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Stok tidak dapat diterima.'); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4"><form onSubmit={(event) => void submit(event)} className="w-full max-w-lg rounded-xl bg-white shadow-xl"><header className="flex items-start justify-between border-b border-[var(--nexus-border)] p-5"><div><p className="material-code">{material.sku}</p><h2 className="mt-1 font-bold text-[var(--nexus-charcoal)]">Terima Stok {material.name}</h2></div><button type="button" onClick={onClose} className="rounded p-1 text-[var(--nexus-muted)] hover:bg-gray-100"><X className="h-5 w-5" /></button></header><div className="grid gap-4 p-5 sm:grid-cols-2"><label className="material-field"><span>Jumlah ({material.unit_symbol}) *</span><input inputMode="decimal" autoFocus value={quantity} onChange={(event) => setQuantity(event.target.value)} placeholder="1000" /></label><label className="material-field"><span>Biaya per {material.unit_symbol} (Rp)</span><input inputMode="decimal" value={unitCost} onChange={(event) => setUnitCost(event.target.value)} placeholder="0" /></label><label className="material-field sm:col-span-2"><span>Lokasi Penyimpanan</span><input value={location} onChange={(event) => setLocation(event.target.value)} placeholder="Rak A-01" /></label>{filament && <p className="rounded-lg bg-[var(--nexus-cream-soft)] p-3 text-xs leading-5 text-[var(--nexus-muted)] sm:col-span-2">Penerimaan filament akan membuat satu batch dan satu spool fisik dengan berat bersih sesuai jumlah penerimaan.</p>}<label className="material-field sm:col-span-2"><span>Catatan</span><textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Referensi penerimaan atau kondisi material…" /></label>{error && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700 sm:col-span-2">{error}</p>}</div><footer className="flex justify-end gap-2 border-t border-[var(--nexus-border)] bg-[var(--nexus-cream-soft)]/40 p-4"><Button type="button" variant="outline" onClick={onClose}>Batal</Button><Button type="submit" disabled={saving}>{saving ? 'Menyimpan…' : 'Terima Stok'}</Button></footer></form></div>;
}
