import React, { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, RefreshCw } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button } from '../../../components/ui/Button';
import { craftMaterialsApi } from '../../../services/api/craft-materials.api';
import type { CraftMaterial } from '../../../types/craft-materials';
import { MaterialStatusBadge } from './components/MaterialStatusBadge';

export function LowStockPage() {
  const [items, setItems] = useState<CraftMaterial[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const load = useCallback(async () => { setLoading(true); setError(null); try { setItems(await craftMaterialsApi.getLowStock()); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Stok menipis tidak dapat dimuat.'); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  return <div className="space-y-6"><header className="flex items-end justify-between border-b border-[var(--nexus-border)] pb-5"><div><p className="material-code">MATERIAL</p><h1 className="mt-1 text-2xl font-bold text-[var(--nexus-charcoal)]">Stok Menipis</h1><p className="mt-1 text-sm text-[var(--nexus-muted)]">Daftar material berdasarkan stok tersedia setelah reservasi produksi.</p></div><Button variant="outline" onClick={() => void load()}><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Muat Ulang</Button></header>{error ? <section className="rounded-xl border border-red-200 bg-red-50 p-6"><p className="text-red-800">{error}</p><Button className="mt-3" onClick={() => void load()}>Coba Lagi</Button></section> : loading ? <p className="rounded-xl border border-[var(--nexus-border)] bg-white p-10 text-center text-sm text-[var(--nexus-muted)]">Memuat status stok…</p> : items.length === 0 ? <section className="rounded-xl border border-dashed border-emerald-200 bg-white p-12 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-emerald-50 text-emerald-700">✓</div><h2 className="mt-4 font-bold text-[var(--nexus-charcoal)]">Semua Stok Dalam Kondisi Aman</h2><p className="mt-2 text-sm text-[var(--nexus-muted)]">Tidak ada material aktif yang berada di bawah ambang stoknya.</p></section> : <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <Link key={item.id} to={`/app/craft/materials/${item.id}`} className="rounded-xl border border-[var(--nexus-border)] bg-white p-5 shadow-sm transition hover:border-[var(--nexus-yellow-deep)]"><div className="flex items-start justify-between gap-3"><div><p className="material-code">{item.sku}</p><h2 className="mt-1 font-bold">{item.name}</h2><p className="mt-1 text-xs text-[var(--nexus-muted)]">{item.category_name} · {item.material_type || '—'}</p></div><MaterialStatusBadge status={item.stock_status}/></div><div className="mt-5 flex items-center gap-3 rounded-lg bg-[var(--nexus-cream-soft)] p-3"><AlertTriangle className="h-5 w-5 text-amber-600"/><div><p className="text-sm font-bold">{item.available_qty} {item.unit_symbol} tersedia</p><p className="text-xs text-[var(--nexus-muted)]">Ambang {item.low_stock_threshold} {item.unit_symbol} · rekomendasi reorder {item.reorder_qty} {item.unit_symbol}</p></div></div></Link>)}</section>}</div>;
}
