import React, { useCallback, useEffect, useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, RefreshCw } from 'lucide-react';
import { Button } from '../../../components/ui/Button';
import { formatDate } from '../../../lib/utils';
import { craftMaterialsApi } from '../../../services/api/craft-materials.api';
import type { InventoryMovement } from '../../../types/craft-materials';

const label = (type: string) => ({ stock_in: 'Penerimaan stok', production_usage: 'Pemakaian produksi', waste: 'Limbah', adjustment_in: 'Penyesuaian masuk', adjustment_out: 'Penyesuaian keluar', reservation: 'Reservasi', release: 'Pelepasan reservasi' }[type] || type);
export function StockMovementsPage() {
  const [movements, setMovements] = useState<InventoryMovement[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const load = useCallback(async () => { setLoading(true); setError(null); try { setMovements(await craftMaterialsApi.getMovements()); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Pergerakan stok tidak dapat dimuat.'); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  return <div className="space-y-6"><header className="flex items-end justify-between border-b border-[var(--nexus-border)] pb-5"><div><p className="material-code">MATERIAL</p><h1 className="mt-1 text-2xl font-bold text-[var(--nexus-charcoal)]">Pergerakan Stok</h1><p className="mt-1 text-sm text-[var(--nexus-muted)]">Jejak penerimaan, penggunaan produksi, penyesuaian, dan limbah material.</p></div><Button variant="outline" onClick={() => void load()}><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Muat Ulang</Button></header>{error ? <section className="rounded-xl border border-red-200 bg-red-50 p-6"><p className="text-red-800">{error}</p><Button className="mt-3" onClick={() => void load()}>Coba Lagi</Button></section> : loading ? <p className="rounded-xl border border-[var(--nexus-border)] bg-white p-10 text-center text-sm text-[var(--nexus-muted)]">Memuat pergerakan stok…</p> : movements.length === 0 ? <section className="rounded-xl border border-dashed border-[var(--nexus-border)] bg-white p-12 text-center"><h2 className="font-bold">Belum Ada Pergerakan Stok</h2><p className="mt-2 text-sm text-[var(--nexus-muted)]">Penerimaan, pemakaian, dan penyesuaian akan muncul di sini.</p></section> : <section className="overflow-hidden rounded-xl border border-[var(--nexus-border)] bg-white shadow-sm"><div className="overflow-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="orders-table-head"><tr><th>Waktu</th><th>Material</th><th>Jenis</th><th>Referensi</th><th>Catatan</th><th className="text-right">Jumlah</th></tr></thead><tbody>{movements.map((movement) => { const incoming = ['stock_in', 'adjustment_in', 'return_in'].includes(movement.movement_type); return <tr className="orders-table-row" key={movement.id}><td>{formatDate(movement.occurred_at)}</td><td><p className="font-semibold">{movement.material_name}</p><p className="material-code">{movement.material_sku} · {movement.batch_code || 'tanpa batch'}</p></td><td><span className="inline-flex items-center gap-1.5"><span className={`flex h-6 w-6 items-center justify-center rounded-full ${incoming ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{incoming ? <ArrowDownLeft className="h-3.5 w-3.5"/> : <ArrowUpRight className="h-3.5 w-3.5"/>}</span>{label(movement.movement_type)}</span></td><td>{movement.reference_code || '—'}</td><td className="max-w-xs truncate text-[var(--nexus-muted)]">{movement.notes || '—'}</td><td className={`text-right font-bold ${incoming ? 'text-emerald-700' : 'text-[var(--nexus-charcoal)]'}`}>{incoming ? '+' : '−'}{movement.quantity} {movement.unit_symbol}</td></tr>; })}</tbody></table></div></section>}</div>;
}
