import { useQuery } from '@tanstack/react-query';
import { ArrowDownRight, ArrowRight, Box, CheckCircle2, ChevronRight, ClipboardList, Clock3, Layers3, MessageSquare, Plus, Printer, ReceiptText } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api, type Envelope, type Row } from '../lib/api';
import { useAuth } from '../lib/auth';
import { display, money, recordName, titleCase } from '../lib/format';
import { Badge, EmptyState, ErrorState, PageHeader, Spinner } from '../components/ui';

type DashboardData = { metrics: { openRequests: number; pendingQuotations: number; activeOrders: number; queuedProduction: number; activePrints: number; materialUsageGram: string; estimatedHpp: string; actualHpp: string }; printers: { status: string; count: number }[]; recentFailures: Row[]; recentActivity: Row[] };

export function Dashboard() {
  const { workspace, session } = useAuth();
  const query = useQuery({ queryKey: ['dashboard', workspace!.id], queryFn: async () => (await api<Envelope<DashboardData>>('/dashboard', { workspace: workspace!.id })).data });
  if (query.isPending) return <Spinner />;
  if (query.isError) return <ErrorState error={query.error} retry={() => void query.refetch()} />;
  const { metrics, printers, recentActivity, recentFailures } = query.data;
  const totalPrinters = printers.reduce((sum, item) => sum + Number(item.count), 0);
  const cards = [
    { label: 'Permintaan Terbuka', count: metrics.openRequests, icon: MessageSquare, path: 'requests', note: 'Ide yang sedang dimatangkan', color: 'teal' },
    { label: 'Penawaran Menunggu', count: metrics.pendingQuotations, icon: ReceiptText, path: 'quotations', note: 'Menunggu langkah berikutnya', color: 'amber' },
    { label: 'Pesanan Aktif', count: metrics.activeOrders, icon: ClipboardList, path: 'orders', note: 'Sedang dikerjakan', color: 'blue' },
    { label: 'Proses Cetak Aktif', count: metrics.activePrints, icon: Printer, path: 'print-queue', note: `${metrics.queuedProduction} tugas produksi dalam antrean`, color: 'purple' },
  ];
  return <><PageHeader eyebrow="RINGKASAN WORKSPACE" title={`Selamat datang kembali, ${session?.user.full_name.split(' ')[0] || 'tim'}.`} description="Ringkasan aktivitas yang sedang berlangsung di operasional Anda." actions={<Link to="/app/requests/new" className="button primary"><Plus size={17} />Permintaan Baru</Link>} />
    <div className="overview-banner"><div className="banner-icon"><Layers3 size={27} strokeWidth={1.5} /></div><div><strong>Kerja yang baik dimulai dari alur kerja yang terhubung.</strong><p>Dari permintaan pertama hingga pemeriksaan kualitas akhir, pantau setiap tahapnya.</p></div><Link to="/app/production">Lihat Produksi<ArrowRight size={16} /></Link></div>
    <div className="metric-grid">{cards.map(({ label, count, icon: Icon, path, note, color }) => <Link className="metric-card" to={`/app/${path}`} key={path}><div className="metric-top"><span>{label}</span><span className={`metric-icon ${color}`}><Icon size={18} /></span></div><strong className="metric-value">{count.toLocaleString()}</strong><div className="metric-bottom"><span>{note}</span><ArrowDownRight size={17} /></div></Link>)}</div>
    <div className="dashboard-grid"><section className="panel workflow-panel"><div className="panel-heading"><div><h2>Alur Produksi</h2><p>Setiap tahap punya tempatnya.</p></div><Link to="/app/orders">Lihat Pesanan<ChevronRight size={15} /></Link></div><div className="pipeline">{[{ name: 'Permintaan', count: metrics.openRequests, icon: MessageSquare, link: 'requests' }, { name: 'Penawaran', count: metrics.pendingQuotations, icon: ReceiptText, link: 'quotations' }, { name: 'Pesanan', count: metrics.activeOrders, icon: ClipboardList, link: 'orders' }, { name: 'Antrean', count: metrics.queuedProduction, icon: Box, link: 'production' }, { name: 'Mencetak', count: metrics.activePrints, icon: Printer, link: 'print-queue' }].map(({ name, count, icon: Icon, link }) => <Link to={`/app/${link}`} key={name} className="pipeline-step"><span><Icon size={20} /></span><strong>{count}</strong><small>{name}</small></Link>)}</div><div className="panel-note"><CheckCircle2 size={15} />Permintaan, penawaran, pesanan, dan produksi tetap terhubung sebagai catatan yang berbeda.</div></section>
      <section className="panel"><div className="panel-heading"><div><h2>Lantai Printer</h2><p>{totalPrinters} {totalPrinters === 1 ? 'printer' : 'printer'} di workspace Anda</p></div><Printer size={20} /></div>{totalPrinters ? <div className="printer-status-list">{printers.map((item) => <Link to={`/app/printers?status=${item.status}`} key={item.status}><Badge value={item.status} /><strong>{item.count}</strong></Link>)}</div> : <EmptyState title="Bengkel yang masih sepi" description="Tambahkan printer pertama Anda untuk mulai mengelola lantai produksi." action={<Link className="text-link" to="/app/printers/new">Tambah printer<ArrowRight size={15} /></Link>} />}</section>
      <section className="panel"><div className="panel-heading"><div><h2>Aktivitas Terbaru</h2><p>Catatan bersama dari pekerjaan tim Anda.</p></div><Link to="/app/audit">Lihat Semua<ChevronRight size={15} /></Link></div>{recentActivity.length ? <div className="activity-list">{recentActivity.slice(0, 6).map((item) => <div className="activity-item" key={item.id}><span className="activity-icon"><Clock3 size={16} /></span><div><strong>{titleCase(String(item.action || 'Updated'))} · {titleCase(String(item.entity_type || 'record'))}</strong><small>{display(item.created_at, { name: 'created_at', label: 'Date', type: 'datetime' })}</small></div></div>)}</div> : <EmptyState title="Ceritanya dimulai di sini" description="Perubahan pada permintaan, pesanan, dan produksi akan muncul di sini seiring tim Anda mulai bekerja." />}</section>
      <section className="panel"><div className="panel-heading"><div><h2>Biaya & Material</h2><p>Total tercatat di workspace</p></div><Link to="/app/costing">Detail<ChevronRight size={15} /></Link></div><div className="cost-overview"><div><span>Estimasi HPP</span><strong>{money(metrics.estimatedHpp)}</strong></div><div><span>HPP Aktual</span><strong>{money(metrics.actualHpp)}</strong></div><div><span>Material terpakai</span><strong>{display(metrics.materialUsageGram)} <small>g</small></strong></div></div><div className="panel-note"><Layers3 size={15} />Berdasarkan biaya dan pemakaian material yang tercatat.</div></section>
    </div>
    {recentFailures.length > 0 && <section className="panel attention-panel"><div className="panel-heading"><div><h2>Kegagalan Cetak untuk Ditinjau</h2><p>Pelajari setiap kegagalan agar proses berikutnya lebih baik.</p></div><Link to="/app/failures">Lihat Kegagalan<ChevronRight size={15} /></Link></div><div className="activity-list">{recentFailures.slice(0, 4).map((item) => <Link className="activity-item" to={`/app/failures/${item.id}`} key={item.id}><span className="activity-icon amber"><Printer size={17} /></span><div><strong>{String(item.failure_type || item.reason || recordName(item))}</strong><small>{display(item.created_at, { name: 'created_at', label: 'Date', type: 'datetime' })}</small></div><ChevronRight size={16} /></Link>)}</div></section>}
  </>;
}
