import { useQuery } from '@tanstack/react-query';
import { ArrowDownRight, ArrowRight, Box, CheckCircle2, ChevronRight, ClipboardList, Clock3, Layers3, MessageSquare, Plus, Printer, ReceiptText } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api, type Envelope, type Row } from '../lib/api';
import { useAuth } from '../lib/auth';
import { display, money, recordName, titleCase } from '../lib/format';
import { Badge, EmptyState, ErrorState, PageHeader, Spinner } from '../components/ui';

type DashboardData = { metrics: { openRequests: number; pendingQuotations: number; activeOrders: number; queuedProduction: number; activePrints: number; materialUsageGram: string; estimatedHpp: string; actualHpp: string }; printers: { status: string; count: number }[]; recentFailures: Row[]; recentActivity: Row[] };

export function Dashboard() {
  const { workspace, session } = useAuth();
  const query = useQuery({ queryKey: ['dashboard', workspace!.id], queryFn: async () => (await api<Envelope<DashboardData>>('/dashboard', { workspace: workspace!.id })).data });
  if (query.isPending) return <Spinner />;
  if (query.isError) return <ErrorState error={query.error} retry={() => void query.refetch()} />;
  const { metrics, printers, recentActivity, recentFailures } = query.data;
  const totalPrinters = printers.reduce((sum, item) => sum + Number(item.count), 0);
  const cards = [
    { label: 'Open requests', count: metrics.openRequests, icon: MessageSquare, path: 'requests', note: 'Ideas taking shape', color: 'teal' },
    { label: 'Pending quotations', count: metrics.pendingQuotations, icon: ReceiptText, path: 'quotations', note: 'Awaiting the next step', color: 'amber' },
    { label: 'Active orders', count: metrics.activeOrders, icon: ClipboardList, path: 'orders', note: 'Work in progress', color: 'blue' },
    { label: 'Active print jobs', count: metrics.activePrints, icon: Printer, path: 'print-queue', note: `${metrics.queuedProduction} production jobs queued`, color: 'purple' },
  ];
  return <><PageHeader eyebrow="WORKSPACE OVERVIEW" title={`Welcome back, ${session?.user.full_name.split(' ')[0] || 'team'}.`} description="A clear view of what’s happening across your workshop." actions={<Link to="/app/requests/new" className="button primary"><Plus size={17} />New request</Link>} />
    <div className="overview-banner"><div className="banner-icon"><Layers3 size={27} strokeWidth={1.5} /></div><div><strong>Good work starts with a connected workflow.</strong><p>From the first request to the final quality check, keep every step in sight.</p></div><Link to="/app/production">View production<ArrowRight size={16} /></Link></div>
    <div className="metric-grid">{cards.map(({ label, count, icon: Icon, path, note, color }) => <Link className="metric-card" to={`/app/${path}`} key={path}><div className="metric-top"><span>{label}</span><span className={`metric-icon ${color}`}><Icon size={18} /></span></div><strong className="metric-value">{count.toLocaleString()}</strong><div className="metric-bottom"><span>{note}</span><ArrowDownRight size={17} /></div></Link>)}</div>
    <div className="dashboard-grid"><section className="panel workflow-panel"><div className="panel-heading"><div><h2>The production pipeline</h2><p>Every stage has its place.</p></div><Link to="/app/orders">View orders<ChevronRight size={15} /></Link></div><div className="pipeline">{[{ name: 'Requests', count: metrics.openRequests, icon: MessageSquare, link: 'requests' }, { name: 'Quotations', count: metrics.pendingQuotations, icon: ReceiptText, link: 'quotations' }, { name: 'Orders', count: metrics.activeOrders, icon: ClipboardList, link: 'orders' }, { name: 'Queued', count: metrics.queuedProduction, icon: Box, link: 'production' }, { name: 'Printing', count: metrics.activePrints, icon: Printer, link: 'print-queue' }].map(({ name, count, icon: Icon, link }) => <Link to={`/app/${link}`} key={name} className="pipeline-step"><span><Icon size={20} /></span><strong>{count}</strong><small>{name}</small></Link>)}</div><div className="panel-note"><CheckCircle2 size={15} />Requests, quotations, orders, and production stay connected as distinct records.</div></section>
      <section className="panel"><div className="panel-heading"><div><h2>Printer floor</h2><p>{totalPrinters} {totalPrinters === 1 ? 'printer' : 'printers'} in your workspace</p></div><Printer size={20} /></div>{totalPrinters ? <div className="printer-status-list">{printers.map((item) => <Link to={`/app/printers?status=${item.status}`} key={item.status}><Badge value={item.status} /><strong>{item.count}</strong></Link>)}</div> : <EmptyState title="A quiet workshop, for now" description="Add your first printer to start managing your production floor." action={<Link className="text-link" to="/app/printers/new">Add a printer<ArrowRight size={15} /></Link>} />}</section>
      <section className="panel"><div className="panel-heading"><div><h2>Recent activity</h2><p>A shared record of your team’s work.</p></div><Link to="/app/audit">View all<ChevronRight size={15} /></Link></div>{recentActivity.length ? <div className="activity-list">{recentActivity.slice(0, 6).map((item) => <div className="activity-item" key={item.id}><span className="activity-icon"><Clock3 size={16} /></span><div><strong>{titleCase(String(item.action || 'Updated'))} · {titleCase(String(item.entity_type || 'record'))}</strong><small>{display(item.created_at, { name: 'created_at', label: 'Date', type: 'datetime' })}</small></div></div>)}</div> : <EmptyState title="Your story starts here" description="Changes to requests, orders, and production will appear here as your team gets to work." />}</section>
      <section className="panel"><div className="panel-heading"><div><h2>Costs & materials</h2><p>Recorded workspace totals</p></div><Link to="/app/costing">Details<ChevronRight size={15} /></Link></div><div className="cost-overview"><div><span>Estimated HPP</span><strong>{money(metrics.estimatedHpp)}</strong></div><div><span>Actual HPP</span><strong>{money(metrics.actualHpp)}</strong></div><div><span>Material used</span><strong>{display(metrics.materialUsageGram)} <small>g</small></strong></div></div><div className="panel-note"><Layers3 size={15} />Based on recorded costs and material usage.</div></section>
    </div>
    {recentFailures.length > 0 && <section className="panel attention-panel"><div className="panel-heading"><div><h2>Print failures to review</h2><p>Learn from each run and make the next one better.</p></div><Link to="/app/failures">View failures<ChevronRight size={15} /></Link></div><div className="activity-list">{recentFailures.slice(0, 4).map((item) => <Link className="activity-item" to={`/app/failures/${item.id}`} key={item.id}><span className="activity-icon amber"><Printer size={17} /></span><div><strong>{String(item.failure_type || item.reason || recordName(item))}</strong><small>{display(item.created_at, { name: 'created_at', label: 'Date', type: 'datetime' })}</small></div><ChevronRight size={16} /></Link>)}</div></section>}
  </>;
}
