import React, { useEffect, useState } from 'react';
import { FileEdit, Inbox, Plus, Trash2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../../../components/ui/Button';
import { Card } from '../../../components/ui/Card';
import { ConfirmDialog } from '../../../components/ui/ConfirmDialog';
import { craftOrdersApi } from '../../../services/api/craft-orders.api';
import type { CraftOrderDraftSummary } from '../../../types/craft-orders';
import { EmptyOrdersState, OrderPageHeader } from './components/OrdersUI';

export function DraftOrdersPage() {
  const navigate = useNavigate(); const [drafts, setDrafts] = useState<CraftOrderDraftSummary[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [discarding, setDiscarding] = useState<CraftOrderDraftSummary | null>(null); const [working, setWorking] = useState(false);
  const load = async () => { setLoading(true); try { setDrafts(await craftOrdersApi.getDrafts()); setError(null); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Gagal memuat draf pesanan.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const discard = async () => { if (!discarding) return; setWorking(true); try { await craftOrdersApi.discardDraft(discarding.id); setDiscarding(null); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Gagal membuang draf pesanan.'); } finally { setWorking(false); } };
  return <div className="space-y-6 pb-8"><OrderPageHeader title="Draf Pesanan" description="Lanjutkan pesanan yang belum siap menjadi order operasional." actions={<Button onClick={() => navigate('/app/craft/orders/new')}><Plus className="h-4 w-4" /> Pesanan Baru</Button>} />{error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<Card>{loading ? <div className="flex h-64 items-center justify-center text-sm text-[var(--nexus-muted)]">Memuat draf...</div> : drafts.length === 0 ? <EmptyOrdersState title="Belum Ada Draf Pesanan" description="Draf yang Anda simpan sebelum menjadi order akan muncul di sini." action={<Button onClick={() => navigate('/app/craft/orders/new')}><Plus className="h-4 w-4" /> Buat Draf Pertama</Button>} /> : <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="orders-table-head"><tr><th>Kode Draf</th><th>Judul / Ringkasan</th><th>Pelanggan</th><th>Item</th><th>Dibuat Oleh</th><th>Terakhir Diperbarui</th><th className="text-right">Aksi</th></tr></thead><tbody>{drafts.map(draft => <tr key={draft.id} className="orders-table-row"><td><span className="orders-code">{draft.draft_code}</span></td><td><span className="font-semibold text-[var(--nexus-charcoal)]">{draft.title || 'Draf Pesanan Baru'}</span></td><td className="text-[var(--nexus-muted)]">{draft.customer_name || 'Belum dipilih'}</td><td>{draft.item_count}</td><td className="text-[var(--nexus-muted)]">{draft.created_by_name || '-'}</td><td className="text-[var(--nexus-muted)]">{new Date(draft.updated_at).toLocaleString('id-ID')}</td><td><div className="flex justify-end gap-2"><Button size="sm" variant="outline" onClick={() => navigate(`/app/craft/orders/drafts/${draft.id}`)}><FileEdit className="h-3.5 w-3.5" /> Lanjutkan</Button><Button size="sm" variant="ghost" className="text-red-600" onClick={() => setDiscarding(draft)}><Trash2 className="h-3.5 w-3.5" /> Buang</Button></div></td></tr>)}</tbody></table></div>}</Card><ConfirmDialog open={Boolean(discarding)} title="Buang draf pesanan?" description={discarding ? `Draf ${discarding.draft_code} akan ditandai sebagai dibuang dan tidak akan muncul di daftar aktif.` : ''} confirmLabel="Buang Draf" isLoading={working} onCancel={() => setDiscarding(null)} onConfirm={() => void discard()} variant="danger" /></div>;
}
