import React, { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, Clock, RefreshCw, Timer } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../../../components/ui/Button';
import { Card } from '../../../components/ui/Card';
import { craftOrdersApi } from '../../../services/api/craft-orders.api';
import type { CraftOrder } from '../../../types/craft-orders';
import { EmptyOrdersState, OrderPageHeader, OrderPriorityBadge } from './components/OrdersUI';

export function OrderPriorityPage() {
  const navigate = useNavigate(); const [orders, setOrders] = useState<CraftOrder[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [working, setWorking] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const result = await craftOrdersApi.getOrders({ page: 1, limit: 100, activeOnly: true, sortBy: 'priority', sortOrder: 'desc' }); setOrders(result.items); setError(null); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Gagal memuat prioritas.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const recalculate = async () => { setWorking(true); try { await craftOrdersApi.recalculatePriorities(); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Gagal mengkalkulasi prioritas.'); } finally { setWorking(false); } };
  return <div className="space-y-6 pb-8"><OrderPageHeader title="Prioritas Produksi" description="Pesanan mana yang harus dikerjakan lebih dahulu? Urutan ini mengikuti urgensi dan estimasi produksi." actions={<Button variant="outline" onClick={() => void recalculate()} disabled={working}><RefreshCw className={`h-4 w-4 ${working ? 'animate-spin' : ''}`} />{working ? 'Menghitung...' : 'Kalkulasi Ulang'}</Button>} />{error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{loading ? <div className="flex h-64 items-center justify-center text-sm text-[var(--nexus-muted)]">Memuat prioritas...</div> : orders.length === 0 ? <Card><EmptyOrdersState title="Tidak Ada Pesanan Aktif" description="Pesanan aktif akan muncul setelah dibuat." /></Card> : <div className="space-y-3">{orders.map((order, index) => <Card key={order.id} className="cursor-pointer transition duration-150 hover:border-[var(--nexus-yellow-deep)]" onClick={() => navigate(`/app/craft/orders/${order.id}`)}><div className="grid gap-4 p-5 md:grid-cols-[64px_minmax(0,1fr)_220px]"><div className={`flex h-12 w-12 items-center justify-center rounded-xl text-lg font-bold ${index === 0 ? 'bg-[var(--nexus-yellow)] text-[var(--nexus-charcoal)]' : 'bg-[var(--nexus-cream-soft)] text-[var(--nexus-muted)]'}`}>#{index + 1}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="orders-code text-sm">{order.order_code}</span><OrderPriorityBadge value={order.priority_code} />{Boolean(order.is_overdue) && <span className="inline-flex items-center gap-1 rounded-full border border-red-200 bg-red-50 px-2.5 py-1 text-[11px] font-semibold text-red-700"><AlertTriangle className="h-3 w-3" /> Terlambat</span>}</div><p className="mt-2 font-medium text-[var(--nexus-charcoal)]">{order.customer_name}</p><p className="mt-1 text-xs text-[var(--nexus-muted)]">{order.sales_channel_name} · Skor prioritas {Number(order.priority_score).toFixed(1)}</p>{order.priority_reason && <p className="mt-3 border-l-2 border-[var(--nexus-yellow)] pl-3 text-xs leading-5 text-[var(--nexus-muted)]">{order.priority_reason}</p>}</div><div className="space-y-2 text-xs text-[var(--nexus-muted)] md:text-right"><p className="inline-flex items-center gap-1 md:justify-end"><Clock className="h-3.5 w-3.5" /> {order.deadline_at ? new Date(order.deadline_at).toLocaleString('id-ID') : 'Tanpa tenggat'}</p><p className="inline-flex items-center gap-1 md:justify-end"><Timer className="h-3.5 w-3.5" /> Est. cetak: {order.total_print_minutes ? `${order.total_print_minutes} menit` : '-'}</p></div></div></Card>)}</div>}</div>;
}
