import React, { useEffect, useState } from 'react';
import { CalendarClock, Save, Truck } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { Card } from '../../../components/ui/Card';
import { Button } from '../../../components/ui/Button';
import { craftOrdersApi } from '../../../services/api/craft-orders.api';
import { FormField, OrderPageHeader, OrderPriorityBadge, OrderSectionHeader, OrderStatusBadge } from './components/OrdersUI';

const PRE_PRODUCTION_STATUSES = ['new', 'confirmed', 'waiting', 'ready'];
export function OrderEditPage() {
  const { id } = useParams<{ id: string }>(); const navigate = useNavigate(); const orderId = parseInt(id!);
  const [order, setOrder] = useState<Awaited<ReturnType<typeof craftOrdersApi.getOrder>>['order'] | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [deadline, setDeadline] = useState(''); const [customerNotes, setCustomerNotes] = useState(''); const [internalNotes, setInternalNotes] = useState(''); const [couriername, setCourierName] = useState(''); const [shippingAddress, setShippingAddress] = useState(''); const [shippingRecipient, setShippingRecipient] = useState(''); const [shippingPhone, setShippingPhone] = useState('');
  useEffect(() => { const load = async () => { try { const res = await craftOrdersApi.getOrder(orderId); const loadedOrder = res.order; setOrder(loadedOrder); setDeadline(loadedOrder.deadline_at ? new Date(loadedOrder.deadline_at).toISOString().slice(0, 16) : ''); setCustomerNotes(loadedOrder.customer_notes || ''); setInternalNotes(loadedOrder.internal_notes || ''); setCourierName(loadedOrder.courier_name || ''); setShippingAddress(loadedOrder.shipping_address || ''); setShippingRecipient(loadedOrder.shipping_recipient_name || ''); setShippingPhone(loadedOrder.shipping_phone || ''); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Gagal memuat pesanan.'); } finally { setLoading(false); } }; void load(); }, [orderId]);
  if (loading) return <div className="flex h-64 items-center justify-center text-sm text-[var(--nexus-muted)]">Memuat pesanan...</div>;
  if (error) return <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>;
  if (!order) return null;
  const canEdit = PRE_PRODUCTION_STATUSES.includes(order.status_code);
  const handleSave = async () => { if (!canEdit) return; setSaving(true); try { await craftOrdersApi.updateOrder(orderId, { deadline_at: deadline || null, customer_notes: customerNotes || null, internal_notes: internalNotes || null, courier_name: couriername || null, shipping_address: shippingAddress || null, shipping_recipient_name: shippingRecipient || null, shipping_phone: shippingPhone || null }); navigate('/app/craft/orders/' + orderId); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Gagal menyimpan perubahan.'); } finally { setSaving(false); } };
  return <div className="space-y-6 pb-12"><OrderPageHeader eyebrow={`Craft Orders / ${order.order_code}`} title={`Edit ${order.order_code}`} description="Perbarui tenggat, pengiriman, dan catatan tanpa mengubah detail transaksi." back={() => navigate('/app/craft/orders/' + orderId)} actions={<><OrderStatusBadge value={order.status_code} /><OrderPriorityBadge value={order.priority_code} /></>} />{!canEdit && <div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Pesanan ini tidak dapat diedit karena sudah memasuki tahap produksi atau selesai.</div>}<Card><div className="space-y-5 p-5 sm:p-6"><OrderSectionHeader number="01" icon={Truck} title="Informasi Pengiriman" description="Field yang terkunci mengikuti aturan status pesanan." /><div className="grid gap-4 md:grid-cols-2"><FormField label="Tenggat waktu"><span className="relative"><CalendarClock className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--nexus-muted)]" /><input type="datetime-local" className="orders-input pl-10" value={deadline} onChange={event => setDeadline(event.target.value)} disabled={!canEdit} /></span></FormField><FormField label="Kurir"><input className="orders-input" value={couriername} onChange={event => setCourierName(event.target.value)} disabled={!canEdit} /></FormField><FormField label="Penerima"><input className="orders-input" value={shippingRecipient} onChange={event => setShippingRecipient(event.target.value)} disabled={!canEdit} /></FormField><FormField label="Telepon penerima"><input className="orders-input" value={shippingPhone} onChange={event => setShippingPhone(event.target.value)} disabled={!canEdit} /></FormField><FormField label="Alamat pengiriman" className="md:col-span-2"><textarea className="orders-textarea" rows={3} value={shippingAddress} onChange={event => setShippingAddress(event.target.value)} disabled={!canEdit} /></FormField></div></div></Card><Card><div className="space-y-5 p-5 sm:p-6"><OrderSectionHeader number="02" title="Catatan" description="Bedakan instruksi untuk pelanggan dan kebutuhan internal tim." /><div className="grid gap-4 md:grid-cols-2"><FormField label="Catatan pelanggan"><textarea className="orders-textarea" rows={4} value={customerNotes} onChange={event => setCustomerNotes(event.target.value)} disabled={!canEdit} /></FormField><FormField label="Catatan internal"><textarea className="orders-textarea" rows={4} value={internalNotes} onChange={event => setInternalNotes(event.target.value)} disabled={!canEdit} /></FormField></div></div></Card>{canEdit && <div className="flex justify-end"><Button onClick={handleSave} disabled={saving} className="h-11 px-6"><Save className="h-4 w-4" />{saving ? 'Menyimpan...' : 'Simpan Perubahan'}</Button></div>}</div>;
}
