import type { AutomationTemplate } from '../craft-automations/craft-automations.types';

export const STUDIO_AUTOMATION_TEMPLATES: AutomationTemplate[] = [
  { code: 'studio-project-deadline-alert', name: 'Tenggat Proyek Mendekat', description: 'Kirim pengingat ketika tenggat proyek aktif tinggal 24 jam.', rule: { name: 'Tenggat Proyek Mendekat', trigger_type: 'sensor', trigger_event: 'studio.project.deadline_approaching', trigger_config_json: { version: 1, schedule: { type: 'cron', expression: '0 * * * *', timezone: 'Asia/Jakarta' } }, action_json: { version: 1, actions: [{ type: 'notification.create', config: { recipient_scope: 'project_manager', severity: 'warning', title_template: 'Tenggat mendekat: {{project.project_name}}', message_template: 'Proyek {{project.project_code}} mendekati tenggat {{project.deadline_at}}.' } }] }, cooldown_seconds: 86400 } },
  { code: 'studio-project-overdue-task', name: 'Proyek Terlambat → Tugas', description: 'Buat tugas tindak lanjut yang aman untuk proyek aktif yang terlambat.', rule: { name: 'Proyek Terlambat → Tugas', trigger_type: 'sensor', trigger_event: 'studio.project.overdue', trigger_config_json: { version: 1, schedule: { type: 'cron', expression: '0 9 * * *', timezone: 'Asia/Jakarta' } }, action_json: { version: 1, actions: [{ type: 'tasks.create', config: { title_template: 'Tindak lanjut proyek terlambat: {{project.project_code}}', description_template: '{{project.project_name}} melewati tenggat {{project.deadline_at}}.', priority: 'high' } }] }, cooldown_seconds: 86400 } },
  { code: 'studio-quotation-expiring', name: 'Penawaran Segera Berakhir', description: 'Ingatkan tim komersial atas penawaran yang hampir habis masa berlakunya.', rule: { name: 'Penawaran Segera Berakhir', trigger_type: 'sensor', trigger_event: 'studio.quotation.expiring', trigger_config_json: { version: 1, schedule: { type: 'cron', expression: '0 9 * * *', timezone: 'Asia/Jakarta' } }, action_json: { version: 1, actions: [{ type: 'notification.create', config: { severity: 'warning', title_template: 'Penawaran mendekati kedaluwarsa: {{quotation.quotation_number}}', message_template: 'Penawaran berlaku sampai {{quotation.valid_until}}.' } }] }, cooldown_seconds: 86400 } },
  { code: 'studio-invoice-overdue', name: 'Invoice Terlambat', description: 'Buat pengingat aman saat invoice Studio masih memiliki saldo setelah jatuh tempo.', rule: { name: 'Invoice Terlambat', trigger_type: 'sensor', trigger_event: 'studio.invoice.overdue', trigger_config_json: { version: 1, schedule: { type: 'cron', expression: '0 9 * * *', timezone: 'Asia/Jakarta' } }, action_json: { version: 1, actions: [{ type: 'tasks.create', config: { title_template: 'Tindak lanjut invoice: {{invoice.invoice_code}}', description_template: 'Invoice terlambat dengan saldo {{invoice.outstanding_amount}}.', priority: 'high' } }] }, cooldown_seconds: 86400 } },
  { code: 'studio-asset-maintenance', name: 'Perawatan Aset', description: 'Beri peringatan ketika perawatan aset mendekati atau melewati jadwal.', rule: { name: 'Perawatan Aset', trigger_type: 'sensor', trigger_event: 'studio.asset.maintenance_due', trigger_config_json: { version: 1, schedule: { type: 'cron', expression: '0 8 * * *', timezone: 'Asia/Jakarta' } }, action_json: { version: 1, actions: [{ type: 'notification.create', config: { severity: 'warning', title_template: 'Perawatan aset: {{asset.name}}', message_template: 'Aset {{asset.asset_code}} membutuhkan perawatan pada {{asset.next_due_at}}.' } }] }, cooldown_seconds: 86400 } },
  { code: 'studio-weekly-report', name: 'Laporan Studio Mingguan', description: 'Hasilkan export Analytics Studio terdaftar setiap Senin pagi.', rule: { name: 'Laporan Studio Mingguan', trigger_type: 'schedule', trigger_event: 'schedule', trigger_config_json: { version: 1, schedule: { type: 'cron', expression: '0 8 * * 1', timezone: 'Asia/Jakarta' } }, action_json: { version: 1, actions: [{ type: 'studio.analytics.generate_report', config: { report: 'overview', format: 'xlsx' } }] } } },
];

export class StudioAutomationTemplateService {
  list() { return STUDIO_AUTOMATION_TEMPLATES; }
  get(code: string) { return STUDIO_AUTOMATION_TEMPLATES.find((template) => template.code === code); }
}
