import { randomUUID } from 'crypto';
import { pool } from '../../config/database';
import { AppError } from '../../shared/errors/AppError';
import { FinancePostingService } from '../../shared/finance/finance-posting.service';
import { AuditService } from '../../shared/audit/audit.service';
import type { PostingContext } from '../../shared/finance/finance-posting.service';

const number = (v: unknown) => Number(v || 0); const code=(p:string,id:number)=>`${p}-${String(id).padStart(6,'0')}`;
export class CraftFinanceService {
  private posting = new FinancePostingService();
  async overview(context: PostingContext) { const [rows]:any=await pool.execute(`SELECT
    (SELECT COALESCE(SUM(current_balance),0) FROM treasury_accounts WHERE organization_id=? AND business_unit_id=? AND is_active=1) cash,
    (SELECT COALESCE(SUM(amount),0) FROM financial_transactions WHERE organization_id=? AND business_unit_id=? AND transaction_type='income' AND status_code='posted' AND DATE_FORMAT(transaction_date,'%Y-%m')=DATE_FORMAT(UTC_DATE(),'%Y-%m')) income,
    (SELECT COALESCE(SUM(amount),0) FROM financial_transactions WHERE organization_id=? AND business_unit_id=? AND transaction_type='expense' AND status_code='posted' AND DATE_FORMAT(transaction_date,'%Y-%m')=DATE_FORMAT(UTC_DATE(),'%Y-%m')) expense,
    (SELECT COALESCE(SUM(balance_due),0) FROM invoices WHERE organization_id=? AND business_unit_id=? AND status_code NOT IN ('paid','void')) receivables,
    (SELECT COALESCE(SUM(balance_due),0) FROM supplier_invoices WHERE business_unit_id=? AND status_code NOT IN ('paid','void')) payables`,[context.organizationId,context.businessUnitId,context.organizationId,context.businessUnitId,context.organizationId,context.businessUnitId,context.organizationId,context.businessUnitId,context.businessUnitId]);
    const [transactions]:any=await pool.execute(`SELECT ft.*,tc.name category_name,ta.name treasury_name FROM financial_transactions ft LEFT JOIN transaction_categories tc ON tc.id=ft.category_id LEFT JOIN treasury_accounts ta ON ta.id=ft.treasury_account_id WHERE ft.organization_id=? AND ft.business_unit_id=? ORDER BY ft.transaction_date DESC LIMIT 8`,[context.organizationId,context.businessUnitId]); const [treasuries]:any=await pool.execute('SELECT * FROM treasury_accounts WHERE organization_id=? AND business_unit_id=? ORDER BY is_active DESC,name',[context.organizationId,context.businessUnitId]); return {...rows[0],net_cash_flow:number(rows[0].income)-number(rows[0].expense),transactions,treasuries}; }
  async references(context:PostingContext){const [categories]:any=await pool.execute('SELECT id,code,name,transaction_type FROM transaction_categories WHERE organization_id=? AND business_unit_id=? AND is_active=1 ORDER BY name',[context.organizationId,context.businessUnitId]); const [methods]:any=await pool.execute('SELECT id,code,name,method_type FROM payment_methods WHERE is_active=1 ORDER BY name'); const [treasuries]:any=await pool.execute('SELECT id,name,account_type,current_balance,currency_code FROM treasury_accounts WHERE organization_id=? AND business_unit_id=? AND is_active=1 ORDER BY name',[context.organizationId,context.businessUnitId]); return {categories,methods,treasuries};}
  async createTreasury(context: PostingContext, data: any) {
    const connection = await pool.getConnection(); await connection.beginTransaction();
    try {
      let coa = data.coa_account_id;
      if (!coa) { const [rows]: any = await connection.execute("SELECT id FROM chart_of_accounts WHERE organization_id=? AND account_code='1000' AND is_active=1 LIMIT 1", [context.organizationId]); coa = rows[0]?.id || null; }
      const [result]: any = await connection.execute(`INSERT INTO treasury_accounts (organization_id,business_unit_id,coa_account_id,account_code,name,account_type,provider_name,account_number_masked,currency_code,opening_balance,current_balance) VALUES (?,?,?, ?,?,?,?,?,?,?,?)`, [context.organizationId, context.businessUnitId, coa, `TMP-${randomUUID()}`, data.name, data.account_type, data.provider_name || null, data.account_number_masked || null, data.currency_code, data.opening_balance, 0]);
      const id = Number(result.insertId); const accountCode = code('TRS', id);
      await connection.execute('UPDATE treasury_accounts SET account_code=? WHERE id=?', [accountCode, id]);
      if (number(data.opening_balance) > 0) await this.posting.postTreasuryOpening(connection, context, { treasuryAccountId: id, amount: data.opening_balance, date: new Date().toISOString().slice(0, 23).replace('T', ' '), description: 'Saldo awal akun kas' }, { auditModule: 'craft_finance', auditAction: 'finance.treasury_opening', entityCode: accountCode });
      await AuditService.write({ organizationId: context.organizationId, businessUnitId: context.businessUnitId, userId: context.userId, moduleCode: 'craft_finance', actionCode: 'finance.treasury_create', entityType: 'treasury_account', entityId: id, entityCode: accountCode, description: 'Membuat akun kas.', newValues: { name: data.name, account_type: data.account_type, currency_code: data.currency_code, opening_balance: data.opening_balance } }, connection);
      await connection.commit(); return { id };
    } catch (error) { await connection.rollback(); throw error; } finally { connection.release(); }
  }
  async setTreasuryStatus(context:PostingContext,id:number,active:boolean){const [r]:any=await pool.execute('UPDATE treasury_accounts SET is_active=? WHERE id=? AND organization_id=? AND business_unit_id=?',[active?1:0,id,context.organizationId,context.businessUnitId]);if(!r.affectedRows)throw new AppError(404,'TREASURY_NOT_FOUND','Akun kas tidak ditemukan.');}
  async supplierPayment(context:PostingContext,id:number,data:any){const c=await pool.getConnection();await c.beginTransaction();try{const [invoices]:any=await c.execute('SELECT supplier_party_id FROM supplier_invoices WHERE id=? AND business_unit_id=?',[id,context.businessUnitId]);if(!invoices.length)throw new AppError(404,'SUPPLIER_INVOICE_NOT_FOUND','Tagihan pemasok tidak ditemukan.');const result=await this.posting.postSupplierPayment(c,context,{supplierInvoiceId:id,partyId:invoices[0].supplier_party_id,paymentMethodId:data.payment_method_id,treasuryAccountId:data.treasury_account_id,amount:data.amount,paymentDate:data.payment_date,categoryCode:data.category_code,referenceNumber:data.reference_number,notes:data.notes});await c.commit();return{payment_id:result};}catch(e){await c.rollback();throw e;}finally{c.release();}}
  async customerPayment(context:PostingContext,id:number,data:any){const c=await pool.getConnection();await c.beginTransaction();try{const [invoices]:any=await c.execute('SELECT party_id FROM invoices WHERE id=? AND organization_id=? AND business_unit_id=?',[id,context.organizationId,context.businessUnitId]);if(!invoices.length)throw new AppError(404,'INVOICE_NOT_FOUND','Invoice tidak ditemukan.');const result=await this.posting.postCustomerPayment(c,context,{invoiceId:id,partyId:invoices[0].party_id,paymentMethodId:data.payment_method_id,treasuryAccountId:data.treasury_account_id,amount:data.amount,paymentDate:data.payment_date,referenceNumber:data.reference_number,notes:data.notes});await c.commit();return{payment_id:result};}catch(e){await c.rollback();throw e;}finally{c.release();}}
  async income(context:PostingContext,data:any){const c=await pool.getConnection();await c.beginTransaction();try{const result=await this.posting.postCashMovement(c,context,{direction:'in',amount:data.amount,transactionDate:data.transaction_date,treasuryAccountId:data.treasury_account_id,categoryCode:data.category_code,description:data.description,partyId:data.party_id||null,sourceType:'craft_manual_income',enforceSourceIdempotency:false},{auditModule:'craft_finance',auditAction:'craft.finance.manual_income'});await c.commit();return{id:result.transactionId,transaction_code:result.transactionCode};}catch(e){await c.rollback();throw e;}finally{c.release();}}
}
