import { randomUUID } from 'crypto';
import { pool } from '../../config/database';
import { AppError } from '../../shared/errors/AppError';
import { FinancePostingService } from '../../shared/finance/finance-posting.service';
import type { PostingContext } from '../../shared/finance/finance-posting.service';

const number = (v: unknown) => Number(v || 0); const code=(p:string,id:number)=>`${p}-${String(id).padStart(6,'0')}`;
export class CraftFinanceService {
  private posting = new FinancePostingService();
  async overview(context: PostingContext) { const [rows]:any=await pool.execute(`SELECT
    (SELECT COALESCE(SUM(current_balance),0) FROM treasury_accounts WHERE organization_id=? AND business_unit_id=? AND is_active=1) cash,
    (SELECT COALESCE(SUM(amount),0) FROM financial_transactions WHERE organization_id=? AND business_unit_id=? AND transaction_type='income' AND status_code='posted' AND DATE_FORMAT(transaction_date,'%Y-%m')=DATE_FORMAT(UTC_DATE(),'%Y-%m')) income,
    (SELECT COALESCE(SUM(amount),0) FROM financial_transactions WHERE organization_id=? AND business_unit_id=? AND transaction_type='expense' AND status_code='posted' AND DATE_FORMAT(transaction_date,'%Y-%m')=DATE_FORMAT(UTC_DATE(),'%Y-%m')) expense,
    (SELECT COALESCE(SUM(balance_due),0) FROM invoices WHERE organization_id=? AND business_unit_id=? AND status_code NOT IN ('paid','void')) receivables,
    (SELECT COALESCE(SUM(balance_due),0) FROM supplier_invoices WHERE business_unit_id=? AND status_code NOT IN ('paid','void')) payables`,[context.organizationId,context.businessUnitId,context.organizationId,context.businessUnitId,context.organizationId,context.businessUnitId,context.organizationId,context.businessUnitId,context.businessUnitId]);
    const [transactions]:any=await pool.execute(`SELECT ft.*,tc.name category_name,ta.name treasury_name FROM financial_transactions ft LEFT JOIN transaction_categories tc ON tc.id=ft.category_id LEFT JOIN treasury_accounts ta ON ta.id=ft.treasury_account_id WHERE ft.organization_id=? AND ft.business_unit_id=? ORDER BY ft.transaction_date DESC LIMIT 8`,[context.organizationId,context.businessUnitId]); const [treasuries]:any=await pool.execute('SELECT * FROM treasury_accounts WHERE organization_id=? AND business_unit_id=? ORDER BY is_active DESC,name',[context.organizationId,context.businessUnitId]); return {...rows[0],net_cash_flow:number(rows[0].income)-number(rows[0].expense),transactions,treasuries}; }
  async references(context:PostingContext){const [categories]:any=await pool.execute('SELECT id,code,name,transaction_type FROM transaction_categories WHERE organization_id=? AND business_unit_id=? AND is_active=1 ORDER BY name',[context.organizationId,context.businessUnitId]); const [methods]:any=await pool.execute('SELECT id,code,name,method_type FROM payment_methods WHERE is_active=1 ORDER BY name'); const [treasuries]:any=await pool.execute('SELECT id,name,account_type,current_balance,currency_code FROM treasury_accounts WHERE organization_id=? AND business_unit_id=? AND is_active=1 ORDER BY name',[context.organizationId,context.businessUnitId]); return {categories,methods,treasuries};}
  async createTreasury(context:PostingContext,data:any){const c=await pool.getConnection();await c.beginTransaction();try{let coa=data.coa_account_id;if(!coa){const [r]:any=await c.execute("SELECT id FROM chart_of_accounts WHERE organization_id=? AND account_code='1000' AND is_active=1 LIMIT 1",[context.organizationId]);coa=r[0]?.id||null;}const [result]:any=await c.execute(`INSERT INTO treasury_accounts (organization_id,business_unit_id,coa_account_id,account_code,name,account_type,provider_name,account_number_masked,currency_code,opening_balance,current_balance) VALUES (?,?,?, ?,?,?,?,?,?,?,?)`,[context.organizationId,context.businessUnitId,coa,`TMP-${randomUUID()}`,data.name,data.account_type,data.provider_name||null,data.account_number_masked||null,data.currency_code,data.opening_balance,data.opening_balance]);const id=Number(result.insertId);await c.execute('UPDATE treasury_accounts SET account_code=? WHERE id=?',[code('TRS',id),id]);if(number(data.opening_balance)>0){await c.execute(`INSERT INTO financial_transactions (organization_id,business_unit_id,transaction_code,transaction_date,transaction_type,treasury_account_id,amount,currency_code,description,source_type,source_id,status_code,created_by,posted_by,posted_at) VALUES (?,?,?,UTC_TIMESTAMP(),'adjustment',?,?,?,?,?,'treasury_opening',?,'posted',?,?,UTC_TIMESTAMP())`,[context.organizationId,context.businessUnitId,`OPN-${id}`,id,data.opening_balance,data.currency_code,'Saldo awal akun kas',id,context.userId,context.userId]);}await c.execute(`INSERT INTO audit_logs (organization_id,business_unit_id,user_id,module_code,action_code,entity_type,entity_id,entity_code,description) VALUES (?,?,?,'craft_finance','finance.treasury_create','treasury_account',?,?,?)`,[context.organizationId,context.businessUnitId,context.userId,id,code('TRS',id),'Membuat akun kas.']);await c.commit();return{id};}catch(e){await c.rollback();throw e;}finally{c.release();}}
  async setTreasuryStatus(context:PostingContext,id:number,active:boolean){const [r]:any=await pool.execute('UPDATE treasury_accounts SET is_active=? WHERE id=? AND organization_id=? AND business_unit_id=?',[active?1:0,id,context.organizationId,context.businessUnitId]);if(!r.affectedRows)throw new AppError(404,'TREASURY_NOT_FOUND','Akun kas tidak ditemukan.');}
  async supplierPayment(context:PostingContext,id:number,data:any){const c=await pool.getConnection();await c.beginTransaction();try{const [invoices]:any=await c.execute('SELECT supplier_party_id FROM supplier_invoices WHERE id=? AND business_unit_id=?',[id,context.businessUnitId]);if(!invoices.length)throw new AppError(404,'SUPPLIER_INVOICE_NOT_FOUND','Tagihan pemasok tidak ditemukan.');const result=await this.posting.postSupplierPayment(c,context,{supplierInvoiceId:id,partyId:invoices[0].supplier_party_id,paymentMethodId:data.payment_method_id,treasuryAccountId:data.treasury_account_id,amount:data.amount,paymentDate:data.payment_date,categoryCode:data.category_code,referenceNumber:data.reference_number,notes:data.notes});await c.commit();return{payment_id:result};}catch(e){await c.rollback();throw e;}finally{c.release();}}
  async customerPayment(context:PostingContext,id:number,data:any){const c=await pool.getConnection();await c.beginTransaction();try{const [invoices]:any=await c.execute('SELECT party_id FROM invoices WHERE id=? AND organization_id=? AND business_unit_id=?',[id,context.organizationId,context.businessUnitId]);if(!invoices.length)throw new AppError(404,'INVOICE_NOT_FOUND','Invoice tidak ditemukan.');const result=await this.posting.postCustomerPayment(c,context,{invoiceId:id,partyId:invoices[0].party_id,paymentMethodId:data.payment_method_id,treasuryAccountId:data.treasury_account_id,amount:data.amount,paymentDate:data.payment_date,referenceNumber:data.reference_number,notes:data.notes});await c.commit();return{payment_id:result};}catch(e){await c.rollback();throw e;}finally{c.release();}}
  async income(context:PostingContext,data:any){const c=await pool.getConnection();await c.beginTransaction();try{const [cat]:any=await c.execute('SELECT id FROM transaction_categories WHERE organization_id=? AND business_unit_id=? AND code=? AND transaction_type=\'income\' AND is_active=1',[context.organizationId,context.businessUnitId,data.category_code]);if(!cat.length)throw new AppError(400,'INVALID_TRANSACTION_CATEGORY','Kategori pendapatan tidak valid.');const [t]:any=await c.execute('SELECT current_balance,currency_code FROM treasury_accounts WHERE id=? AND organization_id=? AND business_unit_id=? AND is_active=1 FOR UPDATE',[data.treasury_account_id,context.organizationId,context.businessUnitId]);if(!t.length)throw new AppError(400,'INVALID_TREASURY_ACCOUNT','Akun kas tidak valid.');const [r]:any=await c.execute(`INSERT INTO financial_transactions (organization_id,business_unit_id,transaction_code,transaction_date,transaction_type,category_id,treasury_account_id,party_id,amount,currency_code,description,status_code,created_by,posted_by,posted_at) VALUES (?,?,?,?,'income',?,?,?,?,?,?, 'posted',?,?,UTC_TIMESTAMP())`,[context.organizationId,context.businessUnitId,`TMP-${randomUUID()}`,data.transaction_date,cat[0].id,data.treasury_account_id,data.party_id||null,data.amount,t[0].currency_code,data.description,context.userId,context.userId]);const id=Number(r.insertId);await c.execute('UPDATE financial_transactions SET transaction_code=? WHERE id=?',[code('FTX',id),id]);await c.execute('UPDATE treasury_accounts SET current_balance=current_balance+? WHERE id=?',[data.amount,data.treasury_account_id]);await c.commit();return{id};}catch(e){await c.rollback();throw e;}finally{c.release();}}
}
