import React from 'react';
import { ArrowRight, CircleAlert } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../../../components/ui/Button';
import { Card } from '../../../components/ui/Card';
import { studioBillingApi } from '../../../services/api/studio-billing.api';
import type { StudioOutstandingResponse } from '../../../types/studio-billing';
import { EmptyState, ErrorBanner, InvoiceStatusBadge, Kpi, LoadingState, StudioBillingHeader, dateOnly, money } from './components/BillingUI';

export function OutstandingBillingPage() {
  const navigate = useNavigate(); const [result, setResult] = React.useState<StudioOutstandingResponse | null>(null); const [overdue, setOverdue] = React.useState(false); const [error, setError] = React.useState<string | null>(null);
  const load = React.useCallback(async () => { try { setResult(await studioBillingApi.getOutstanding({ overdue, limit: 50 })); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Gagal memuat outstanding.'); } }, [overdue]); React.useEffect(() => { void load(); }, [load]);
  if (!result && !error) return <LoadingState />;
  return <div className="space-y-6 pb-8"><StudioBillingHeader title="Tagihan Belum Dibayar" description="Tampilan operasional piutang Studio. Saldo dan status pembayaran dibaca dari data invoice/pembayaran kanonis." actions={<Button variant={overdue ? 'primary' : 'outline'} onClick={() => setOverdue(value => !value)}><CircleAlert className="h-4 w-4" /> {overdue ? 'Menampilkan Terlambat' : 'Filter Terlambat'}</Button>} /><ErrorBanner message={error} />{result && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="Total Outstanding" value={money(result.summary.total_outstanding)} /><Kpi label="Nilai Terlambat" value={money(result.summary.overdue_amount)} tone="danger" /><Kpi label="Jatuh Tempo 7 Hari" value={money(result.summary.due_in_7_days)} tone="warning" /><Kpi label="Invoice Terlambat" value={result.summary.overdue_invoice_count} tone={result.summary.overdue_invoice_count ? 'danger' : 'default'} /><Kpi label="Klien Berutang" value={result.summary.clients_with_outstanding} /></div><Card>{!result.items.length ? <EmptyState title="Tidak ada tagihan outstanding" description="Invoice yang sudah dibayar, void, refunded, dan Draft tidak ditampilkan di sini." /> : <div className="divide-y divide-[var(--nexus-border)]">{result.items.map(invoice => <button className="flex w-full flex-col gap-3 p-5 text-left transition hover:bg-gray-50 md:flex-row md:items-center" key={invoice.id} onClick={() => navigate(`/app/studio/billing/invoices/${invoice.id}`)}><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-[var(--nexus-charcoal)]">{invoice.invoice_number}</p><InvoiceStatusBadge status={invoice.effective_status} /></div><p className="mt-1 text-sm text-[var(--nexus-muted)]">{invoice.client_name}{invoice.project_name ? ` • ${invoice.project_code} — ${invoice.project_name}` : ''}</p>{invoice.next_schedule_due_date && <p className="mt-1 text-xs text-[var(--nexus-muted)]">Termin berikutnya: {invoice.next_schedule_label || 'Termin'} • {dateOnly(invoice.next_schedule_due_date)} • {money(invoice.next_schedule_balance || 0, invoice.currency_code)}</p>}</div><div className="grid grid-cols-2 gap-x-5 gap-y-1 text-sm md:block md:text-right"><span className="text-[var(--nexus-muted)]">Jatuh tempo</span><span>{dateOnly(invoice.due_date)}</span><span className="text-[var(--nexus-muted)] md:mt-1 md:block">Outstanding</span><strong>{money(invoice.balance_due, invoice.currency_code)}</strong></div><ArrowRight className="hidden h-4 w-4 text-[var(--nexus-muted)] md:block" /></button>)}</div>}</Card></>}</div>;
}
