import React from 'react';
import { Eye, Plus, ToggleLeft, ToggleRight } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../../../components/ui/Button';
import { Card } from '../../../components/ui/Card';
import { useAuth } from '../../../context/AuthContext';
import { studioBillingApi } from '../../../services/api/studio-billing.api';
import type { Paginated, StudioQuotationTemplateSummary } from '../../../types/studio-billing';
import { EmptyState, ErrorBanner, LoadingState, StudioBillingHeader, dateOnly, inputClass } from './components/BillingUI';

export function QuotationTemplatesPage() {
  const navigate = useNavigate(); const { hasPermission } = useAuth(); const canWrite = hasPermission('studio.billing.write'); const [result, setResult] = React.useState<Paginated<StudioQuotationTemplateSummary> | null>(null); const [error, setError] = React.useState<string | null>(null); const [busy, setBusy] = React.useState<number | null>(null); const [search, setSearch] = React.useState('');
  const load = React.useCallback(async () => { try { setResult(await studioBillingApi.getTemplates({ search, limit: 50 })); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Gagal memuat template.'); } }, [search]);
  React.useEffect(() => { void load(); }, [load]);
  const toggle = async (template: StudioQuotationTemplateSummary) => { setBusy(template.id); try { template.is_active ? await studioBillingApi.deactivateTemplate(template.id) : await studioBillingApi.activateTemplate(template.id); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Gagal mengubah template.'); } finally { setBusy(null); } };
  return <div className="space-y-6 pb-8"><StudioBillingHeader title="Template Penawaran" description="Konten dan item default untuk mempercepat penyusunan penawaran Studio." back={() => navigate('/app/studio/billing/quotations')} actions={canWrite ? <Button onClick={() => navigate('/app/studio/billing/quotation-templates/new')}><Plus className="h-4 w-4" /> Tambah Template</Button> : undefined} /><ErrorBanner message={error} /><Card className="overflow-visible"><div className="border-b border-[var(--nexus-border)] p-4"><input className={inputClass} value={search} onChange={event => setSearch(event.target.value)} placeholder="Cari kode atau nama template..." /></div>{!result ? <LoadingState /> : !result.items.length ? <EmptyState title="Belum ada template" description="Simpan paket scope dan ketentuan umum agar bisa digunakan kembali." /> : <div className="overflow-x-auto"><table className="min-w-[780px] w-full text-sm"><thead className="bg-[var(--nexus-cream-soft)] text-left text-[10px] uppercase tracking-[.11em] text-[var(--nexus-muted)]"><tr><th className="px-5 py-3">Template</th><th className="px-4 py-3">Validitas Default</th><th className="px-4 py-3">Item</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Diperbarui</th><th /></tr></thead><tbody>{result.items.map(template => <tr key={template.id} className="border-t border-[var(--nexus-border)]"><td className="px-5 py-4"><p className="font-semibold">{template.name}</p><p className="text-xs text-[var(--nexus-muted)]">{template.template_code}</p></td><td className="px-4 py-4">{template.default_valid_days} hari</td><td className="px-4 py-4">{template.item_count}</td><td className="px-4 py-4"><span className={template.is_active ? 'text-emerald-700' : 'text-gray-500'}>{template.is_active ? 'Aktif' : 'Nonaktif'}</span></td><td className="px-4 py-4 text-[var(--nexus-muted)]">{dateOnly(template.updated_at)}</td><td className="px-4 py-4"><div className="flex gap-1">{canWrite && <Button size="sm" variant="ghost" onClick={() => navigate(`/app/studio/billing/quotation-templates/${template.id}/edit`)}><Eye className="h-4 w-4" /> Edit</Button>}{canWrite && <Button size="sm" variant="ghost" onClick={() => void toggle(template)} disabled={busy === template.id}>{template.is_active ? <ToggleRight className="h-4 w-4" /> : <ToggleLeft className="h-4 w-4" />}</Button>}</div></td></tr>)}</tbody></table></div>}</Card></div>;
}
