import type { NextFunction, Request, Response } from 'express';
import { z } from 'zod';
import { AppError } from '../../shared/errors/AppError';
import { getBusinessUnitByCode } from '../../shared/utils/business-unit';
import { sendSuccess } from '../../shared/utils/response';
import { assetStatusSchema, assignmentSchema, createAssetSchema, maintenanceCompleteSchema, maintenanceSchema, maintenanceUpdateSchema, returnAssignmentSchema, updateAssetSchema } from './studio-equipment.schema';
import { studioEquipmentService } from './studio-equipment.service';

const studio = () => getBusinessUnitByCode('STUDIO');
const actorId = (req: Request) => Number((req as any).user?.id);
const id = (value: unknown, label: string) => { const parsed = Number.parseInt(String(value || ''), 10); if (!Number.isInteger(parsed) || parsed <= 0) throw new AppError(400, 'INVALID_ID', `${label} tidak valid.`); return parsed; };
const optionalId = (value: unknown) => value === undefined || value === null || value === '' ? undefined : id(value, 'ID');
const asValidationError = (error: unknown, message: string) => error instanceof z.ZodError ? new AppError(400, 'VALIDATION_ERROR', message, error.issues) : error;

export class StudioEquipmentController {
  getOverview = async (_req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioEquipmentService.getOverview(await studio())); } catch (error) { next(error); } };
  getAssets = async (req: Request, res: Response, next: NextFunction) => { try {
    sendSuccess(res, await studioEquipmentService.listAssets(await studio(), { page: optionalId(req.query.page) || 1, limit: optionalId(req.query.limit) || 20, search: req.query.search as string || undefined, status: req.query.status as string || undefined, category: req.query.category as string || undefined, assignedUserId: optionalId(req.query.assigned_user_id), location: req.query.location as string || undefined, maintenanceDue: req.query.maintenance_due as string || undefined, assignmentState: req.query.assignment_state as string || undefined, sortBy: req.query.sort_by as string || undefined, sortOrder: req.query.sort_order === 'asc' ? 'asc' : 'desc' }));
  } catch (error) { next(error); } };
  createAsset = async (req: Request, res: Response, next: NextFunction) => { try { const data = createAssetSchema.parse(req.body); sendSuccess(res, await studioEquipmentService.createAsset(data, actorId(req), await studio()), undefined, 201); } catch (error) { next(asValidationError(error, 'Data aset tidak valid.')); } };
  getAsset = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioEquipmentService.getAssetDetail(id(req.params.id, 'ID aset'), await studio())); } catch (error) { next(error); } };
  updateAsset = async (req: Request, res: Response, next: NextFunction) => { try { const data = updateAssetSchema.parse(req.body); sendSuccess(res, await studioEquipmentService.updateAsset(id(req.params.id, 'ID aset'), data, actorId(req), await studio())); } catch (error) { next(asValidationError(error, 'Data aset tidak valid.')); } };
  changeStatus = async (req: Request, res: Response, next: NextFunction) => { try { const data = assetStatusSchema.parse(req.body); sendSuccess(res, await studioEquipmentService.changeStatus(id(req.params.id, 'ID aset'), data.status as any, data.reason, data.notes, actorId(req), await studio())); } catch (error) { next(asValidationError(error, 'Perubahan status aset tidak valid.')); } };
  getActivity = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioEquipmentService.getActivity(id(req.params.id, 'ID aset'), await studio())); } catch (error) { next(error); } };

  getAssetAssignments = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioEquipmentService.getAssignments(id(req.params.id, 'ID aset'), await studio())); } catch (error) { next(error); } };
  createAssignment = async (req: Request, res: Response, next: NextFunction) => { try { const data = assignmentSchema.parse(req.body); sendSuccess(res, await studioEquipmentService.createAssignment(id(req.params.id, 'ID aset'), data, actorId(req), await studio()), undefined, 201); } catch (error) { next(asValidationError(error, 'Data penugasan aset tidak valid.')); } };
  getAssignments = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioEquipmentService.listAssignments(await studio(), { page: optionalId(req.query.page) || 1, limit: optionalId(req.query.limit) || 50, state: req.query.state as string || undefined, assetId: optionalId(req.query.asset_id), projectId: optionalId(req.query.project_id), category: req.query.category as string || undefined, startDate: req.query.start_date as string || undefined, endDate: req.query.end_date as string || undefined })); } catch (error) { next(error); } };
  returnAssignment = async (req: Request, res: Response, next: NextFunction) => { try { const data = returnAssignmentSchema.parse(req.body || {}); sendSuccess(res, await studioEquipmentService.returnAssignment(id(req.params.assignmentId, 'ID penugasan'), data.returned_at, actorId(req), await studio())); } catch (error) { next(asValidationError(error, 'Data pengembalian aset tidak valid.')); } };
  cancelAssignment = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioEquipmentService.cancelFutureAssignment(id(req.params.assignmentId, 'ID penugasan'), actorId(req), await studio())); } catch (error) { next(error); } };
  availability = async (req: Request, res: Response, next: NextFunction) => { try { const from = String(req.query.from || ''); const until = String(req.query.until || ''); if (!from || !until || Number.isNaN(Date.parse(from)) || Number.isNaN(Date.parse(until)) || new Date(until).getTime() <= new Date(from).getTime()) throw new AppError(400, 'INVALID_AVAILABILITY_WINDOW', 'Rentang waktu ketersediaan tidak valid.'); sendSuccess(res, await studioEquipmentService.availability(await studio(), from, until, (req.query.category as string) || undefined)); } catch (error) { next(error); } };

  getAssetMaintenance = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioEquipmentService.getMaintenance(id(req.params.id, 'ID aset'), await studio())); } catch (error) { next(error); } };
  getMaintenance = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioEquipmentService.listMaintenance(await studio(), { assetId: optionalId(req.query.asset_id), category: req.query.category as string || undefined, providerId: optionalId(req.query.provider_id), state: req.query.state as string || undefined, dateFrom: req.query.date_from as string || undefined, dateTo: req.query.date_to as string || undefined })); } catch (error) { next(error); } };
  startMaintenance = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioEquipmentService.startMaintenance(id(req.params.id, 'ID aset'), actorId(req), await studio())); } catch (error) { next(error); } };
  completeMaintenance = async (req: Request, res: Response, next: NextFunction) => { try { const { outcome_status, ...data } = maintenanceCompleteSchema.parse(req.body); sendSuccess(res, await studioEquipmentService.completeMaintenance(id(req.params.id, 'ID aset'), data, outcome_status, actorId(req), await studio()), undefined, 201); } catch (error) { next(asValidationError(error, 'Data penyelesaian perawatan tidak valid.')); } };
  addMaintenanceRecord = async (req: Request, res: Response, next: NextFunction) => { try { const data = maintenanceSchema.parse(req.body); sendSuccess(res, await studioEquipmentService.addHistoricalMaintenance(id(req.params.id, 'ID aset'), data, actorId(req), await studio()), undefined, 201); } catch (error) { next(asValidationError(error, 'Data riwayat perawatan tidak valid.')); } };
  updateMaintenanceRecord = async (req: Request, res: Response, next: NextFunction) => { try { const data = maintenanceUpdateSchema.parse(req.body); sendSuccess(res, await studioEquipmentService.updateMaintenanceRecord(id(req.params.id, 'ID aset'), id(req.params.recordId, 'ID riwayat perawatan'), data, actorId(req), await studio())); } catch (error) { next(asValidationError(error, 'Data riwayat perawatan tidak valid.')); } };
  getReferences = async (_req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioEquipmentService.getReferences(await studio())); } catch (error) { next(error); } };
}
