import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Clock3 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../../../components/ui/Button';
import { Card } from '../../../components/ui/Card';
import { useAuth } from '../../../context/AuthContext';
import { craftProductionApi } from '../../../services/api/craft-production.api';
import type { CalendarView, PrinterOption, ProductionCalendarEntry, ProductionJob } from '../../../types/craft-production';
import { ScheduleJobModal } from './components/JobActionDialogs';
import { DeadlineRiskBadge, formatProductionDate, ProductionEmptyState, ProductionError, ProductionLoading, ProductionPageHeader, ProductionPriorityBadge, ProductionStatusBadge } from './components/ProductionUI';

export function ProductionCalendarPage() {
  const navigate = useNavigate();
  const { hasPermission } = useAuth();
  const canWrite = hasPermission('craft.production.write');
  const [view, setView] = useState<CalendarView>('week');
  const [date, setDate] = useState(todayInput());
  const [printerId, setPrinterId] = useState<number | undefined>();
  const [printers, setPrinters] = useState<PrinterOption[]>([]);
  const [events, setEvents] = useState<ProductionCalendarEntry[]>([]);
  const [scheduling, setScheduling] = useState<ProductionJob | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const range = useMemo(() => calendarRange(date, view), [date, view]);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const result = await craftProductionApi.getProductionCalendar(range.start.toISOString(), range.end.toISOString(), printerId); setEvents(result.events || []); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Gagal memuat kalender produksi.'); } finally { setLoading(false); } }, [printerId, range.end, range.start]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { void craftProductionApi.getReferences().then(data => setPrinters(data.printers || [])).catch(() => undefined); }, []);
  const days = useMemo(() => enumerateDays(range.start, range.end), [range.end, range.start]);
  const openSchedule = async (entry: ProductionCalendarEntry) => { try { const detail = await craftProductionApi.getPrintJob(entry.print_job_id); setScheduling(detail.job); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Gagal memuat pekerjaan untuk penjadwalan.'); } };
  const move = (direction: -1 | 1) => { const current = parseDateInput(date); current.setDate(current.getDate() + direction * (view === 'week' ? 7 : 1)); setDate(toDateInput(current)); };

  return <div className="space-y-6 pb-8"><ProductionPageHeader title="Kalender Produksi" description="Jadwal penggunaan printer berdasarkan waktu rencana pekerjaan cetak." /><div className="flex flex-col gap-3 rounded-xl border border-[var(--nexus-border)] bg-white p-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap items-center gap-2"><div className="production-segmented"><button type="button" className={view === 'day' ? 'is-active' : ''} onClick={() => setView('day')}>Hari</button><button type="button" className={view === 'week' ? 'is-active' : ''} onClick={() => setView('week')}>Minggu</button></div><Button variant="outline" size="sm" onClick={() => move(-1)} aria-label="Periode sebelumnya"><ChevronLeft className="h-4 w-4" /></Button><Button variant="outline" size="sm" onClick={() => setDate(todayInput())}>Hari Ini</Button><Button variant="outline" size="sm" onClick={() => move(1)} aria-label="Periode berikutnya"><ChevronRight className="h-4 w-4" /></Button><strong className="ml-1 text-sm">{formatRange(range.start, range.end, view)}</strong></div><div className="flex flex-wrap gap-2"><input type="date" className="production-filter-select w-auto" value={date} onChange={event => setDate(event.target.value)} aria-label="Pilih tanggal" /><select className="production-filter-select w-56" value={printerId || ''} onChange={event => setPrinterId(event.target.value ? Number(event.target.value) : undefined)} aria-label="Filter printer"><option value="">Semua Printer</option>{printers.map(printer => <option key={printer.id} value={printer.id}>{printer.name}</option>)}</select></div></div>{error && <ProductionError message={error} retry={() => void load()} />}{loading ? <ProductionLoading label="Memuat kalender produksi..." /> : events.length === 0 ? <Card><ProductionEmptyState icon={CalendarDays} title="Belum Ada Jadwal Produksi" description="Pekerjaan queued atau ready yang dijadwalkan akan muncul pada periode ini." /></Card> : <div className={`grid gap-3 ${view === 'week' ? 'xl:grid-cols-7' : 'grid-cols-1'}`}>{days.map(day => <CalendarDay key={day.toISOString()} day={day} events={events.filter(event => isSameLocalDay(new Date(event.scheduled_start_at), day))} canWrite={canWrite} onOpen={entry => navigate(`/app/craft/production/jobs/${entry.print_job_id}`)} onSchedule={entry => void openSchedule(entry)} />)}</div>}<div className="rounded-lg border border-blue-200 bg-blue-50 p-4 text-xs leading-5 text-blue-800">Jadwal menggunakan waktu rencana pekerjaan, bukan reservasi kontrol mesin. Backend tetap memvalidasi benturan interval pada printer yang sama.</div>{scheduling && <ScheduleJobModal open job={scheduling} onClose={() => setScheduling(null)} onSuccess={() => { setScheduling(null); void load(); }} onError={setError} />}</div>;
}

function CalendarDay({ day, events, canWrite, onOpen, onSchedule }: { day: Date; events: ProductionCalendarEntry[]; canWrite: boolean; onOpen: (entry: ProductionCalendarEntry) => void; onSchedule: (entry: ProductionCalendarEntry) => void; key?: React.Key }) {
  const isToday = isSameLocalDay(day, new Date());
  return <section className="min-h-64 rounded-xl border border-[var(--nexus-border)] bg-[var(--nexus-cream-soft)]/35"><div className={`border-b border-[var(--nexus-border)] px-4 py-3 ${isToday ? 'bg-[var(--nexus-yellow)]/15' : 'bg-white'}`}><p className="text-[10px] font-bold uppercase tracking-wider text-[var(--nexus-muted)]">{new Intl.DateTimeFormat('id-ID', { weekday: 'long' }).format(day)}</p><p className="mt-1 text-lg font-bold">{new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short' }).format(day)}</p></div><div className="space-y-2 p-2">{events.length ? events.sort((a, b) => new Date(a.scheduled_start_at).getTime() - new Date(b.scheduled_start_at).getTime()).map(entry => <article key={entry.id} className="rounded-lg border border-[var(--nexus-border)] bg-white p-3 shadow-sm transition hover:border-[var(--nexus-yellow-deep)]"><button type="button" onClick={() => onOpen(entry)} className="block w-full text-left"><div className="flex items-start justify-between gap-2"><span className="font-mono text-[11px] font-bold">{entry.job_code}</span><ProductionPriorityBadge value={entry.priority_code} /></div><p className="mt-2 line-clamp-2 text-xs font-semibold">{entry.item_name}</p><p className="mt-1 truncate text-[11px] text-[var(--nexus-muted)]">{entry.printer_name}</p><div className="mt-3 flex items-center gap-1 text-[11px] font-semibold"><Clock3 className="h-3 w-3" /> {formatTime(entry.scheduled_start_at)}–{formatTime(entry.scheduled_end_at)}</div><div className="mt-2 flex flex-wrap gap-1"><ProductionStatusBadge value={entry.status_code} /><DeadlineRiskBadge value={entry.deadline_risk} /></div><p className="mt-2 text-[10px] text-[var(--nexus-muted)]">Tenggat {formatProductionDate(entry.deadline_at, false)}</p></button>{canWrite && ['queued', 'ready'].includes(entry.status_code) && <button type="button" className="mt-3 text-[11px] font-semibold text-[var(--nexus-yellow-deep)] hover:underline" onClick={() => onSchedule(entry)}>Ubah jadwal</button>}</article>) : <p className="px-2 py-8 text-center text-xs text-[var(--nexus-muted)]">Tidak ada jadwal.</p>}</div></section>;
}

function calendarRange(value: string, view: CalendarView): { start: Date; end: Date } { const selected = parseDateInput(value); selected.setHours(0, 0, 0, 0); if (view === 'week') { const day = selected.getDay(); const offset = day === 0 ? -6 : 1 - day; selected.setDate(selected.getDate() + offset); } const end = new Date(selected); end.setDate(end.getDate() + (view === 'week' ? 7 : 1)); return { start: selected, end }; }
function enumerateDays(start: Date, end: Date): Date[] { const days: Date[] = []; for (const cursor = new Date(start); cursor < end; cursor.setDate(cursor.getDate() + 1)) days.push(new Date(cursor)); return days; }
function parseDateInput(value: string): Date { const [year, month, day] = value.split('-').map(Number); return new Date(year, month - 1, day); }
function toDateInput(value: Date): string { const year = value.getFullYear(); const month = String(value.getMonth() + 1).padStart(2, '0'); const day = String(value.getDate()).padStart(2, '0'); return `${year}-${month}-${day}`; }
function todayInput(): string { return toDateInput(new Date()); }
function isSameLocalDay(left: Date, right: Date): boolean { return left.getFullYear() === right.getFullYear() && left.getMonth() === right.getMonth() && left.getDate() === right.getDate(); }
function formatTime(value: string): string { const date = new Date(value); return Number.isNaN(date.getTime()) ? '-' : new Intl.DateTimeFormat('id-ID', { hour: '2-digit', minute: '2-digit' }).format(date); }
function formatRange(start: Date, end: Date, view: CalendarView): string { if (view === 'day') return new Intl.DateTimeFormat('id-ID', { weekday: 'long', day: '2-digit', month: 'long', year: 'numeric' }).format(start); const last = new Date(end); last.setDate(last.getDate() - 1); return `${new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short' }).format(start)} – ${new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }).format(last)}`; }
