import React from 'react';
import { AlertTriangle, ArrowLeft, CalendarClock, CheckCircle2, Clock3, HardDrive, PackageOpen, Pencil, Plus, Wrench } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { Button } from '../../../../components/ui/Button';
import { Card } from '../../../../components/ui/Card';
import { cn, formatCurrency, formatDate } from '../../../../lib/utils';
import type { MaintenanceDueState, StudioAsset, StudioAssetStatus } from '../../../../types/studio-equipment';

export const statusLabels: Record<StudioAssetStatus, string> = { available: 'Tersedia', in_use: 'Digunakan', maintenance: 'Perawatan', borrowed: 'Dipinjamkan', retired: 'Dipensiunkan', lost: 'Hilang' };
export const maintenanceLabels: Record<MaintenanceDueState, string> = { overdue: 'Terlambat', due_soon: 'Segera', scheduled: 'Terjadwal', unscheduled: 'Belum Dijadwalkan' };
const statusStyles: Record<StudioAssetStatus, string> = { available: 'bg-emerald-50 text-emerald-700 border-emerald-200', in_use: 'bg-blue-50 text-blue-700 border-blue-200', maintenance: 'bg-amber-50 text-amber-800 border-amber-200', borrowed: 'bg-violet-50 text-violet-700 border-violet-200', retired: 'bg-slate-100 text-slate-600 border-slate-200', lost: 'bg-red-50 text-red-700 border-red-200' };
const maintenanceStyles: Record<MaintenanceDueState, string> = { overdue: 'bg-red-50 text-red-700 border-red-200', due_soon: 'bg-amber-50 text-amber-800 border-amber-200', scheduled: 'bg-blue-50 text-blue-700 border-blue-200', unscheduled: 'bg-slate-100 text-slate-600 border-slate-200' };

export const requestError = (error: unknown, fallback: string) => error instanceof Error ? error.message : fallback;
export const dateTimeInput = (value?: string | null) => value ? value.replace(' ', 'T').slice(0, 16) : '';
export const displayDate = (value?: string | null) => value ? formatDate(value) : '—';

export function AssetStatusBadge({ status, effective }: { status: StudioAssetStatus; effective?: boolean }) { const shown = effective && status === 'available' ? 'in_use' : status; return <span className={cn('inline-flex items-center rounded-full border px-2.5 py-1 text-xs font-bold', statusStyles[shown])}>{statusLabels[shown]}{effective && status === 'available' ? ' (efektif)' : ''}</span>; }
export function MaintenanceBadge({ state }: { state?: MaintenanceDueState | null }) { if (!state) return <span className="text-sm text-[var(--nexus-muted)]">—</span>; return <span className={cn('inline-flex rounded-full border px-2.5 py-1 text-xs font-bold', maintenanceStyles[state])}>{maintenanceLabels[state]}</span>; }

export function EquipmentHeader({ eyebrow = 'OPERASIONAL STUDIO', title, description, back, actions }: { eyebrow?: string; title: string; description: string; back?: () => void; actions?: React.ReactNode }) { return <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div className="flex gap-3"><>{back && <Button variant="outline" size="sm" onClick={back} className="mt-1"><ArrowLeft className="h-4 w-4" /> Kembali</Button>}</><div><p className="text-xs font-bold tracking-[0.16em] text-[var(--nexus-yellow-deep)]">{eyebrow}</p><h1 className="mt-1 text-2xl font-bold text-[var(--nexus-charcoal)] sm:text-3xl">{title}</h1><p className="mt-2 max-w-3xl text-sm text-[var(--nexus-muted)]">{description}</p></div></div><div className="flex flex-wrap gap-2">{actions}</div></div>; }

export function Kpi({ label, value, hint, tone = 'default' }: { label: string; value: React.ReactNode; hint?: string; tone?: 'default' | 'danger' | 'warning' }) { const styles = tone === 'danger' ? 'border-red-200 bg-red-50/60' : tone === 'warning' ? 'border-amber-200 bg-amber-50/60' : ''; return <Card className={cn('p-4', styles)}><p className="text-xs font-bold uppercase tracking-wide text-[var(--nexus-muted)]">{label}</p><p className="mt-2 text-2xl font-bold text-[var(--nexus-charcoal)]">{value}</p>{hint && <p className="mt-1 text-xs text-[var(--nexus-muted)]">{hint}</p>}</Card>; }

export function Loading({ label = 'Memuat data...' }: { label?: string }) { return <div className="rounded-xl border border-dashed border-[var(--nexus-border)] bg-white p-10 text-center text-sm text-[var(--nexus-muted)]">{label}</div>; }
export function ErrorBanner({ message, onDismiss }: { message?: string | null; onDismiss?: () => void }) { if (!message) return null; return <div className="flex items-start justify-between gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><span className="flex gap-2"><AlertTriangle className="h-5 w-5 shrink-0" />{message}</span>{onDismiss && <button onClick={onDismiss} className="font-bold">×</button>}</div>; }
export function Empty({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="flex flex-col items-center p-10 text-center"><PackageOpen className="h-10 w-10 text-[var(--nexus-muted)]" /><h3 className="mt-4 font-bold">{title}</h3><p className="mt-1 max-w-md text-sm text-[var(--nexus-muted)]">{description}</p>{action && <div className="mt-4">{action}</div>}</div>; }

export function AssetName({ asset }: { asset: StudioAsset }) { return <Link to={`/app/studio/equipment/assets/${asset.id}`} className="group flex min-w-48 items-center gap-3"><span className="rounded-lg bg-[var(--nexus-cream-soft)] p-2 text-[var(--nexus-yellow-deep)]"><HardDrive className="h-4 w-4" /></span><span><span className="block font-semibold group-hover:underline">{asset.name}</span><span className="studio-code">{asset.asset_code}</span></span></Link>; }

export function AssetTable({ assets, canWrite, onStartMaintenance }: { assets: StudioAsset[]; canWrite?: boolean; onStartMaintenance?: (asset: StudioAsset) => void }) { const navigate = useNavigate(); if (!assets.length) return <Empty title="Belum Ada Peralatan & Aset" description="Tambahkan aset Studio pertama untuk mulai mengelola ketersediaan dan perawatan." action={canWrite ? <Button onClick={() => navigate('/app/studio/equipment/assets/new')}><Plus className="h-4 w-4" /> Tambah Aset</Button> : undefined} />; return <div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="border-b border-[var(--nexus-border)] bg-[var(--nexus-cream-soft)]/50 text-xs uppercase tracking-wide text-[var(--nexus-muted)]"><tr><th className="p-3 font-bold">Aset</th><th className="p-3 font-bold">Kategori</th><th className="p-3 font-bold">Status</th><th className="p-3 font-bold">Proyek Saat Ini</th><th className="p-3 font-bold">Custodian</th><th className="p-3 font-bold">Lokasi</th><th className="p-3 font-bold">Perawatan Berikut</th><th className="p-3 font-bold">Nilai Buku</th><th className="p-3 font-bold">Aksi</th></tr></thead><tbody className="divide-y divide-[var(--nexus-border)]">{assets.map(asset => <tr key={asset.id} className="hover:bg-[var(--nexus-cream-soft)]/30"><td className="p-3"><AssetName asset={asset} /></td><td className="p-3">{asset.category}<span className="mt-1 block text-xs text-[var(--nexus-muted)]">{[asset.brand, asset.model].filter(Boolean).join(' · ') || '—'}</span></td><td className="p-3"><AssetStatusBadge status={asset.status_code} effective={asset.is_effectively_in_use} /></td><td className="p-3">{asset.current_project_id ? <Link className="font-medium text-blue-700 hover:underline" to={`/app/studio/projects/${asset.current_project_id}`}>{asset.current_project_name}</Link> : asset.next_project_name ? <span><b>Berikut:</b> {asset.next_project_name}</span> : '—'}</td><td className="p-3">{asset.custodian_name || '—'}</td><td className="p-3">{asset.location_name || '—'}</td><td className="p-3">{asset.next_due_at ? <div><MaintenanceBadge state={asset.maintenance_due_state} /><p className="mt-1 text-xs text-[var(--nexus-muted)]">{displayDate(asset.next_due_at)}</p></div> : <MaintenanceBadge state="unscheduled" />}</td><td className="p-3 font-semibold">{asset.current_book_value === null ? '—' : formatCurrency(asset.current_book_value)}</td><td className="p-3"><div className="flex gap-1">{canWrite && <Button size="sm" variant="ghost" onClick={() => navigate(`/app/studio/equipment/assets/${asset.id}/edit`)} aria-label={`Edit ${asset.name}`}><Pencil className="h-4 w-4" /></Button>}{canWrite && asset.status_code === 'available' && <Button size="sm" variant="ghost" onClick={() => onStartMaintenance?.(asset)} aria-label={`Mulai perawatan ${asset.name}`}><Wrench className="h-4 w-4" /></Button>}</div></td></tr>)}</tbody></table></div>; }

export function AttentionItem({ icon = 'clock', title, detail, tone = 'default', to }: { icon?: 'clock' | 'warning' | 'check'; title: string; detail: string; tone?: 'default' | 'danger' | 'warning'; to?: string }) { const Icon = icon === 'warning' ? AlertTriangle : icon === 'check' ? CheckCircle2 : Clock3; const cls = tone === 'danger' ? 'text-red-700 bg-red-50' : tone === 'warning' ? 'text-amber-800 bg-amber-50' : 'text-blue-700 bg-blue-50'; const content = <><span className={cn('rounded-lg p-2', cls)}><Icon className="h-4 w-4" /></span><span><b className="block">{title}</b><span className="text-xs text-[var(--nexus-muted)]">{detail}</span></span></>; return to ? <Link to={to} className="flex gap-3 rounded-lg p-3 hover:bg-[var(--nexus-cream-soft)]">{content}</Link> : <div className="flex gap-3 rounded-lg p-3">{content}</div>; }

export function DateRange({ from, until }: { from: string | null; until: string | null }) { return <span className="flex items-center gap-1 text-xs text-[var(--nexus-muted)]"><CalendarClock className="h-3.5 w-3.5" />{displayDate(from)}{until ? ` – ${displayDate(until)}` : ' – belum ditentukan'}</span>; }
