import type { NextFunction, Request, Response } from 'express';
import { z } from 'zod';
import { sendSuccess } from '../../shared/utils/response';
import { getStudioBusinessUnit, parseNumericId } from '../studio-projects/studio-projects.helpers';
import { assignmentEndSchema, assignmentSchema, assignmentUpdateSchema, contactInputSchema, contactUpdateSchema, createExternalPartySchema, deactivateRoleSchema, duplicateSchema, managedRoleSchema, updateExternalPartySchema } from './studio-vendors.schema';
import { studioVendorsService } from './studio-vendors.service';

const actorId = (req: Request) => Number((req as any).user?.id);
const validation = (error: unknown, message: string) => error instanceof z.ZodError ? Object.assign(error, { message }) : error;
const positive = (value: unknown, name: string) => parseNumericId(String(value), name);
const optionalInt = (value: unknown) => { const parsed = Number.parseInt(String(value || ''), 10); return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined; };
const csvCell = (value: unknown) => { let text = String(value ?? ''); if (/^[=+\-@]/.test(text)) text = `'${text}`; return `"${text.replaceAll('"', '""')}"`; };

export class StudioVendorsController {
  private id = (req: Request) => positive(req.params.id, 'ID pihak eksternal');
  private filters(req: Request) { return { page: optionalInt(req.query.page) || 1, limit: optionalInt(req.query.limit) || 20, search: typeof req.query.search === 'string' ? req.query.search : undefined, role: typeof req.query.role === 'string' ? req.query.role as any : undefined, relationshipStatus: typeof req.query.relationship_status === 'string' ? req.query.relationship_status as any : undefined, partyKind: typeof req.query.party_kind === 'string' ? req.query.party_kind : undefined, city: typeof req.query.city === 'string' ? req.query.city : undefined, hasActiveAssignment: req.query.has_active_assignment === 'true', sortBy: typeof req.query.sort_by === 'string' ? req.query.sort_by : undefined, sortOrder: req.query.sort_order === 'desc' ? 'desc' as const : 'asc' as const }; }
  summary = async (_req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioVendorsService.summary(await getStudioBusinessUnit())); } catch (error) { next(error); } };
  list = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioVendorsService.list(this.filters(req), await getStudioBusinessUnit())); } catch (error) { next(error); } };
  export = async (req: Request, res: Response, next: NextFunction) => { try {
    const result = await studioVendorsService.list({ ...this.filters(req), page: 1, limit: 100 }, await getStudioBusinessUnit());
    const header = ['Party Code', 'Name', 'Party Type', 'Roles', 'Email', 'Phone', 'City', 'Primary Contact', 'Active Assignments', 'Total Projects', 'Total Agreed Fee', 'Recorded Expenses', 'Status'];
    const rows = result.items.map((item: any) => [item.code, item.display_name, item.party_kind, item.managed_roles.join(' / '), item.email, item.phone, item.city, item.primary_contact_name, item.active_assignment_count, item.total_project_count, item.total_agreed_fee, item.recorded_expenses, item.relationship_status]);
    res.status(200).type('text/csv; charset=utf-8').attachment('studio-external-parties.csv').send(`\uFEFF${[header, ...rows].map(row => row.map(csvCell).join(',')).join('\n')}`);
  } catch (error) { next(error); } };
  duplicates = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioVendorsService.duplicates(duplicateSchema.parse(req.body ?? {}), await getStudioBusinessUnit())); } catch (error) { next(validation(error, 'Data pengecekan duplikat tidak valid.')); } };
  create = async (req: Request, res: Response, next: NextFunction) => { try { const data = createExternalPartySchema.parse(req.body); sendSuccess(res, await studioVendorsService.create({ ...data, email: data.email || null, website: data.website || null }, actorId(req), await getStudioBusinessUnit()), undefined, 201); } catch (error) { next(validation(error, 'Data pihak eksternal tidak valid.')); } };
  detail = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioVendorsService.detail(this.id(req), await getStudioBusinessUnit())); } catch (error) { next(error); } };
  update = async (req: Request, res: Response, next: NextFunction) => { try { const data = updateExternalPartySchema.parse(req.body); const payload: Record<string, unknown> = { ...data }; if (Object.prototype.hasOwnProperty.call(data, 'email') && data.email === '') payload.email = null; if (Object.prototype.hasOwnProperty.call(data, 'website') && data.website === '') payload.website = null; sendSuccess(res, await studioVendorsService.update(this.id(req), payload, actorId(req), await getStudioBusinessUnit())); } catch (error) { next(validation(error, 'Data pihak eksternal tidak valid.')); } };
  activateRole = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioVendorsService.activateRole(this.id(req), managedRoleSchema.parse(req.params.role), actorId(req), await getStudioBusinessUnit())); } catch (error) { next(validation(error, 'Peran tidak valid.')); } };
  deactivateRole = async (req: Request, res: Response, next: NextFunction) => { try { const data = deactivateRoleSchema.parse(req.body ?? {}); sendSuccess(res, await studioVendorsService.deactivateRole(this.id(req), managedRoleSchema.parse(req.params.role), data.reason || null, data.confirm_active_assignments, actorId(req), await getStudioBusinessUnit())); } catch (error) { next(validation(error, 'Data penonaktifan tidak valid.')); } };
  contacts = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioVendorsService.contacts(this.id(req), await getStudioBusinessUnit())); } catch (error) { next(error); } };
  createContact = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioVendorsService.createContact(this.id(req), contactInputSchema.parse(req.body), actorId(req), await getStudioBusinessUnit()), undefined, 201); } catch (error) { next(validation(error, 'Data kontak tidak valid.')); } };
  updateContact = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioVendorsService.updateContact(this.id(req), positive(req.params.contactId, 'ID kontak'), contactUpdateSchema.parse(req.body), actorId(req), await getStudioBusinessUnit())); } catch (error) { next(validation(error, 'Data kontak tidak valid.')); } };
  deleteContact = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioVendorsService.deleteContact(this.id(req), positive(req.params.contactId, 'ID kontak'), actorId(req), await getStudioBusinessUnit())); } catch (error) { next(error); } };
  assignments = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioVendorsService.assignments(this.id(req), await getStudioBusinessUnit())); } catch (error) { next(error); } };
  addAssignment = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioVendorsService.addAssignment(this.id(req), assignmentSchema.parse(req.body), actorId(req), await getStudioBusinessUnit()), undefined, 201); } catch (error) { next(validation(error, 'Data penugasan tidak valid.')); } };
  updateAssignment = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioVendorsService.updateAssignment(this.id(req), positive(req.params.assignmentId, 'ID penugasan'), assignmentUpdateSchema.parse(req.body), actorId(req), await getStudioBusinessUnit())); } catch (error) { next(validation(error, 'Data penugasan tidak valid.')); } };
  endAssignment = async (req: Request, res: Response, next: NextFunction) => { try { const data = assignmentEndSchema.parse(req.body ?? {}); sendSuccess(res, await studioVendorsService.endAssignment(this.id(req), positive(req.params.assignmentId, 'ID penugasan'), data.end_date || null, actorId(req), await getStudioBusinessUnit())); } catch (error) { next(validation(error, 'Data pengakhiran penugasan tidak valid.')); } };
  commercial = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioVendorsService.commercial(this.id(req), await getStudioBusinessUnit())); } catch (error) { next(error); } };
  expenses = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioVendorsService.expenses(this.id(req), await getStudioBusinessUnit())); } catch (error) { next(error); } };
  maintenance = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioVendorsService.maintenance(this.id(req), await getStudioBusinessUnit())); } catch (error) { next(error); } };
  activity = async (req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioVendorsService.activity(this.id(req), await getStudioBusinessUnit())); } catch (error) { next(error); } };
  projects = async (_req: Request, res: Response, next: NextFunction) => { try { sendSuccess(res, await studioVendorsService.projects(await getStudioBusinessUnit())); } catch (error) { next(error); } };
}
