import { api } from '../../lib/api';
import type { AutomationCatalogScope, AutomationEvent, AutomationMeta, AutomationOverview, AutomationPage, AutomationRule, AutomationRulePayload, AutomationRun, AutomationTemplate, AutomationWorkspace } from '../../types/automations';

const base = '/automations';
const query = (filters: Record<string, string | number | undefined>) => { const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value !== undefined && value !== '') params.set(key, String(value)); }); const value = params.toString(); return value ? `?${value}` : ''; };

export const automationsApi = {
  meta: () => api.get<AutomationMeta>(`${base}/meta`), overview: (filters: Record<string, string | number | undefined> = {}) => api.get<AutomationOverview>(`${base}/overview${query(filters)}`), catalog: (workspace?: AutomationWorkspace) => api.get<AutomationCatalogScope[]>(`${base}/catalog${workspace ? `?workspace=${workspace}` : ''}`), templates: (workspace?: AutomationWorkspace) => api.get<AutomationTemplate[]>(`${base}/templates${workspace ? `?workspace=${workspace}` : ''}`),
  rules: (filters: Record<string, string | number | undefined> = {}) => api.get<AutomationPage<AutomationRule>>(`${base}/rules${query(filters)}`), rule: (id: number) => api.get<AutomationRule>(`${base}/rules/${id}`), createRule: (data: AutomationRulePayload) => api.post<{ id: number; rule_code: string }>(`${base}/rules`, data), updateRule: (id: number, data: Partial<AutomationRulePayload> & { expected_version: number }) => api.patch<{ id: number; rule_code: string }>(`${base}/rules/${id}`, data),
  activate: (id: number) => api.post<{ id: number; status_code: string }>(`${base}/rules/${id}/activate`, {}), pause: (id: number) => api.post<{ id: number; status_code: string }>(`${base}/rules/${id}/pause`, {}), resume: (id: number) => api.post<{ id: number; status_code: string }>(`${base}/rules/${id}/resume`, {}), disable: (id: number) => api.post<{ id: number; status_code: string }>(`${base}/rules/${id}/disable`, {}), duplicate: (id: number) => api.post<{ id: number; rule_code: string }>(`${base}/rules/${id}/duplicate`, {}), test: (id: number, input: Record<string, unknown> = {}) => api.post<Record<string, unknown>>(`${base}/rules/${id}/test`, input), run: (id: number, input: Record<string, unknown> = {}) => api.post<{ run: AutomationRun; message: string }>(`${base}/rules/${id}/run`, input),
  useTemplate: (workspace: AutomationWorkspace, code: string) => api.post<{ id: number; rule_code: string }>(`${base}/templates/${workspace}/${encodeURIComponent(code)}/use`, {}), runs: (filters: Record<string, string | number | undefined> = {}) => api.get<AutomationPage<AutomationRun>>(`${base}/runs${query(filters)}`), runDetail: (id: number) => api.get<AutomationRun>(`${base}/runs/${id}`), events: (filters: Record<string, string | number | undefined> = {}) => api.get<AutomationPage<AutomationEvent>>(`${base}/events${query(filters)}`),
};
