import { api } from '../../lib/api';
import type { MaintenanceSchedule, PrinterActivity, PrinterDetail, PrinterIssue, PrinterPayload, PrintHistory, Technician } from '../../types/craft-printers';
const BASE = '/craft/printers';
const query = (values: Record<string, string | number | boolean | undefined>) => { const params = new URLSearchParams(); Object.entries(values).forEach(([key, value]) => { if (value !== undefined && value !== '') params.set(key, String(value)); }); return params.toString() ? `?${params}` : ''; };
export const craftPrintersApi = {
  list: (filters: Record<string, string | boolean | undefined> = {}) => api.get<PrinterActivity[]>(`${BASE}${query(filters)}`),
  get: (id: number) => api.get<PrinterDetail>(`${BASE}/${id}`), create: (data: PrinterPayload) => api.post<PrinterDetail>(BASE, data), update: (id: number, data: Partial<PrinterPayload>) => api.patch<PrinterDetail>(`${BASE}/${id}`, data), archive: (id: number) => api.delete<{ id: number; archived: boolean }>(`${BASE}/${id}`), reactivate: (id: number) => api.post<PrinterDetail>(`${BASE}/${id}/reactivate`, {}), offline: (id: number) => api.post<PrinterDetail>(`${BASE}/${id}/offline`, {}), available: (id: number) => api.post<PrinterDetail>(`${BASE}/${id}/available`, {}),
  activity: () => api.get<PrinterActivity[]>(`${BASE}/activity`), history: (filters: Record<string, string | number | undefined> = {}) => api.get<PrintHistory[]>(`${BASE}/history${query(filters)}`), profiles: (printerId?: number) => api.get<PrinterDetail['print_profiles']>(`${BASE}/profiles${query({ printerId })}`), technicians: () => api.get<Technician[]>(`${BASE}/technicians`),
  maintenance: (printerId?: number) => api.get<{ schedules: MaintenanceSchedule[]; records: PrinterDetail['maintenance_records'] }>(`${BASE}/maintenance${query({ printerId })}`), createSchedule: (data: Record<string, unknown>) => api.post<MaintenanceSchedule>(`${BASE}/maintenance/schedules`, data), updateSchedule: (id: number, data: Record<string, unknown>) => api.patch<MaintenanceSchedule>(`${BASE}/maintenance/schedules/${id}`, data), deleteSchedule: (id: number) => api.delete<{ id: number; deleted: boolean }>(`${BASE}/maintenance/schedules/${id}`), startMaintenance: (id: number) => api.post<PrinterDetail>(`${BASE}/${id}/maintenance/start`, {}), completeMaintenance: (id: number, data: Record<string, unknown>) => api.post<PrinterDetail>(`${BASE}/${id}/maintenance/complete`, data),
  issues: (filters: Record<string, string | number | undefined> = {}) => api.get<PrinterIssue[]>(`${BASE}/issues${query(filters)}`), createIssue: (data: Record<string, unknown>) => api.post<PrinterIssue>(`${BASE}/issues`, data), updateIssue: (id: number, data: Record<string, unknown>) => api.patch<PrinterIssue>(`${BASE}/issues/${id}`, data),
};
