import { api } from '../../lib/api';
import type { PaginatedExternalParties, ProjectOption, StudioExternalAssignment, StudioExternalContact, StudioExternalDuplicateCandidate, StudioExternalExpense, StudioExternalMaintenanceRecord, StudioExternalPartyDetail, StudioVendorFilters, StudioVendorsOverview } from '../../types/studio-vendors';
const BASE = '/studio/vendors';
const query = (filters: object = {}) => { const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value !== undefined && value !== null && value !== '' && value !== false) params.set(key, String(value)); }); const text = params.toString(); return text ? `?${text}` : ''; };
const download = (blob: Blob) => { const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'studio-external-parties.csv'; document.body.appendChild(anchor); anchor.click(); anchor.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 0); };
export const studioVendorsApi = {
  summary: () => api.get<StudioVendorsOverview>(`${BASE}/summary`), list: (filters: StudioVendorFilters = {}) => api.get<PaginatedExternalParties>(`${BASE}${query(filters)}`), export: async (filters: StudioVendorFilters = {}) => download(await api.getBlob(`${BASE}/export${query(filters)}`)),
  duplicates: (data: Record<string, unknown>) => api.post<StudioExternalDuplicateCandidate[]>(`${BASE}/duplicates`, data), create: (data: Record<string, unknown>) => api.post<{ id: number; code: string; display_name: string; reused: boolean }>(BASE, data), detail: (id: number) => api.get<StudioExternalPartyDetail>(`${BASE}/${id}`), update: (id: number, data: Record<string, unknown>) => api.patch<{ id: number }>(`${BASE}/${id}`, data),
  activateRole: (id: number, role: string) => api.post(`${BASE}/${id}/roles/${role}/activate`, {}), deactivateRole: (id: number, role: string, reason: string | null, confirm = false) => api.post(`${BASE}/${id}/roles/${role}/deactivate`, { reason, confirm_active_assignments: confirm }),
  contacts: (id: number) => api.get<StudioExternalContact[]>(`${BASE}/${id}/contacts`), createContact: (id: number, data: Record<string, unknown>) => api.post(`${BASE}/${id}/contacts`, data), updateContact: (id: number, contactId: number, data: Record<string, unknown>) => api.patch(`${BASE}/${id}/contacts/${contactId}`, data), deleteContact: (id: number, contactId: number) => api.delete(`${BASE}/${id}/contacts/${contactId}`),
  assignments: (id: number) => api.get<StudioExternalAssignment[]>(`${BASE}/${id}/assignments`), addAssignment: (id: number, data: Record<string, unknown>) => api.post(`${BASE}/${id}/assignments`, data), updateAssignment: (id: number, assignmentId: number, data: Record<string, unknown>) => api.patch(`${BASE}/${id}/assignments/${assignmentId}`, data), endAssignment: (id: number, assignmentId: number, endDate?: string) => api.post(`${BASE}/${id}/assignments/${assignmentId}/end`, { end_date: endDate || null }),
  commercial: (id: number) => api.get<{ assignment_count: number; total_agreed_fee: number; expense_count: number; recorded_expenses: number }>(`${BASE}/${id}/commercial-summary`), expenses: (id: number) => api.get<StudioExternalExpense[]>(`${BASE}/${id}/expenses`), maintenance: (id: number) => api.get<StudioExternalMaintenanceRecord[]>(`${BASE}/${id}/maintenance`), activity: (id: number) => api.get<Array<{ id: number; action_code: string; description: string | null; created_at: string; actor: string | null }>>(`${BASE}/${id}/activity`), projects: () => api.get<ProjectOption[]>(`${BASE}/projects`),
};
