import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { AlertTriangle } from 'lucide-react';
import { Button } from '../../../components/ui/Button';
import { CustomerForm } from './components/CustomerForm';
import { craftCustomersApi } from '../../../services/api/craft-customers.api';
import type { CustomerFormData, DuplicateCustomerCandidate } from '../../../types/craft-customers';

export function CustomerCreatePage() {
  const navigate = useNavigate(); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState<CustomerFormData | null>(null); const [candidates, setCandidates] = useState<DuplicateCustomerCandidate[]>([]);
  const save = async (data: CustomerFormData, confirmed = false) => { setSaving(true); setError(null); try { if (!confirmed) { const found = await craftCustomersApi.getDuplicates(data); if (found.length) { setPending(data); setCandidates(found); setSaving(false); return; } } const result = await craftCustomersApi.createCustomer({ ...data, confirm_duplicate: confirmed }); navigate(`/app/craft/customers/${result.id}`); } catch (requestError) { const message = requestError instanceof Error ? requestError.message : 'Gagal membuat pelanggan.'; setError(message); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-4xl space-y-6 pb-12"><header><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[var(--nexus-yellow-deep)]">Bisnis Craft / Pelanggan</p><h1 className="mt-1 text-2xl font-bold text-[var(--nexus-charcoal)]">Tambah Pelanggan</h1><p className="mt-1 text-sm text-[var(--nexus-muted)]">Buat satu Party baru dengan peran Craft Customer.</p></header>{error && <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<CustomerForm submitting={saving} submitLabel="Simpan Pelanggan" onSubmit={data => void save(data)} onCancel={() => navigate('/app/craft/customers')} />
    {pending && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-lg rounded-xl bg-white shadow-2xl"><div className="flex gap-3 p-6"><span className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-amber-50 text-amber-700"><AlertTriangle className="h-5 w-5" /></span><div><h2 className="font-bold text-[var(--nexus-charcoal)]">Data serupa ditemukan</h2><p className="mt-1 text-sm text-[var(--nexus-muted)]">Tinjau Party berikut sebelum membuat data baru. Sistem tidak pernah menggabungkan Party secara otomatis.</p></div></div><div className="max-h-56 space-y-2 overflow-y-auto border-y border-[var(--nexus-border)] p-4">{candidates.map(candidate => <div key={candidate.id} className="rounded-lg border border-[var(--nexus-border)] p-3 text-sm"><p className="font-semibold text-[var(--nexus-charcoal)]">{candidate.display_name} <span className="ml-1 text-xs font-normal text-[var(--nexus-muted)]">{candidate.code}</span></p><p className="mt-1 text-xs text-[var(--nexus-muted)]">{candidate.email || candidate.phone || candidate.tax_id || 'Tanpa kontak utama'}</p><Link className="mt-2 inline-block text-xs font-semibold text-[var(--nexus-yellow-deep)]" to={`/app/craft/customers/${candidate.id}`}>Lihat Pelanggan</Link></div>)}</div><div className="flex justify-end gap-3 p-5"><Button variant="outline" onClick={() => setPending(null)}>Kembali</Button><Button onClick={() => pending && void save(pending, true)} disabled={saving}>{saving ? 'Menyimpan...' : 'Tetap Buat Baru'}</Button></div></div></div>}
  </div>;
}
