import React, { useCallback, useEffect, useState } from 'react';
import { Download, Plus, Search, SlidersHorizontal, Users, UserCheck, ClipboardList, ArrowLeft, ArrowRight } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../../../components/ui/Button';
import { craftCustomersApi } from '../../../services/api/craft-customers.api';
import type { CraftCustomer, CustomerFilters, CustomerSummaryCards } from '../../../types/craft-customers';
import { CustomerCard } from './components/CustomerUI';
import { useAuth } from '../../../context/AuthContext';

const initialSummary: CustomerSummaryCards = { total_customers: 0, active_customers: 0, active_partners: 0, active_orders: 0 };
const initialFilters: CustomerFilters = { page: 1, limit: 24, sortBy: 'name', sortOrder: 'asc' };

export function CustomersListPage({ partnersOnly = false }: { partnersOnly?: boolean }) {
  const navigate = useNavigate(); const { hasPermission } = useAuth(); const [filters, setFilters] = useState<CustomerFilters>(initialFilters); const [items, setItems] = useState<CraftCustomer[]>([]); const [summary, setSummary] = useState<CustomerSummaryCards>(initialSummary); const [meta, setMeta] = useState({ page: 1, limit: 24, total: 0, totalPages: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const request = partnersOnly ? craftCustomersApi.getPartners(filters) : craftCustomersApi.getCustomers(filters); const [list, totals] = await Promise.all([request, partnersOnly ? Promise.resolve(null) : craftCustomersApi.getSummary()]); setItems(list.items); setMeta(list.meta); if (totals) setSummary(totals); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Gagal memuat pelanggan Craft.'); } finally { setLoading(false); } }, [filters, partnersOnly]);
  useEffect(() => { void load(); }, [load]);
  const update = (changes: Partial<CustomerFilters>) => setFilters(current => ({ ...current, ...changes, page: changes.page || 1 }));
  const handleSearch = (value: string) => update({ search: value || undefined, page: 1 });
  const title = partnersOnly ? 'Mitra' : 'Pelanggan'; const description = partnersOnly ? 'Kelola mitra Craft, masa berlaku, dan harga khusus mereka.' : 'Kelola pelanggan Craft, informasi kontak, dan riwayat hubungan bisnis.';
  return <div className="mx-auto max-w-7xl space-y-6 pb-12"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[var(--nexus-yellow-deep)]">Bisnis Craft</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-[var(--nexus-charcoal)]">{title}</h1><p className="mt-1 text-sm text-[var(--nexus-muted)]">{description}</p></div>{hasPermission('craft.customers.write') && <div className="flex gap-2"><Button variant="outline" onClick={() => void craftCustomersApi.exportCustomers(filters)}><Download className="h-4 w-4" /> Ekspor CSV</Button><Button onClick={() => navigate('/app/craft/customers/new')}><Plus className="h-4 w-4" /> Tambah Pelanggan</Button></div>}</header>
    {!partnersOnly && <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={Users} label="Total Pelanggan" value={summary.total_customers} /><Summary icon={UserCheck} label="Pelanggan Aktif" value={summary.active_customers} /><Summary icon={Users} label="Mitra Aktif" value={summary.active_partners} gold /><Summary icon={ClipboardList} label="Pesanan Aktif" value={summary.active_orders} /></section>}
    <section className="rounded-xl border border-[var(--nexus-border)] bg-white p-4 shadow-sm"><div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_auto]"><label className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--nexus-muted)]" /><input value={filters.search || ''} onChange={event => handleSearch(event.target.value)} placeholder="Cari kode, nama, email, telepon, WhatsApp, atau NPWP..." className="w-full rounded-lg border border-[var(--nexus-border)] py-2.5 pl-10 pr-3 text-sm outline-none focus:border-amber-400 focus:ring-4 focus:ring-[var(--nexus-yellow)]/20" /></label><div className="flex items-center gap-2 text-xs font-semibold text-[var(--nexus-muted)]"><SlidersHorizontal className="h-4 w-4" /> {meta.total} hubungan bisnis</div></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><select value={filters.kind || ''} onChange={event => update({ kind: (event.target.value || undefined) as CustomerFilters['kind'] })} className="rounded-lg border border-[var(--nexus-border)] bg-white px-3 py-2 text-xs"><option value="">Semua jenis</option><option value="individual">Individu</option><option value="company">Perusahaan</option><option value="institution">Institusi</option></select>{!partnersOnly && <select value={filters.relationship || ''} onChange={event => update({ relationship: (event.target.value || undefined) as CustomerFilters['relationship'] })} className="rounded-lg border border-[var(--nexus-border)] bg-white px-3 py-2 text-xs"><option value="">Semua hubungan</option><option value="customer">Pelanggan</option><option value="partner">Mitra</option></select>}<select value={filters.status || ''} onChange={event => update({ status: (event.target.value || undefined) as CustomerFilters['status'] })} className="rounded-lg border border-[var(--nexus-border)] bg-white px-3 py-2 text-xs"><option value="">Semua status</option><option value="active">Aktif</option><option value="inactive">Tidak Aktif</option></select><label className="flex items-center gap-2 rounded-lg border border-[var(--nexus-border)] px-3 py-2 text-xs"><input type="checkbox" checked={Boolean(filters.hasActiveOrder)} onChange={event => update({ hasActiveOrder: event.target.checked || undefined })} /> Pesanan aktif</label><select value={filters.sortBy || 'name'} onChange={event => update({ sortBy: event.target.value as CustomerFilters['sortBy'], sortOrder: event.target.value === 'name' ? 'asc' : 'desc' })} className="rounded-lg border border-[var(--nexus-border)] bg-white px-3 py-2 text-xs"><option value="name">Nama A–Z</option><option value="last_order">Pesanan terbaru</option><option value="order_value">Nilai pesanan tertinggi</option><option value="order_count">Jumlah pesanan</option><option value="created_at">Baru ditambahkan</option></select></div></section>
    {error && <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    {loading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1, 2, 3].map(index => <div key={index} className="h-60 animate-pulse rounded-xl border border-[var(--nexus-border)] bg-white" />)}</div> : items.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(customer => <CustomerCard key={customer.id} customer={customer} onOpen={() => navigate(`/app/craft/customers/${customer.id}`)} />)}</div> : <div className="rounded-xl border border-dashed border-[var(--nexus-border)] bg-white px-6 py-16 text-center"><Users className="mx-auto h-10 w-10 text-[var(--nexus-yellow-deep)]" /><h2 className="mt-4 font-bold text-[var(--nexus-charcoal)]">{partnersOnly ? 'Belum Ada Mitra' : 'Belum Ada Pelanggan'}</h2><p className="mx-auto mt-2 max-w-md text-sm text-[var(--nexus-muted)]">{partnersOnly ? 'Pelanggan yang dipromosikan sebagai Mitra akan muncul di sini.' : 'Pelanggan Craft akan muncul di sini setelah ditambahkan atau dibuat dari Pesanan.'}</p>{hasPermission('craft.customers.write') && !partnersOnly && <Button className="mt-5" onClick={() => navigate('/app/craft/customers/new')}><Plus className="h-4 w-4" /> Tambah Pelanggan</Button>}</div>}
    {meta.totalPages > 1 && <div className="flex items-center justify-end gap-3"><Button variant="outline" size="sm" disabled={meta.page <= 1} onClick={() => update({ page: meta.page - 1 })}><ArrowLeft className="h-4 w-4" /> Sebelumnya</Button><span className="text-xs text-[var(--nexus-muted)]">Halaman {meta.page} dari {meta.totalPages}</span><Button variant="outline" size="sm" disabled={meta.page >= meta.totalPages} onClick={() => update({ page: meta.page + 1 })}>Berikutnya <ArrowRight className="h-4 w-4" /></Button></div>}
  </div>;
}

function Summary({ icon: Icon, label, value, gold }: { icon: React.ElementType; label: string; value: number; gold?: boolean }) { return <div className="rounded-xl border border-[var(--nexus-border)] bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><span className={`inline-flex h-9 w-9 items-center justify-center rounded-lg ${gold ? 'bg-amber-50 text-amber-700' : 'bg-[var(--nexus-cream-soft)] text-[var(--nexus-yellow-deep)]'}`}><Icon className="h-4 w-4" /></span><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-[var(--nexus-muted)]">{label}</p><p className="mt-0.5 text-xl font-bold text-[var(--nexus-charcoal)]">{value}</p></div></div></div>; }
