import React, { FormEvent, useEffect, useState } from 'react';
import { ArrowDownRight, ArrowLeftRight, ArrowUpRight, CheckCircle2, Landmark, Plus, RefreshCw, Wallet } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button } from '../../../components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '../../../components/ui/Card';
import { useAuth } from '../../../context/AuthContext';
import { formatCurrency } from '../../../lib/utils';
import { studioFinanceApi } from '../../../services/api/studio-finance.api';
import type { Budget, FinanceExpense, FinancePayable, FinanceReceivable, FinanceReferences, FinanceTransaction, Journal, Paginated, TreasuryAccount } from '../../../types/studio-finance';

const today = () => new Date().toISOString().slice(0, 10);
const date = (value?: string | null) => value ? new Date(value).toLocaleDateString('id-ID') : '—';
const amountClass = (type: string) => type === 'income' ? 'text-emerald-600' : type === 'expense' ? 'text-red-600' : 'text-[var(--nexus-charcoal)]';
const money = (value: number) => formatCurrency(Number(value || 0));
const statusClass = (status: string) => status === 'paid' || status === 'approved' || status === 'posted' ? 'bg-emerald-50 text-emerald-700' : status === 'draft' || status === 'partial' ? 'bg-amber-50 text-amber-700' : 'bg-red-50 text-red-700';

function PageHeader({ title, description, children }: { title: string; description: string; children?: React.ReactNode }) {
  return <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-bold text-[var(--nexus-charcoal)]">{title}</h1><p className="mt-1 text-sm text-[var(--nexus-muted)]">{description}</p></div>{children}</div>;
}
function Loading() { return <div className="p-8 text-sm text-[var(--nexus-muted)]">Memuat data keuangan Studio…</div>; }
function ErrorPanel({ message, retry }: { message: string; retry: () => void }) { return <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{message} <button className="ml-2 underline" onClick={retry}>Coba lagi</button></div>; }
function Status({ value }: { value: string }) { return <span className={`rounded-full px-2 py-1 text-xs font-semibold ${statusClass(value)}`}>{value}</span>; }
function useWritePermission() { const { hasPermission } = useAuth(); return hasPermission('studio.finance.write'); }
function InlineMessage({ message }: { message: string | null }) { return message ? <p className="mt-3 text-sm text-red-700">{message}</p> : null; }

export function FinanceOverviewPage() {
  const [data, setData] = useState<Awaited<ReturnType<typeof studioFinanceApi.overview>>>();
  const [error, setError] = useState('');
  const load = () => { setError(''); studioFinanceApi.overview().then(setData).catch((e: Error) => setError(e.message)); };
  useEffect(load, []);
  if (error) return <ErrorPanel message={error} retry={load} />;
  if (!data) return <Loading />;
  const cards = [
    ['Total Kas Studio', data.total_cash, Wallet, 'text-[var(--nexus-charcoal)]'], ['Cash In Bulan Ini', data.cash_in_month, ArrowUpRight, 'text-emerald-600'],
    ['Cash Out Bulan Ini', data.cash_out_month, ArrowDownRight, 'text-red-600'], ['Net Cash Flow', data.net_cash_flow, Landmark, data.net_cash_flow >= 0 ? 'text-emerald-600' : 'text-red-600'],
    ['Piutang Klien', data.receivables, Wallet, 'text-amber-700'], ['Pengeluaran Belum Dibayar', data.unpaid_expenses, ArrowDownRight, 'text-amber-700'],
    ['Profit Proyek Tercatat', data.recorded_project_profit, ArrowUpRight, data.recorded_project_profit >= 0 ? 'text-emerald-600' : 'text-red-600'],
  ] as const;
  return <div className="mx-auto max-w-7xl space-y-6 pb-12"><PageHeader title="Keuangan" description="Pantau kas, pembayaran, pengeluaran, piutang, dan profitabilitas Uni-Inside Studio."><Link to="treasury"><Button><Plus className="h-4 w-4" /> Kas & Bank</Button></Link></PageHeader><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon, color]) => <Card key={label}><CardContent className="p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-wider text-[var(--nexus-muted)]">{label}</p><Icon className={`h-4 w-4 ${color}`} /></div><p className={`mt-3 text-2xl font-bold ${color}`}>{money(value)}</p></CardContent></Card>)}</div><div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Perlu Perhatian</CardTitle></CardHeader><CardContent className="grid gap-3 text-sm sm:grid-cols-2"><p>Invoice terlambat <b>{data.attention.overdue_invoices}</b></p><p>Jatuh tempo 7 hari <b>{data.attention.schedules_due_soon}</b></p><p>Pengeluaran disetujui belum dibayar <b>{data.attention.approved_unpaid_expenses}</b></p><p>Fee eksternal tersisa <b>{money(data.attention.external_fee_remaining)}</b></p></CardContent></Card><Card><CardHeader><CardTitle>Aktivitas Finansial Terkini</CardTitle></CardHeader><CardContent className="space-y-3">{data.transactions.length ? data.transactions.map(row => <div key={row.id} className="flex items-start justify-between gap-4 border-b pb-3 text-sm last:border-0"><div><p className="font-medium">{row.description}</p><p className="text-xs text-[var(--nexus-muted)]">{date(row.transaction_date)} · {row.treasury_name || '—'}</p></div><b className={amountClass(row.transaction_type)}>{row.transaction_type === 'income' ? '+' : '-'}{money(row.amount)}</b></div>) : <p className="text-sm text-[var(--nexus-muted)]">Belum ada transaksi tercatat.</p>}</CardContent></Card></div></div>;
}

export function TransactionsPage() {
  const [data, setData] = useState<Paginated<FinanceTransaction>>(); const [error, setError] = useState('');
  const load = () => { setError(''); studioFinanceApi.transactions().then(setData).catch((e: Error) => setError(e.message)); }; useEffect(load, []);
  if (error) return <ErrorPanel message={error} retry={load} />; if (!data) return <Loading />;
  return <div className="mx-auto max-w-7xl space-y-6 pb-12"><PageHeader title="Transaksi" description="Riwayat transaksi posted Studio. Riwayat ini tidak dapat dihapus." ><Button variant="outline" onClick={load}><RefreshCw className="h-4 w-4" /> Muat ulang</Button></PageHeader><Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[800px] text-sm"><thead className="bg-[var(--nexus-cream-soft)] text-left text-xs uppercase text-[var(--nexus-muted)]"><tr><th className="p-4">Kode / Tanggal</th><th>Jenis</th><th>Kategori</th><th>Kas</th><th>Pihak</th><th className="text-right">Jumlah</th></tr></thead><tbody>{data.items.map(row => <tr className="border-t" key={row.id}><td className="p-4 font-medium">{row.transaction_code}<div className="mt-1 text-xs font-normal text-[var(--nexus-muted)]">{date(row.transaction_date)} · {row.description}</div></td><td><Status value={row.transaction_type} /></td><td>{row.category_name || 'Penyesuaian'}</td><td>{row.treasury_name || '—'}</td><td>{row.party_name || '—'}</td><td className={`text-right font-semibold ${amountClass(row.transaction_type)}`}>{row.transaction_type === 'income' ? '+' : row.transaction_type === 'expense' ? '-' : ''}{money(row.amount)}</td></tr>)}</tbody></table>{!data.items.length && <div className="p-8 text-sm text-[var(--nexus-muted)]">Belum ada transaksi Studio.</div>}</CardContent></Card></div>;
}

export function TreasuryPage() {
  const mayWrite = useWritePermission(); const [accounts, setAccounts] = useState<TreasuryAccount[]>(); const [refs, setRefs] = useState<FinanceReferences>(); const [error, setError] = useState(''); const [showCreate, setShowCreate] = useState(false); const [showTransfer, setShowTransfer] = useState(false);
  const load = () => { setError(''); Promise.all([studioFinanceApi.treasury(), studioFinanceApi.references()]).then(([a, r]) => { setAccounts(a); setRefs(r); }).catch((e: Error) => setError(e.message)); }; useEffect(load, []);
  if (error) return <ErrorPanel message={error} retry={load} />; if (!accounts || !refs) return <Loading />;
  return <div className="mx-auto max-w-7xl space-y-6 pb-12"><PageHeader title="Kas & Bank" description="Saldo kas Studio berasal dari posting keuangan yang tercatat.">{mayWrite && <div className="flex gap-2"><Button variant="outline" onClick={() => setShowTransfer(!showTransfer)}><ArrowLeftRight className="h-4 w-4" /> Transfer</Button><Button onClick={() => setShowCreate(!showCreate)}><Plus className="h-4 w-4" /> Akun Kas</Button></div>}</PageHeader>{showCreate && <TreasuryForm done={() => { setShowCreate(false); load(); }} />}{showTransfer && <TransferForm treasuries={accounts} done={() => { setShowTransfer(false); load(); }} />}<Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[800px] text-sm"><thead className="bg-[var(--nexus-cream-soft)] text-left text-xs uppercase text-[var(--nexus-muted)]"><tr><th className="p-4">Akun</th><th>Jenis</th><th>Provider</th><th>Saldo Awal</th><th>Saldo Saat Ini</th><th>Status</th></tr></thead><tbody>{accounts.map(account => <tr className="border-t" key={account.id}><td className="p-4 font-medium">{account.account_code} · {account.name}<div className="text-xs font-normal text-[var(--nexus-muted)]">{account.account_number_masked || '—'} · {account.currency_code}</div></td><td>{account.account_type}</td><td>{account.provider_name || '—'}</td><td>{money(account.opening_balance)}</td><td className="font-semibold">{money(account.current_balance)}</td><td><Status value={account.is_active ? 'active' : 'inactive'} /></td></tr>)}</tbody></table>{!accounts.length && <div className="p-8 text-sm text-[var(--nexus-muted)]">Belum ada akun kas Studio.</div>}</CardContent></Card></div>;
}

function TreasuryForm({ done }: { done: () => void }) { const [message,setMessage]=useState(''); const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await studioFinanceApi.createTreasury({name:String(f.get('name')),account_type:String(f.get('type')),provider_name:String(f.get('provider') || '') || null,account_number_masked:String(f.get('masked') || '') || null,opening_balance:Number(f.get('opening') || 0),currency_code:'IDR'});done();}catch(error){setMessage((error as Error).message);}};return <Card><CardHeader><CardTitle>Akun Kas / Bank Baru</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="grid gap-3 md:grid-cols-3"><input required name="name" placeholder="Nama akun" className="rounded border p-2"/><select name="type" className="rounded border p-2"><option value="bank">Bank</option><option value="cash">Kas</option><option value="ewallet">E-Wallet</option></select><input name="provider" placeholder="Provider" className="rounded border p-2"/><input name="masked" placeholder="Nomor tersamarkan" className="rounded border p-2"/><input name="opening" type="number" min="0" step="0.01" placeholder="Saldo awal" className="rounded border p-2"/><Button type="submit">Simpan akun</Button></form><p className="mt-2 text-xs text-[var(--nexus-muted)]">Saldo awal dicatat sebagai penyesuaian kas, bukan pendapatan.</p><InlineMessage message={message}/></CardContent></Card>; }
function TransferForm({ treasuries, done }: { treasuries: TreasuryAccount[]; done: () => void }) { const [message,setMessage]=useState(''); const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await studioFinanceApi.transfer({from_treasury_account_id:Number(f.get('from')),to_treasury_account_id:Number(f.get('to')),amount:Number(f.get('amount')),transfer_date:String(f.get('date')),description:String(f.get('description') || '') || null});done();}catch(error){setMessage((error as Error).message);}};return <Card><CardHeader><CardTitle>Transfer Antar Kas Studio</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="grid gap-3 md:grid-cols-4"><select required name="from" className="rounded border p-2"><option value="">Dari akun</option>{treasuries.filter(t=>t.is_active).map(t=><option key={t.id} value={t.id}>{t.name} ({money(t.current_balance)})</option>)}</select><select required name="to" className="rounded border p-2"><option value="">Ke akun</option>{treasuries.filter(t=>t.is_active).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input required name="amount" type="number" min="1" step="0.01" placeholder="Jumlah" className="rounded border p-2"/><input required name="date" defaultValue={today()} type="date" className="rounded border p-2"/><input name="description" placeholder="Keterangan" className="rounded border p-2 md:col-span-3"/><Button type="submit">Transfer</Button></form><p className="mt-2 text-xs text-[var(--nexus-muted)]">Transfer tidak dihitung sebagai pendapatan atau pengeluaran.</p><InlineMessage message={message}/></CardContent></Card>; }

export function IncomePage() { const mayWrite=useWritePermission();const [refs,setRefs]=useState<FinanceReferences>();const [message,setMessage]=useState('');useEffect(()=>{studioFinanceApi.references().then(setRefs).catch((e:Error)=>setMessage(e.message));},[]);if(!refs)return <Loading/>;const income=refs.categories.filter(c=>c.transaction_type==='income');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await studioFinanceApi.income({amount:Number(f.get('amount')),transaction_date:String(f.get('date')),treasury_account_id:Number(f.get('treasury')),category_code:String(f.get('category')),description:String(f.get('description')),reference_number:String(f.get('reference') || '') || null});e.currentTarget.reset();setMessage('Pendapatan berhasil diposting ke kas Studio.');}catch(error){setMessage((error as Error).message);}};return <div className="mx-auto max-w-4xl space-y-6 pb-12"><PageHeader title="Pendapatan" description="Catat kas masuk yang benar-benar diterima, bukan invoice yang baru diterbitkan."/>{mayWrite?<Card><CardHeader><CardTitle>Catat Pendapatan Manual</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="grid gap-3 md:grid-cols-2"><input required name="amount" type="number" min="1" step="0.01" placeholder="Jumlah diterima" className="rounded border p-2"/><input required name="date" defaultValue={today()} type="date" className="rounded border p-2"/><select required name="treasury" className="rounded border p-2"><option value="">Pilih kas / bank</option>{refs.treasuries.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select required name="category" className="rounded border p-2">{income.map(c=><option key={c.id} value={c.code}>{c.name}</option>)}</select><input required name="description" placeholder="Keterangan" className="rounded border p-2 md:col-span-2"/><input name="reference" placeholder="Nomor referensi (opsional)" className="rounded border p-2"/><Button type="submit">Posting kas masuk</Button></form><InlineMessage message={message}/></CardContent></Card>:<Card><CardContent className="p-6 text-sm text-[var(--nexus-muted)]">Anda memiliki akses baca saja.</CardContent></Card>}</div>; }

export function ExpensesPage() { const mayWrite=useWritePermission();const [data,setData]=useState<Paginated<FinanceExpense>>();const [refs,setRefs]=useState<FinanceReferences>();const [message,setMessage]=useState('');const [showForm,setShowForm]=useState(false);const [reversal,setReversal]=useState<FinanceExpense | null>(null);const load=()=>Promise.all([studioFinanceApi.expenses(),studioFinanceApi.references()]).then(([e,r])=>{setData(e);setRefs(r);}).catch((e:Error)=>setMessage(e.message));useEffect(load,[]);if(!data||!refs)return <Loading/>;const pay=async(id:number)=>{const treasury=refs.treasuries[0];if(!treasury){setMessage('Tambahkan akun kas aktif terlebih dahulu.');return;}try{await studioFinanceApi.payExpense(id,{treasury_account_id:treasury.id,payment_date:today()});load();}catch(error){setMessage((error as Error).message);}};const approve=async(id:number)=>{try{await studioFinanceApi.approveExpense(id);load();}catch(error){setMessage((error as Error).message);}};return <div className="mx-auto max-w-7xl space-y-6 pb-12"><PageHeader title="Pengeluaran" description="Draf dan persetujuan tidak mengubah kas; pembayaran aktual baru diposting saat dibayar.">{mayWrite&&<Button onClick={()=>setShowForm(!showForm)}><Plus className="h-4 w-4"/> Pengeluaran</Button>}</PageHeader>{showForm&&<ExpenseForm refs={refs} done={()=>{setShowForm(false);load();}}/>}{reversal&&<ExpenseReversalForm expense={reversal} done={()=>{setReversal(null);load();}}/>}<InlineMessage message={message}/><Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[900px] text-sm"><thead className="bg-[var(--nexus-cream-soft)] text-left text-xs uppercase text-[var(--nexus-muted)]"><tr><th className="p-4">Pengeluaran</th><th>Proyek</th><th>Kategori</th><th>Status</th><th className="text-right">Jumlah</th><th></th></tr></thead><tbody>{data.items.map(row=><tr className="border-t" key={row.id}><td className="p-4 font-medium">{row.expense_code}<div className="text-xs font-normal text-[var(--nexus-muted)]">{row.description} · {date(row.expense_date)}</div></td><td>{row.project_name || 'Umum'}</td><td>{row.category_name}</td><td><Status value={row.status_code}/></td><td className="text-right font-semibold">{money(row.total_amount)}</td><td className="p-2 text-right">{mayWrite&&row.status_code==='draft'&&<Button variant="outline" onClick={()=>approve(row.id)}>Setujui</Button>}{mayWrite&&row.status_code==='approved'&&<Button onClick={()=>pay(row.id)}>Bayar</Button>}{mayWrite&&row.status_code==='paid'&&<Button variant="outline" onClick={()=>setReversal(row)}>Balik</Button>}</td></tr>)}</tbody></table>{!data.items.length&&<div className="p-8 text-sm text-[var(--nexus-muted)]">Belum ada pengeluaran Studio.</div>}</CardContent></Card></div>; }

function ExpenseForm({ refs, done }: { refs: FinanceReferences; done: () => void }) { const [message,setMessage]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await studioFinanceApi.createExpense({expense_date:String(f.get('date')),description:String(f.get('description')),amount:Number(f.get('amount')),tax_amount:Number(f.get('tax')||0),category_code:String(f.get('category')),studio_project_id:Number(f.get('project')) || null,status_code:'draft'});done();}catch(error){setMessage((error as Error).message);}};return <Card><CardHeader><CardTitle>Pengeluaran Baru</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="grid gap-3 md:grid-cols-3"><input required name="description" placeholder="Deskripsi pengeluaran" className="rounded border p-2 md:col-span-2"/><input required name="date" defaultValue={today()} type="date" className="rounded border p-2"/><input required name="amount" type="number" min="1" step="0.01" placeholder="Nilai sebelum pajak" className="rounded border p-2"/><input name="tax" type="number" min="0" step="0.01" placeholder="Pajak" className="rounded border p-2"/><select name="category" className="rounded border p-2">{refs.categories.filter(c=>c.transaction_type==='expense').map(c=><option key={c.id} value={c.code}>{c.name}</option>)}</select><select name="project" className="rounded border p-2 md:col-span-2"><option value="">Tidak terkait proyek</option>{refs.projects.map(p=><option key={p.id} value={p.id}>{p.project_code} · {p.project_name}</option>)}</select><Button type="submit">Simpan sebagai draf</Button></form><InlineMessage message={message}/></CardContent></Card>; }
function ExpenseReversalForm({ expense, done }: { expense: FinanceExpense; done: () => void }) { const [message,setMessage]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await studioFinanceApi.reverseExpense(expense.id,{reversal_date:String(f.get('date')),reason:String(f.get('reason'))});done();}catch(error){setMessage((error as Error).message);}};return <Card><CardHeader><CardTitle>Pembalikan Pengeluaran {expense.expense_code}</CardTitle></CardHeader><CardContent><p className="mb-3 text-sm text-amber-800">Tindakan ini membuat transaksi pembalikan dan jurnal penyeimbang; riwayat pembayaran asli tidak dihapus.</p><form onSubmit={submit} className="grid gap-3 md:grid-cols-3"><input required name="date" defaultValue={today()} type="date" className="rounded border p-2"/><input required name="reason" minLength={3} placeholder="Alasan pembalikan" className="rounded border p-2 md:col-span-2"/><Button type="submit" variant="outline">Konfirmasi pembalikan</Button></form><InlineMessage message={message}/></CardContent></Card>; }

export function ReceivablesPage() { const mayWrite=useWritePermission();const [rows,setRows]=useState<FinanceReceivable[]>();const [refs,setRefs]=useState<FinanceReferences>();const [message,setMessage]=useState('');const [selected,setSelected]=useState<FinanceReceivable | null>(null);const load=()=>Promise.all([studioFinanceApi.receivables(),studioFinanceApi.references()]).then(([r,ref])=>{setRows(r);setRefs(ref);}).catch((e:Error)=>setMessage(e.message));useEffect(load,[]);if(!rows||!refs)return <Loading/>;return <div className="mx-auto max-w-7xl space-y-6 pb-12"><PageHeader title="Piutang Klien" description="Saldo invoice yang belum diterima; status terlambat dihitung saat dibaca, tanpa mengubah data."/>{selected&&mayWrite&&<InvoicePaymentForm invoice={selected} refs={refs} done={()=>{setSelected(null);load();}}/>}<InlineMessage message={message}/><Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[900px] text-sm"><thead className="bg-[var(--nexus-cream-soft)] text-left text-xs uppercase text-[var(--nexus-muted)]"><tr><th className="p-4">Invoice</th><th>Klien / Proyek</th><th>Jatuh tempo</th><th>Status</th><th className="text-right">Sisa</th><th></th></tr></thead><tbody>{rows.map(row=><tr className="border-t" key={row.id}><td className="p-4 font-medium">{row.invoice_number}<div className="text-xs font-normal text-[var(--nexus-muted)]">Ditagihkan {money(row.total_amount)} · terkumpul {money(row.paid_amount)}</div></td><td>{row.client_name}<div className="text-xs text-[var(--nexus-muted)]">{row.project_name || '—'}</div></td><td className={row.days_overdue>0?'text-red-700 font-semibold':''}>{date(row.due_date)}{row.days_overdue>0&&` (${row.days_overdue}h)`}</td><td><Status value={row.days_overdue>0?'overdue':row.status_code}/></td><td className="text-right font-semibold">{money(row.balance_due)}</td><td className="p-2 text-right">{mayWrite&&<Button onClick={()=>setSelected(row)}>Terima bayar</Button>}</td></tr>)}</tbody></table>{!rows.length&&<div className="p-8 text-sm text-[var(--nexus-muted)]">Tidak ada piutang terbuka.</div>}</CardContent></Card></div>; }

function InvoicePaymentForm({ invoice, refs, done }: { invoice: FinanceReceivable; refs: FinanceReferences; done: () => void }) { const [message,setMessage]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await studioFinanceApi.payInvoice(invoice.id,{amount:Number(f.get('amount')),payment_date:String(f.get('date')),payment_method_id:Number(f.get('method')),treasury_account_id:Number(f.get('treasury')),reference_number:String(f.get('reference')||'')||null});done();}catch(error){setMessage((error as Error).message);}};return <Card><CardHeader><CardTitle>Terima Pembayaran {invoice.invoice_number}</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="grid gap-3 md:grid-cols-4"><input required name="amount" type="number" min="1" max={invoice.balance_due} step="0.01" defaultValue={invoice.balance_due} className="rounded border p-2"/><input required name="date" type="date" defaultValue={today()} className="rounded border p-2"/><select required name="treasury" className="rounded border p-2"><option value="">Kas tujuan</option>{refs.treasuries.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select required name="method" className="rounded border p-2"><option value="">Metode</option>{refs.payment_methods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><input name="reference" placeholder="Referensi" className="rounded border p-2 md:col-span-3"/><Button type="submit">Konfirmasi penerimaan</Button></form><InlineMessage message={message}/></CardContent></Card>; }

export function PayablesPage() { const mayWrite=useWritePermission();const [rows,setRows]=useState<FinancePayable[]>();const [refs,setRefs]=useState<FinanceReferences>();const [message,setMessage]=useState('');const [selected,setSelected]=useState<FinancePayable|null>(null);const load=()=>Promise.all([studioFinanceApi.payables(),studioFinanceApi.references()]).then(([p,r])=>{setRows(p);setRefs(r);}).catch((e:Error)=>setMessage(e.message));useEffect(load,[]);if(!rows||!refs)return <Loading/>;return <div className="mx-auto max-w-7xl space-y-6 pb-12"><PageHeader title="Kewajiban Vendor / Freelancer" description="Fee disepakati adalah komitmen; biaya aktual hanya muncul setelah payout Finance."/>{selected&&mayWrite&&<PayoutForm payable={selected} refs={refs} done={()=>{setSelected(null);load();}}/>}<InlineMessage message={message}/><Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[800px] text-sm"><thead className="bg-[var(--nexus-cream-soft)] text-left text-xs uppercase text-[var(--nexus-muted)]"><tr><th className="p-4">Pihak</th><th>Proyek</th><th>Status</th><th className="text-right">Disepakati</th><th className="text-right">Sudah Dibayar</th><th className="text-right">Sisa</th><th></th></tr></thead><tbody>{rows.map(row=><tr className="border-t" key={row.id}><td className="p-4 font-medium">{row.party_name}<div className="text-xs font-normal text-[var(--nexus-muted)]">{row.assignment_role}</div></td><td>{row.project_code} · {row.project_name}</td><td><Status value={row.payment_status_code}/></td><td className="text-right">{money(row.agreed_fee)}</td><td className="text-right">{money(row.paid_amount)}</td><td className="text-right font-semibold">{money(row.remaining)}</td><td className="p-2 text-right">{mayWrite&&row.remaining>0&&<Button onClick={()=>setSelected(row)}>Bayar</Button>}</td></tr>)}</tbody></table></CardContent></Card></div>; }

function PayoutForm({ payable, refs, done }: { payable: FinancePayable; refs: FinanceReferences; done: () => void }) { const [message,setMessage]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await studioFinanceApi.payout(payable.id,{amount:Number(f.get('amount')),payment_date:String(f.get('date')),treasury_account_id:Number(f.get('treasury'))});done();}catch(error){setMessage((error as Error).message);}};return <Card><CardHeader><CardTitle>Payout {payable.party_name}</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="grid gap-3 md:grid-cols-3"><input required name="amount" type="number" min="1" max={payable.remaining} defaultValue={payable.remaining} step="0.01" className="rounded border p-2"/><input required name="date" type="date" defaultValue={today()} className="rounded border p-2"/><select required name="treasury" className="rounded border p-2"><option value="">Kas sumber</option>{refs.treasuries.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><Button type="submit">Posting payout</Button></form><InlineMessage message={message}/></CardContent></Card>; }

export function ProfitabilityPage() { const [rows,setRows]=useState<Awaited<ReturnType<typeof studioFinanceApi.profitability>>>();const [message,setMessage]=useState('');const load=()=>studioFinanceApi.profitability().then(setRows).catch((e:Error)=>setMessage(e.message));useEffect(load,[]);if(!rows)return <Loading/>;return <div className="mx-auto max-w-7xl space-y-6 pb-12"><PageHeader title="Profitabilitas Proyek" description="Cash margin menggunakan kas terkumpul dan biaya Finance aktual; fee disepakati tidak dihitung sebagai biaya aktual."/><InlineMessage message={message}/><Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-[var(--nexus-cream-soft)] text-left text-xs uppercase text-[var(--nexus-muted)]"><tr><th className="p-4">Proyek</th><th className="text-right">Kontrak</th><th className="text-right">Ditagihkan</th><th className="text-right">Terkumpul</th><th className="text-right">Biaya Aktual</th><th className="text-right">Cash Margin</th><th className="text-right">Margin Kontrak</th></tr></thead><tbody>{rows.map(row=><tr className="border-t" key={row.id}><td className="p-4 font-medium">{row.project_code}<div className="text-xs font-normal text-[var(--nexus-muted)]">{row.project_name}</div></td><td className="text-right">{money(row.contract_value)}</td><td className="text-right">{money(row.invoiced_amount)}</td><td className="text-right">{money(row.collected)}</td><td className="text-right">{money(row.actual_cost)}</td><td className={`text-right font-semibold ${row.cash_margin>=0?'text-emerald-600':'text-red-600'}`}>{money(row.cash_margin)}</td><td className="text-right">{money(row.recorded_contract_margin)}<div className="text-xs text-[var(--nexus-muted)]">{row.margin_percent.toFixed(1)}%</div></td></tr>)}</tbody></table></CardContent></Card></div>; }

export function CashFlowPage() { const [rows,setRows]=useState<Awaited<ReturnType<typeof studioFinanceApi.cashFlow>>>();const [message,setMessage]=useState('');const load=()=>studioFinanceApi.cashFlow().then(setRows).catch((e:Error)=>setMessage(e.message));useEffect(load,[]);if(!rows)return <Loading/>;const totals=rows.reduce((result,row)=>({in:result.in+row.cash_in,out:result.out+row.cash_out}),{in:0,out:0});return <div className="mx-auto max-w-5xl space-y-6 pb-12"><PageHeader title="Arus Kas" description="Hanya kas masuk dan keluar Studio yang diposting. Transfer antar akun tidak memengaruhi arus kas bersih."/><InlineMessage message={message}/><div className="grid gap-4 md:grid-cols-3"><Card><CardContent className="p-5"><p className="text-xs uppercase text-[var(--nexus-muted)]">Cash In</p><p className="mt-2 text-xl font-bold text-emerald-600">{money(totals.in)}</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-xs uppercase text-[var(--nexus-muted)]">Cash Out</p><p className="mt-2 text-xl font-bold text-red-600">{money(totals.out)}</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-xs uppercase text-[var(--nexus-muted)]">Net</p><p className="mt-2 text-xl font-bold">{money(totals.in-totals.out)}</p></CardContent></Card></div><Card><CardContent className="overflow-x-auto p-0"><table className="w-full text-sm"><thead className="bg-[var(--nexus-cream-soft)] text-left text-xs uppercase text-[var(--nexus-muted)]"><tr><th className="p-4">Tanggal</th><th className="text-right">Masuk</th><th className="text-right">Keluar</th><th className="text-right">Net</th></tr></thead><tbody>{rows.map(row=><tr className="border-t" key={row.day}><td className="p-4">{date(row.day)}</td><td className="text-right text-emerald-600">{money(row.cash_in)}</td><td className="text-right text-red-600">{money(row.cash_out)}</td><td className="text-right font-semibold">{money(row.net_cash_flow)}</td></tr>)}</tbody></table></CardContent></Card></div>; }

export function BudgetsPage() { const mayWrite=useWritePermission();const [rows,setRows]=useState<Budget[]>();const [message,setMessage]=useState('');const [showForm,setShowForm]=useState(false);const load=()=>studioFinanceApi.budgets().then(setRows).catch((e:Error)=>setMessage(e.message));useEffect(load,[]);if(!rows)return <Loading/>;const approve=async(id:number)=>{try{await studioFinanceApi.approveBudget(id);load();}catch(error){setMessage((error as Error).message);}};return <div className="mx-auto max-w-6xl space-y-6 pb-12"><PageHeader title="Anggaran" description="Realisasi dihitung dari pengeluaran Studio yang benar-benar paid dalam periode anggaran.">{mayWrite&&<Button onClick={()=>setShowForm(!showForm)}><Plus className="h-4 w-4"/> Anggaran</Button>}</PageHeader>{showForm&&<BudgetForm done={()=>{setShowForm(false);load();}}/>}<InlineMessage message={message}/><Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[700px] text-sm"><thead className="bg-[var(--nexus-cream-soft)] text-left text-xs uppercase text-[var(--nexus-muted)]"><tr><th className="p-4">Anggaran</th><th>Periode</th><th>Status</th><th className="text-right">Alokasi</th><th className="text-right">Realisasi</th><th className="text-right">Utilisasi</th><th></th></tr></thead><tbody>{rows.map(row=><tr className="border-t" key={row.id}><td className="p-4 font-medium">{row.budget_code}<div className="text-xs font-normal text-[var(--nexus-muted)]">{row.name}</div></td><td>{date(row.period_start)} – {date(row.period_end)}</td><td><Status value={row.status_code}/></td><td className="text-right">{money(row.allocated_amount)}</td><td className="text-right">{money(row.actual_amount)}</td><td className="text-right">{row.utilization_percent.toFixed(1)}%</td><td className="p-2 text-right">{mayWrite&&row.status_code==='draft'&&<Button variant="outline" onClick={()=>approve(row.id)}><CheckCircle2 className="h-4 w-4"/> Setujui</Button>}</td></tr>)}</tbody></table></CardContent></Card></div>; }

function BudgetForm({ done }: { done: () => void }) { const [message,setMessage]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await studioFinanceApi.createBudget({name:String(f.get('name')),period_start:String(f.get('start')),period_end:String(f.get('end')),items:[{name:String(f.get('item')),allocated_amount:Number(f.get('amount'))}]});done();}catch(error){setMessage((error as Error).message);}};return <Card><CardHeader><CardTitle>Anggaran Baru</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="grid gap-3 md:grid-cols-3"><input required name="name" placeholder="Nama anggaran" className="rounded border p-2"/><input required name="start" type="date" className="rounded border p-2"/><input required name="end" type="date" className="rounded border p-2"/><input required name="item" placeholder="Nama pos anggaran" className="rounded border p-2 md:col-span-2"/><input required name="amount" min="0" step="0.01" type="number" placeholder="Alokasi" className="rounded border p-2"/><Button type="submit">Simpan draf</Button></form><InlineMessage message={message}/></CardContent></Card>; }

export function AccountingPage() { const [data,setData]=useState<{journals:Journal[];periods:Awaited<ReturnType<typeof studioFinanceApi.accounting>>['periods']}>();const [message,setMessage]=useState('');const load=()=>studioFinanceApi.accounting().then(setData).catch((e:Error)=>setMessage(e.message));useEffect(load,[]);if(!data)return <Loading/>;return <div className="mx-auto max-w-7xl space-y-6 pb-12"><PageHeader title="Jurnal & Periode" description="Jurnal Finance bersifat baca-saja dan setiap posting memeriksa periode keuangan tertutup."/><InlineMessage message={message}/><div className="grid gap-6 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle>Jurnal Posted</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[650px] text-sm"><thead className="bg-[var(--nexus-cream-soft)] text-left text-xs uppercase text-[var(--nexus-muted)]"><tr><th className="p-4">Nomor</th><th>Tanggal</th><th>Deskripsi</th><th className="text-right">Debit</th><th className="text-right">Kredit</th></tr></thead><tbody>{data.journals.map(row=><tr className="border-t" key={row.id}><td className="p-4 font-medium">{row.journal_number}</td><td>{date(row.entry_date)}</td><td>{row.description}</td><td className="text-right">{money(row.debit_amount)}</td><td className="text-right">{money(row.credit_amount)} {row.is_balanced&&<span className="text-emerald-600">✓</span>}</td></tr>)}</tbody></table></CardContent></Card><Card><CardHeader><CardTitle>Periode Keuangan</CardTitle></CardHeader><CardContent className="space-y-3">{data.periods.map(period=><div className="border-b pb-3 text-sm last:border-0" key={period.id}><div className="flex justify-between gap-2"><b>{period.period_code}</b><Status value={period.status_code}/></div><p className="mt-1 text-xs text-[var(--nexus-muted)]">{date(period.start_date)} – {date(period.end_date)}</p></div>)}{!data.periods.length&&<p className="text-sm text-[var(--nexus-muted)]">Belum ada periode yang dikonfigurasi.</p>}</CardContent></Card></div></div>; }
