export type AutomationWorkspace = 'craft' | 'studio';
export type AutomationStatus = 'draft' | 'active' | 'paused' | 'disabled';
export type AutomationRunStatus = 'queued' | 'running' | 'success' | 'failed' | 'skipped';
export type AutomationTriggerType = 'event' | 'sensor' | 'schedule' | 'manual';
export type AutomationRisk = 'informational' | 'operational' | 'data_change';
export type AutomationOperator = 'eq' | 'neq' | 'in' | 'not_in' | 'gt' | 'gte' | 'lt' | 'lte' | 'contains' | 'not_contains' | 'is_null' | 'not_null' | 'before' | 'after' | 'within_hours' | 'changed_from' | 'changed_to';

export interface AutomationCapability { accessible: boolean; read: boolean; write: boolean; run: boolean; businessUnitId: number | null; label: string; }
export interface AutomationMeta { capabilities: Record<AutomationWorkspace, AutomationCapability>; timezone: string; workspaces: AutomationWorkspace[]; }
export interface AutomationConditionField { field: string; label: string; type: 'string' | 'number' | 'date' | 'boolean' | 'enum'; values?: string[]; }
export interface AutomationTrigger { code: string; label: string; module: string; description: string; triggerType: AutomationTriggerType; entityType: string; fields: AutomationConditionField[]; recommendedActions: string[]; }
export interface AutomationActionDefinition { type: string; label: string; module: string; description: string; requiredPermission: string; retrySafe: boolean; risk: AutomationRisk; supportedEvents?: string[]; available?: boolean; unavailableReason?: string; }
export interface AutomationCatalogScope { workspace: AutomationWorkspace; triggers: AutomationTrigger[]; actions: AutomationActionDefinition[]; operators: AutomationOperator[]; }
export interface AutomationCondition { field: string; operator: AutomationOperator; value?: unknown; }
export interface AutomationConditionGroup { logic: 'all' | 'any'; conditions: Array<AutomationCondition | AutomationConditionGroup>; }
export interface AutomationAction { type: string; config: Record<string, unknown>; continue_on_error?: boolean; }
export interface AutomationRulePayload { workspace?: AutomationWorkspace; name: string; description?: string | null; trigger_type: AutomationTriggerType; trigger_event: string; trigger_config_json?: { version: number; schedule?: { type: 'cron'; expression: string; timezone?: string } } | null; schedule_timezone?: string | null; condition_json?: AutomationConditionGroup | null; action_json: { version: number; actions: AutomationAction[] }; priority: number; cooldown_seconds: number; max_retries: number; status_code?: AutomationStatus; expected_version?: number; }
export interface AutomationRule extends Omit<AutomationRulePayload, 'workspace' | 'expected_version'> { id: number; workspace: AutomationWorkspace; rule_code: string; module_code: string; version_no: number; is_system: boolean; next_run_at: string | null; last_run_at: string | null; last_success_at: string | null; last_failure_at: string | null; created_by: number | null; updated_by: number | null; created_at: string; updated_at: string; total_runs?: number; success_runs?: number; failed_runs?: number; }
export interface AutomationRun { id: number; workspace: AutomationWorkspace; rule_id: number; rule_code: string; rule_name: string; module_code: string; run_key: string; rule_version: number; trigger_event: string | null; trigger_entity_type: string | null; trigger_entity_id: number | null; scheduled_for: string | null; initiated_by: number | null; attempt_no: number; next_attempt_at: string | null; correlation_id: string | null; chain_depth: number; status_code: AutomationRunStatus; started_at: string; finished_at: string | null; input_json: Record<string, unknown> | null; rule_snapshot_json: Record<string, unknown> | null; result_json: Record<string, unknown> | null; error_message: string | null; }
export interface AutomationEvent { id: number; workspace: AutomationWorkspace; event_name: string; module_code: string; entity_type: string | null; entity_id: number | null; entity_code: string | null; correlation_id: string | null; chain_depth: number; status_code: string; attempt_count: number; available_at: string; locked_at: string | null; processed_at: string | null; last_error: string | null; created_at: string; }
export interface AutomationTemplate { workspace: AutomationWorkspace; code: string; name: string; description: string; rule: AutomationRulePayload; actions: AutomationActionDefinition[]; }
export interface AutomationPage<T> { items: T[]; page: number; limit: number; total: number; total_pages: number; }
export interface AutomationOverview { workspace_summary: Partial<Record<AutomationWorkspace, { active_rules: number; paused_rules: number; rules_total: number }>>; metrics: Record<string, number>; queue_health: { level: 'healthy' | 'warning' | 'critical'; label: string; oldest_pending_event: string | null; recent_activity_at: string | null; note: string; }; recent_runs: AutomationRun[]; upcoming_schedules: Array<{ id: number; workspace: AutomationWorkspace; rule_code: string; name: string; next_run_at: string }>; timezone: string; }
