export type TransactionType = 'income' | 'expense' | 'transfer' | 'adjustment';
export type ExpenseStatus = 'draft' | 'approved' | 'paid' | 'void';

export interface FinanceTransaction { id: number; transaction_code: string; transaction_date: string; transaction_type: TransactionType; amount: number; currency_code: string; description: string; status_code: string; category_code: string | null; category_name: string | null; treasury_name: string | null; party_name: string | null; source_type: string | null; source_code: string | null; }
export interface TreasuryAccount { id: number; account_code: string; name: string; account_type: string; provider_name: string | null; account_number_masked: string | null; currency_code: string; opening_balance: number; current_balance: number; is_active: boolean; last_transaction_at: string | null; }
export interface FinanceCategory { id: number; code: string; name: string; transaction_type: 'income' | 'expense'; }
export interface FinanceReference { id: number; name: string; code?: string; account_code?: string; current_balance?: number; currency_code?: string; display_name?: string; project_code?: string; project_name?: string; contract_value?: number; }
export interface FinanceReferences { categories: FinanceCategory[]; payment_methods: Array<{ id: number; code: string; name: string; method_type: string }>; treasuries: FinanceReference[]; projects: FinanceReference[]; external_parties: FinanceReference[]; periods: FinancialPeriod[]; }
export interface FinanceOverview { total_cash: number; cash_in_month: number; cash_out_month: number; net_cash_flow: number; receivables: number; unpaid_expenses: number; recorded_project_profit: number; attention: { overdue_invoices: number; schedules_due_soon: number; approved_unpaid_expenses: number; external_fee_remaining: number; }; transactions: FinanceTransaction[]; }
export interface FinanceExpense { id: number; expense_code: string; expense_date: string; description: string; amount: number; tax_amount: number; total_amount: number; currency_code: string; status_code: ExpenseStatus; category_code: string; category_name: string; party_name: string | null; project_code: string | null; project_name: string | null; treasury_name: string | null; }
export interface FinanceReceivable { id: number; invoice_number: string; issue_date: string; due_date: string | null; status_code: string; total_amount: number; paid_amount: number; balance_due: number; currency_code: string; client_name: string; client_code: string; project_id: number | null; project_code: string | null; project_name: string | null; next_schedule_due_date: string | null; next_schedule_label: string | null; days_overdue: number; }
export interface FinancePayable { id: number; assignment_role: string; agreed_fee: number; paid_amount: number; remaining: number; payment_status_code: string; party_name: string; party_code: string; project_id: number; project_code: string; project_name: string; }
export interface ProjectProfitability { id: number; project_code: string; project_name: string; status_code: string; contract_value: number; actual_cost: number; collected: number; invoiced_amount: number; outstanding_amount: number; agreed_external_fees: number; cash_margin: number; recorded_contract_margin: number; margin_percent: number; }
export interface CashFlowPoint { day: string; cash_in: number; cash_out: number; net_cash_flow: number; }
export interface Budget { id: number; budget_code: string; name: string; period_start: string; period_end: string; status_code: string; total_amount: number; allocated_amount: number; actual_amount: number; utilization_percent: number; }
export interface FinancialPeriod { id: number; period_code: string; start_date: string; end_date: string; status_code: string; }
export interface Journal { id: number; journal_number: string; entry_date: string; description: string; source_type: string | null; source_id: number | null; status_code: string; debit_amount: number; credit_amount: number; is_balanced: boolean; }
export interface Paginated<T> { items: T[]; meta: { page: number; limit: number; total: number; totalPages: number; }; }

export interface TreasuryPayload { name: string; account_type: string; provider_name?: string | null; account_number_masked?: string | null; currency_code?: string; opening_balance?: number; }
export interface TransferPayload { from_treasury_account_id: number; to_treasury_account_id: number; amount: number; transfer_date: string; description?: string | null; }
export interface IncomePayload { amount: number; transaction_date: string; treasury_account_id: number; category_code?: string; description: string; party_id?: number | null; reference_number?: string | null; }
export interface ExpensePayload { expense_date: string; description: string; amount: number; tax_amount?: number; category_code?: string; party_id?: number | null; studio_project_id?: number | null; treasury_account_id?: number | null; status_code?: 'draft' | 'approved' | 'paid'; direct_payment_confirmed?: boolean; }
