export type StudioExternalRole = 'vendor' | 'freelancer' | 'studio_partner';
export type ExternalRelationshipStatus = 'active' | 'role_inactive' | 'party_inactive';
export interface StudioExternalParty { id: number; code: string; party_kind: 'individual' | 'company' | 'institution'; display_name: string; legal_name: string | null; email: string | null; phone: string | null; city: string | null; status_code: string; relationship_status: ExternalRelationshipStatus; managed_roles: StudioExternalRole[]; primary_contact_name: string | null; active_assignment_count: number; total_project_count: number; total_agreed_fee: number; recorded_expenses: number; }
export type StudioExternalPartySummary = StudioExternalParty;
export interface StudioExternalPartyRole { id: number; role_code: StudioExternalRole; is_active: boolean; valid_from: string | null; valid_until: string | null; created_at: string; }
export type StudioExternalPartyRelationship = StudioExternalPartyRole;
export interface StudioExternalContact { id: number; party_id: number; full_name: string; job_title: string | null; email: string | null; phone: string | null; whatsapp: string | null; is_primary: boolean; notes: string | null; }
export interface StudioExternalAssignment { id: number; project_id: number; project_code: string; project_name: string; project_status: string; project_type: string | null; assignment_role: 'vendor' | 'freelancer' | 'partner' | 'talent' | 'other'; scope_description: string | null; agreed_fee: number; payment_status_code: string; start_date: string | null; end_date: string | null; notes: string | null; is_active: boolean; }
export type StudioExternalProjectSummary = StudioExternalAssignment;
export interface StudioExternalExpense { id: number; expense_code: string; expense_date: string; description: string; amount: number; tax_amount: number; currency_code: string; status_code: string; project_code: string | null; project_name: string | null; financial_transaction_id: number | null; }
export interface StudioExternalCommercialSummary { assignment_count: number; total_agreed_fee: number; expense_count: number; recorded_expenses: number; }
export interface StudioExternalMaintenanceRecord { id: number; asset_id: number; asset_code: string; asset_name: string; maintenance_type: string; performed_at: string; cost: number; next_due_at: string | null; notes: string | null; }
export interface StudioExternalDuplicateCandidate { id: number; code: string; display_name: string; legal_name: string | null; email: string | null; phone: string | null; tax_id: string | null; party_kind: string; status_code: string; role_codes: string[]; is_studio_external: boolean; match_reason: string; }
export interface StudioVendorsOverview { total_parties: number; active_parties: number; vendors: number; freelancers: number; studio_partners: number; total_agreed_fee: number; recorded_expenses: number; }
export interface StudioExternalPartyDetail { party: StudioExternalParty & { website: string | null; tax_id: string | null; address_line1: string | null; address_line2: string | null; province: string | null; postal_code: string | null; country_code: string; notes: string | null; created_at: string; updated_at: string; }; roles: StudioExternalPartyRole[]; other_roles: Array<{ role_code: string; label: string; business_unit_id: number | null }>; primary_contact: StudioExternalContact | null; contact_count: number; assignments: StudioExternalAssignment[]; commercial: { assignment_count: number; total_agreed_fee: number; expense_count: number; recorded_expenses: number }; maintenance: StudioExternalMaintenanceRecord[]; }
export interface StudioVendorFilters { page?: number; limit?: number; search?: string; role?: StudioExternalRole; relationship_status?: ExternalRelationshipStatus; party_kind?: string; city?: string; has_active_assignment?: boolean; sort_by?: string; sort_order?: 'asc' | 'desc'; }
export interface PaginatedExternalParties { items: StudioExternalParty[]; meta: { page: number; limit: number; total: number; totalPages: number }; }
export interface ProjectOption { id: number; project_code: string; project_name: string; status_code: string; }
