import React, { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '../../../components/ui/Card';
import { automationsApi } from '../../../services/api/automations.api';
import type { AutomationEvent, AutomationRun, AutomationWorkspace } from '../../../types/automations';
import { AutomationHeader, EmptyState, ErrorState, LoadingState, StatusBadge, WorkspaceBadge, WorkspaceFilter, duration, errorText, inputClass, when } from './components';
import { useAutomationMeta } from './GlobalAutomations';

export function AutomationRunsPage() {
  const meta = useAutomationMeta(); const [workspace, setWorkspace] = useState<'all' | AutomationWorkspace>('all'); const [status, setStatus] = useState(''); const [items, setItems] = useState<AutomationRun[] | null>(null); const [error, setError] = useState('');
  const load = useCallback(() => { setError(''); automationsApi.runs({ workspace, status, limit: 50 }).then(page => setItems(page.items)).catch(cause => setError(errorText(cause))); }, [workspace, status]); useEffect(() => { load(); }, [load]);
  if (error) return <ErrorState message={error} retry={load} />; if (!items) return <LoadingState />;
  return <div className="space-y-6"><AutomationHeader title="Riwayat Eksekusi" description="Run dari Craft dan Studio yang dapat Anda akses, termasuk retry, korelasi, chain depth, dan snapshot aturan."><WorkspaceFilter value={workspace} onChange={setWorkspace} available={meta.workspaces} /></AutomationHeader><select aria-label="Filter status run" className={`${inputClass} max-w-xs`} value={status} onChange={event => setStatus(event.target.value)}><option value="">Semua status</option>{['queued', 'running', 'success', 'failed', 'skipped'].map(item => <option key={item}>{item}</option>)}</select>{!items.length ? <EmptyState title="Belum ada run" description="Riwayat akan muncul ketika worker memproses event, jadwal, sensor, atau run manual." /> : <Card><div className="overflow-x-auto"><table className="w-full min-w-[1080px] text-left text-sm"><thead className="bg-[var(--nexus-cream-soft)] text-xs uppercase text-[var(--nexus-muted)]"><tr><th className="p-4">Workspace</th><th>Run / aturan</th><th>Pemicu / entitas</th><th>Status</th><th>Waktu</th><th>Durasi</th><th>Attempt / Chain</th><th className="p-4">Detail</th></tr></thead><tbody>{items.map(run => <tr key={run.id} className="border-t border-[var(--nexus-border)]"><td className="p-4"><WorkspaceBadge workspace={run.workspace} /></td><td><p className="font-mono text-xs">#{run.id} · v{run.rule_version}</p><p>{run.rule_name || run.rule_code}</p></td><td><p>{run.trigger_event || '—'}</p><p className="text-xs text-[var(--nexus-muted)]">{run.trigger_entity_type || '—'} {run.trigger_entity_id || ''}</p></td><td><StatusBadge value={run.status_code} /></td><td><p>{when(run.started_at)}</p><p className="text-xs text-[var(--nexus-muted)]">jadwal {when(run.scheduled_for)}</p></td><td>{duration(run.started_at, run.finished_at)}</td><td>{run.attempt_no} / {run.chain_depth}</td><td className="p-4"><Link className="text-xs font-semibold text-[var(--nexus-yellow-deep)] hover:underline" to={`/app/automations/runs/${run.id}`}>Lihat</Link></td></tr>)}</tbody></table></div></Card>}</div>;
}

export function AutomationRunDetailPage() {
  const { id } = useParams(); const [run, setRun] = useState<AutomationRun | null>(null); const [error, setError] = useState(''); const load = useCallback(() => { if (id) automationsApi.runDetail(Number(id)).then(setRun).catch(cause => setError(errorText(cause))); }, [id]); useEffect(() => { load(); }, [load]); if (error) return <ErrorState message={error} retry={load} />; if (!run) return <LoadingState />;
  const result = run.result_json || {}; const actionResults = Array.isArray(result.actions) ? result.actions as Array<Record<string, unknown>> : [];
  return <div className="space-y-6"><AutomationHeader title={`Run #${run.id}`} description={`${run.rule_name || run.rule_code} · snapshot versi ${run.rule_version}`}><WorkspaceBadge workspace={run.workspace} /><StatusBadge value={run.status_code} /></AutomationHeader><section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Info label="Run key" value={run.run_key} mono /><Info label="Correlation ID" value={run.correlation_id || '—'} mono /><Info label="Attempt / Chain" value={`${run.attempt_no} / ${run.chain_depth}`} /><Info label="Jadwal / durasi" value={`${when(run.scheduled_for)} · ${duration(run.started_at, run.finished_at)}`} /></section><Card><CardHeader><CardTitle>Hasil aksi</CardTitle></CardHeader><CardContent>{actionResults.length ? <div className="space-y-3">{actionResults.map((action, index) => <div key={index} className="rounded-lg border border-[var(--nexus-border)] p-3"><div className="flex items-center justify-between gap-3"><b>{String(action.type || 'Aksi')}</b><StatusBadge value={String(action.status || 'success')} /></div>{action.reason && <p className="mt-2 text-sm text-[var(--nexus-muted)]">Alasan: {String(action.reason)}</p>}{action.error && <p className="mt-2 text-sm text-red-700">{String(action.error)}</p>}</div>)}</div> : <p className="text-sm text-[var(--nexus-muted)]">Tidak ada hasil aksi yang ditampilkan untuk run ini.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Evaluasi & snapshot</CardTitle></CardHeader><CardContent className="grid gap-4 lg:grid-cols-2"><Summary title="Kondisi" value={result.evaluations} /><Summary title="Snapshot aturan" value={run.rule_snapshot_json ? { trigger: run.rule_snapshot_json.trigger, reliability: run.rule_snapshot_json.reliability, actions: run.rule_snapshot_json.actions } : null} /></CardContent></Card>{run.error_message && <Card><CardHeader><CardTitle>Ringkasan error aman</CardTitle></CardHeader><CardContent><p className="text-sm text-red-700">{run.error_message}</p></CardContent></Card>}</div>;
}

export function AutomationEventsPage() {
  const meta = useAutomationMeta(); const [workspace, setWorkspace] = useState<'all' | AutomationWorkspace>('all'); const [status, setStatus] = useState(''); const [items, setItems] = useState<AutomationEvent[] | null>(null); const [error, setError] = useState(''); const load = useCallback(() => { setError(''); automationsApi.events({ workspace, status, limit: 50 }).then(page => setItems(page.items)).catch(cause => setError(errorText(cause))); }, [workspace, status]); useEffect(() => { load(); }, [load]); if (error) return <ErrorState message={error} retry={load} />; if (!items) return <LoadingState />;
  return <div className="space-y-6"><AutomationHeader title="Monitor Event Domain" description="Observabilitas event outbox yang diizinkan. Event tidak dapat diubah dari pusat otomasi."><WorkspaceFilter value={workspace} onChange={setWorkspace} available={meta.workspaces} /></AutomationHeader><select aria-label="Filter status event" className={`${inputClass} max-w-xs`} value={status} onChange={event => setStatus(event.target.value)}><option value="">Semua status</option>{['pending', 'processing', 'processed', 'failed'].map(item => <option key={item}>{item}</option>)}</select>{!items.length ? <EmptyState title="Belum ada event domain" /> : <Card><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-[var(--nexus-cream-soft)] text-xs uppercase text-[var(--nexus-muted)]"><tr><th className="p-4">Workspace</th><th>Event</th><th>Entitas</th><th>Status</th><th>Attempt</th><th>Waktu</th><th className="p-4">Error aman</th></tr></thead><tbody>{items.map(event => <tr key={event.id} className="border-t border-[var(--nexus-border)]"><td className="p-4"><WorkspaceBadge workspace={event.workspace} /></td><td><p className="font-medium">{event.event_name}</p><p className="text-xs text-[var(--nexus-muted)]">{event.module_code}</p></td><td>{event.entity_type || '—'} {event.entity_code || event.entity_id || ''}</td><td><StatusBadge value={event.status_code === 'processed' ? 'success' : event.status_code} /></td><td>{event.attempt_count}</td><td><p>Dibuat {when(event.created_at)}</p><p className="text-xs text-[var(--nexus-muted)]">Tersedia {when(event.available_at)} · Diproses {when(event.processed_at)}</p></td><td className="p-4 text-xs text-red-700">{event.last_error || '—'}</td></tr>)}</tbody></table></div></Card>}</div>;
}

function Info({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <Card><CardContent className="p-4"><p className="text-xs text-[var(--nexus-muted)]">{label}</p><p className={`mt-2 break-all text-sm ${mono ? 'font-mono' : 'font-semibold'}`}>{value}</p></CardContent></Card>; }
function Summary({ title, value }: { title: string; value: unknown }) {
  const entries = value && typeof value === 'object' ? Object.entries(value as Record<string, unknown>) : [];
  return <div><p className="font-medium">{title}</p>{entries.length ? <dl className="mt-2 divide-y rounded-lg border border-[var(--nexus-border)] text-sm">{entries.map(([key, item]) => <div key={key} className="flex items-start justify-between gap-4 p-2"><dt className="text-[var(--nexus-muted)]">{key}</dt><dd className="max-w-[65%] text-right">{Array.isArray(item) ? `${item.length} item` : item && typeof item === 'object' ? `${Object.keys(item as Record<string, unknown>).length} properti` : String(item ?? '—')}</dd></div>)}</dl> : <p className="mt-2 text-sm text-[var(--nexus-muted)]">Tidak ada data ringkas.</p>}</div>;
}
