import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Copy, LockKeyhole } from 'lucide-react';
import { Button } from '../../../components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '../../../components/ui/Card';
import { automationsApi } from '../../../services/api/automations.api';
import type { AutomationCatalogScope, AutomationTemplate, AutomationWorkspace } from '../../../types/automations';
import { AutomationHeader, EmptyState, ErrorState, LoadingState, RiskBadge, WorkspaceBadge, WorkspaceFilter, errorText } from './components';
import { useAutomationMeta } from './GlobalAutomations';

export function AutomationTemplatesPage() {
  const meta = useAutomationMeta(); const navigate = useNavigate(); const [workspace, setWorkspace] = useState<'all' | AutomationWorkspace>('all'); const [items, setItems] = useState<AutomationTemplate[] | null>(null); const [error, setError] = useState('');
  const load = useCallback(() => { setError(''); automationsApi.templates(workspace === 'all' ? undefined : workspace).then(setItems).catch(cause => setError(errorText(cause))); }, [workspace]); useEffect(() => { load(); }, [load]);
  const useTemplate = async (template: AutomationTemplate) => { try { const result = await automationsApi.useTemplate(template.workspace, template.code); navigate(`/app/automations/rules/${result.id}/edit`); } catch (cause) { setError(errorText(cause)); } };
  if (error) return <ErrorState message={error} retry={load} />; if (!items) return <LoadingState />;
  return <div className="space-y-6"><AutomationHeader title="Template Otomasi" description="Template adalah blueprint aman. Menggunakannya selalu membuat draf, tidak pernah langsung aktif."><WorkspaceFilter value={workspace} onChange={setWorkspace} available={meta.workspaces} /></AutomationHeader>{!items.length ? <EmptyState title="Tidak ada template untuk workspace ini" /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(template => { const writable = meta.capabilities[template.workspace].write; return <Card key={`${template.workspace}-${template.code}`}><CardContent className="flex h-full flex-col p-5"><div className="flex items-start justify-between gap-3"><h2 className="font-bold text-[var(--nexus-charcoal)]">{template.name}</h2><WorkspaceBadge workspace={template.workspace} /></div><p className="mt-2 text-sm text-[var(--nexus-muted)]">{template.description}</p><p className="mt-4 text-xs font-semibold text-[var(--nexus-yellow-deep)]">{template.rule.trigger_type} · {template.rule.trigger_event}</p><div className="mt-3 space-y-2">{template.actions.map(action => <div key={action.type} className="flex items-center justify-between gap-2 text-xs"><span>{action.label}</span><RiskBadge risk={action.risk} /></div>)}</div><p className="mt-3 text-xs text-[var(--nexus-muted)]">Memerlukan: {template.actions.map(action => action.requiredPermission).join(', ') || 'izin otomasi workspace'}</p><div className="mt-auto pt-5"><Button size="sm" disabled={!writable} onClick={() => void useTemplate(template)}>{writable ? <><Copy className="h-4 w-4" />Gunakan sebagai draf</> : <><LockKeyhole className="h-4 w-4" />Butuh izin tulis</>}</Button></div></CardContent></Card>; })}</div>}</div>;
}

export function AutomationCatalogPage() {
  const meta = useAutomationMeta(); const [workspace, setWorkspace] = useState<'all' | AutomationWorkspace>('all'); const [items, setItems] = useState<AutomationCatalogScope[] | null>(null); const [error, setError] = useState('');
  const load = useCallback(() => { setError(''); automationsApi.catalog(workspace === 'all' ? undefined : workspace).then(setItems).catch(cause => setError(errorText(cause))); }, [workspace]); useEffect(() => { load(); }, [load]);
  const grouped = useMemo(() => items?.flatMap(item => item.triggers.map(trigger => ({ ...trigger, workspace: item.workspace }))) || [], [items]);
  if (error) return <ErrorState message={error} retry={load} />; if (!items) return <LoadingState />;
  return <div className="space-y-6"><AutomationHeader title="Katalog Kemampuan" description="Daftar transparan pemicu, field kondisi, operator, dan aksi tertutup yang dapat digunakan oleh otomasi."><WorkspaceFilter value={workspace} onChange={setWorkspace} available={meta.workspaces} /></AutomationHeader><section className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>Pemicu & field kondisi</CardTitle></CardHeader><div className="divide-y">{grouped.map(trigger => <div key={`${trigger.workspace}-${trigger.code}`} className="p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold">{trigger.label}</p><p className="mt-1 text-xs text-[var(--nexus-muted)]">{trigger.code} · {trigger.module} · {trigger.entityType}</p></div><WorkspaceBadge workspace={trigger.workspace} /></div><p className="mt-2 text-sm text-[var(--nexus-muted)]">{trigger.description}</p><p className="mt-2 text-xs text-[var(--nexus-muted)]">Field: {trigger.fields.length ? trigger.fields.map(field => `${field.label} (${field.type})`).join(', ') : 'Tidak ada field kondisi terdaftar.'}</p></div>)}</div></Card><Card><CardHeader><CardTitle>Aksi yang diizinkan</CardTitle></CardHeader><div className="divide-y">{items.flatMap(scope => scope.actions.map(action => <div key={`${scope.workspace}-${action.type}`} className="p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold">{action.label}</p><p className="mt-1 text-xs text-[var(--nexus-muted)]">{action.type} · {action.module}</p></div><div className="flex items-center gap-2"><WorkspaceBadge workspace={scope.workspace} /><RiskBadge risk={action.risk} /></div></div><p className="mt-2 text-sm text-[var(--nexus-muted)]">{action.description}</p><p className="mt-2 text-xs text-[var(--nexus-muted)]">Izin: {action.requiredPermission} · {action.retrySafe ? 'retry aman' : 'tidak dijalankan ulang otomatis'}{action.available === false ? ` · Belum tersedia: ${action.unavailableReason}` : ''}</p></div>))}</div></Card></section><Card><CardHeader><CardTitle>Operator kondisi</CardTitle></CardHeader><CardContent><p className="text-sm text-[var(--nexus-muted)]">Operator hanya muncul untuk tipe field yang sesuai: angka (=, ≠, &gt;, ≥, &lt;, ≤), teks (memuat), enum (salah satu dari), tanggal (sebelum/sesudah/dalam jam), dan nullability.</p></CardContent></Card></div>;
}
