import React from 'react';
import { Link, NavLink } from 'react-router-dom';
import { Activity, AlertTriangle, CheckCircle2, CirclePause, Clock3, Copy, FileClock, LayoutList, Play, ShieldAlert, SlidersHorizontal, Workflow, Zap } from 'lucide-react';
import { Badge } from '../../../components/ui/Badge';
import { Button } from '../../../components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '../../../components/ui/Card';
import type { AutomationActionDefinition, AutomationCondition, AutomationConditionField, AutomationRule, AutomationRun, AutomationWorkspace } from '../../../types/automations';

export const inputClass = 'mt-1 w-full rounded-lg border border-[var(--nexus-border)] bg-white px-3 py-2 text-sm outline-none focus:border-[var(--nexus-yellow-deep)] focus:ring-2 focus:ring-[var(--nexus-yellow)]/20';
export const labelClass = 'block text-sm font-medium text-[var(--nexus-charcoal)]';

export function AutomationHeader({ title, description, children }: { title: string; description: string; children?: React.ReactNode }) {
  return <header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--nexus-yellow-deep)]">Pusat Otomasi</p><h1 className="mt-1 text-2xl font-bold text-[var(--nexus-charcoal)] sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-sm text-[var(--nexus-muted)]">{description}</p></div>{children && <div className="flex flex-wrap gap-2">{children}</div>}</header>;
}

const statusVariant: Record<string, React.ComponentProps<typeof Badge>['variant']> = { active: 'success', success: 'success', paused: 'warning', queued: 'info', running: 'info', failed: 'error', disabled: 'error', skipped: 'warning', draft: 'outline' };
const statusLabel: Record<string, string> = { active: 'Aktif', success: 'Berhasil', paused: 'Dijeda', queued: 'Dalam antrean', running: 'Berjalan', failed: 'Gagal', disabled: 'Dinonaktifkan', skipped: 'Dilewati', draft: 'Draf' };
export function StatusBadge({ value }: { value: string }) { return <Badge variant={statusVariant[value] || 'outline'}>{statusLabel[value] || value}</Badge>; }
export function WorkspaceBadge({ workspace }: { workspace: AutomationWorkspace }) { return <Badge variant={workspace === 'craft' ? 'warning' : 'info'}>{workspace === 'craft' ? 'Craft' : 'Studio'}</Badge>; }
export function RiskBadge({ risk }: { risk: AutomationActionDefinition['risk'] }) { const text = risk === 'data_change' ? 'Perubahan Data' : risk === 'operational' ? 'Operasional' : 'Informasional'; return <Badge variant={risk === 'data_change' ? 'warning' : risk === 'operational' ? 'info' : 'outline'}>{text}</Badge>; }
export const when = (value?: string | null) => value ? new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';
export const duration = (start?: string | null, end?: string | null) => { if (!start || !end) return '—'; const seconds = Math.max(0, Math.round((new Date(end).getTime() - new Date(start).getTime()) / 1000)); return seconds < 60 ? `${seconds} dtk` : `${Math.floor(seconds / 60)} mnt ${seconds % 60} dtk`; };
export const errorText = (error: unknown) => error instanceof Error ? error.message : 'Operasi otomasi tidak dapat diselesaikan.';

export function WorkspaceFilter({ value, onChange, available }: { value: 'all' | AutomationWorkspace; onChange: (value: 'all' | AutomationWorkspace) => void; available: AutomationWorkspace[] }) {
  return <div className="inline-flex rounded-lg border border-[var(--nexus-border)] bg-white p-1" aria-label="Filter workspace">{(['all', ...available] as Array<'all' | AutomationWorkspace>).map(item => <button key={item} type="button" onClick={() => onChange(item)} className={`rounded-md px-3 py-1.5 text-xs font-semibold ${value === item ? 'bg-[var(--nexus-yellow)] text-[var(--nexus-charcoal)]' : 'text-[var(--nexus-muted)] hover:bg-[var(--nexus-cream-soft)]'}`}>{item === 'all' ? 'Semua' : item === 'craft' ? 'Craft' : 'Studio'}</button>)}</div>;
}

export function AutomationNav() {
  const links = [{ to: '/app/automations', label: 'Ringkasan', Icon: Activity, end: true }, { to: '/app/automations/rules', label: 'Aturan', Icon: Workflow }, { to: '/app/automations/templates', label: 'Template', Icon: Copy }, { to: '/app/automations/runs', label: 'Riwayat', Icon: FileClock }, { to: '/app/automations/events', label: 'Event', Icon: Clock3 }, { to: '/app/automations/catalog', label: 'Katalog', Icon: LayoutList }];
  return <nav className="flex gap-1 overflow-x-auto rounded-xl border border-[var(--nexus-border)] bg-white p-1" aria-label="Navigasi Pusat Otomasi">{links.map(({ to, label, Icon, end }) => <NavLink key={to} end={end} to={to} className={({ isActive }) => `inline-flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium ${isActive ? 'bg-[var(--nexus-cream-soft)] text-[var(--nexus-yellow-deep)]' : 'text-[var(--nexus-muted)] hover:bg-gray-50'}`}><Icon className="h-4 w-4" />{label}</NavLink>)}</nav>;
}

export function MetricCard({ label, value, Icon, detail }: { label: string; value: React.ReactNode; Icon: React.ElementType; detail?: string }) { return <Card><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-2xl font-bold text-[var(--nexus-charcoal)]">{value}</p><p className="mt-1 text-xs font-medium text-[var(--nexus-muted)]">{label}</p>{detail && <p className="mt-2 text-xs text-[var(--nexus-muted)]">{detail}</p>}</div><Icon className="h-5 w-5 text-[var(--nexus-yellow-deep)]" /></div></CardContent></Card>; }

export function EmptyState({ title, description, action }: { title: string; description?: string; action?: React.ReactNode }) { return <Card><CardContent className="p-10 text-center"><Workflow className="mx-auto h-9 w-9 text-[var(--nexus-yellow-deep)]" /><h2 className="mt-3 font-semibold text-[var(--nexus-charcoal)]">{title}</h2>{description && <p className="mx-auto mt-2 max-w-md text-sm text-[var(--nexus-muted)]">{description}</p>}{action && <div className="mt-5">{action}</div>}</CardContent></Card>; }

export function LoadingState() { return <div className="flex min-h-48 items-center justify-center text-sm text-[var(--nexus-muted)]"><Activity className="mr-2 h-4 w-4 animate-pulse" />Memuat pusat otomasi…</div>; }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <EmptyState title="Data otomasi belum dapat dimuat" description={message} action={retry ? <Button variant="outline" onClick={retry}>Coba lagi</Button> : undefined} />; }

export const riskSummary = (rule: AutomationRule, definitions: AutomationActionDefinition[]) => rule.action_json.actions.map(action => definitions.find(definition => definition.type === action.type)?.risk).filter(Boolean).some(risk => risk === 'data_change') ? 'data_change' : rule.action_json.actions.map(action => definitions.find(definition => definition.type === action.type)?.risk).includes('operational') ? 'operational' : 'informational';
export const isOperational = (actions: AutomationActionDefinition[]) => actions.some(action => action.risk !== 'informational');
export const Icons = { Zap, AlertTriangle, CheckCircle2, CirclePause, Clock3, ShieldAlert, SlidersHorizontal, Play };

const operatorLabels: Record<string, string> = { eq: '=', neq: '≠', in: 'salah satu dari', not_in: 'bukan salah satu', gt: '>', gte: '≥', lt: '<', lte: '≤', contains: 'memuat', not_contains: 'tidak memuat', is_null: 'kosong', not_null: 'tidak kosong', before: 'sebelum', after: 'sesudah', within_hours: 'dalam jam', changed_from: 'berubah dari', changed_to: 'berubah menjadi' };
const operatorsFor = (field?: AutomationConditionField) => { if (!field) return []; if (field.type === 'number') return ['eq', 'neq', 'gt', 'gte', 'lt', 'lte']; if (field.type === 'date') return ['before', 'after', 'within_hours', 'is_null', 'not_null']; if (field.type === 'boolean') return ['eq', 'neq', 'is_null', 'not_null']; if (field.type === 'enum') return ['eq', 'neq', 'in', 'not_in', 'is_null', 'not_null']; return ['eq', 'neq', 'contains', 'not_contains', 'is_null', 'not_null', 'changed_from', 'changed_to']; };

export function ConditionBuilder({ fields, value, onChange }: { fields: AutomationConditionField[]; value: AutomationCondition[]; onChange: (value: AutomationCondition[]) => void }) {
  const add = () => { const field = fields[0]; if (field && value.length < 20) onChange([...value, { field: field.field, operator: 'eq', value: field.type === 'boolean' ? true : '' }]); };
  return <div className="space-y-3"><div className="flex items-center justify-between"><p className="text-sm text-[var(--nexus-muted)]">Semua kondisi harus terpenuhi. Field dan operator dibatasi oleh katalog aman.</p><Button type="button" size="sm" variant="outline" onClick={add} disabled={!fields.length || value.length >= 20}>Tambah kondisi</Button></div>{value.map((condition, index) => { const field = fields.find(item => item.field === condition.field); const noValue = ['is_null', 'not_null'].includes(condition.operator); return <div key={`${condition.field}-${index}`} className="grid gap-2 rounded-lg border border-[var(--nexus-border)] p-3 md:grid-cols-[1.4fr_1fr_1fr_auto]"><label className="sr-only">Field kondisi {index + 1}</label><select className={inputClass} value={condition.field} onChange={event => { const next = [...value]; const nextField = fields.find(item => item.field === event.target.value); next[index] = { field: event.target.value, operator: 'eq', value: nextField?.type === 'boolean' ? true : '' }; onChange(next); }}>{fields.map(item => <option key={item.field} value={item.field}>{item.label}</option>)}</select><label className="sr-only">Operator kondisi {index + 1}</label><select className={inputClass} value={condition.operator} onChange={event => { const next = [...value]; next[index] = { ...condition, operator: event.target.value as AutomationCondition['operator'] }; onChange(next); }}>{operatorsFor(field).map(operator => <option key={operator} value={operator}>{operatorLabels[operator]}</option>)}</select>{noValue ? <p className="mt-1 flex items-center text-sm text-[var(--nexus-muted)]">Tanpa nilai</p> : <ConditionValue field={field} condition={condition} onChange={next => { const values = [...value]; values[index] = next; onChange(values); }} /> }<Button type="button" variant="ghost" size="sm" aria-label={`Hapus kondisi ${index + 1}`} onClick={() => onChange(value.filter((_, itemIndex) => itemIndex !== index))}>Hapus</Button></div>; })}</div>;
}

function ConditionValue({ field, condition, onChange }: { field?: AutomationConditionField; condition: AutomationCondition; onChange: (value: AutomationCondition) => void }) {
  if (field?.type === 'enum') return <select aria-label="Nilai kondisi" className={inputClass} value={String(condition.value ?? '')} onChange={event => onChange({ ...condition, value: ['in', 'not_in'].includes(condition.operator) ? event.target.value.split(',').filter(Boolean) : event.target.value })}>{field.values?.map(item => <option key={item}>{item}</option>)}</select>;
  if (field?.type === 'boolean') return <select aria-label="Nilai kondisi" className={inputClass} value={String(Boolean(condition.value))} onChange={event => onChange({ ...condition, value: event.target.value === 'true' })}><option value="true">Benar</option><option value="false">Salah</option></select>;
  return <input aria-label="Nilai kondisi" type={field?.type === 'number' ? 'number' : field?.type === 'date' ? 'datetime-local' : 'text'} className={inputClass} value={String(condition.value ?? '')} onChange={event => onChange({ ...condition, value: field?.type === 'number' ? Number(event.target.value) : event.target.value })} />;
}

export function ActionSummary({ actions, definitions }: { actions: AutomationRule['action_json']['actions']; definitions: AutomationActionDefinition[] }) { return <div className="space-y-2">{actions.map((action, index) => { const definition = definitions.find(item => item.type === action.type); return <div key={`${action.type}-${index}`} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-[var(--nexus-border)] p-3"><div><p className="font-medium">{definition?.label || action.type}</p><p className="text-xs text-[var(--nexus-muted)]">{definition?.description || action.type}</p></div>{definition && <div className="flex items-center gap-2"><RiskBadge risk={definition.risk} /><Badge variant="outline">{definition.retrySafe ? 'Retry aman' : 'Tanpa retry'}</Badge></div>}</div>; })}</div>; }

export function MiniRunTable({ runs }: { runs: AutomationRun[] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-[var(--nexus-cream-soft)] text-xs uppercase text-[var(--nexus-muted)]"><tr><th className="p-3">Workspace</th><th>Aturan</th><th>Status</th><th>Mulai</th><th className="p-3">Detail</th></tr></thead><tbody>{runs.map(run => <tr key={run.id} className="border-t border-[var(--nexus-border)]"><td className="p-3"><WorkspaceBadge workspace={run.workspace} /></td><td>{run.rule_name || run.rule_code}</td><td><StatusBadge value={run.status_code} /></td><td>{when(run.started_at)}</td><td className="p-3"><Link className="text-xs font-semibold text-[var(--nexus-yellow-deep)] hover:underline" to={`/app/automations/runs/${run.id}`}>Lihat</Link></td></tr>)}</tbody></table></div>; }

export { Card, CardContent, CardHeader, CardTitle };
