$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.IO.Compression.FileSystem
$workbook = Join-Path (Get-Location) 'Pengujian UNI-NEXUS.xlsx'
$tempWorkbook = Join-Path (Get-Location) 'Pengujian UNI-NEXUS.xlsx.qa-tmp'
$mainNs = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'
$xmlNs = 'http://www.w3.org/XML/1998/namespace'
$targetRows = 82..91
$expectedStatus = @{}
$notes = @{}
$notes[82] = 'Daftar Pemasok hanya menampilkan QA Supplier Primary SUP-000020; pemasok sekunder/reuse aktif yang menjadi target tidak tersedia. Form PO baru hanya menyediakan QA Supplier Primary. Karena target sekunder dan data PO/tagihan pembanding tidak tersedia, alur batal/konfirmasi nonaktif, reaktivasi, pemeriksaan Party role lain, serta penolakan karena workflow terbuka tidak dapat dijalankan literal tanpa memakai pemasok yang salah. Expected Result tidak terpenuhi. Akun ACCOUNT #1 — Insinyur 3D, workspace Uni-Inside Craft. Bukti: test-evidence/session-82-91/UNX-S06-006/01-no-secondary-active-supplier-po-form.png.'
$notes[83] = 'Form Permintaan Pembelian dapat dibuka, tetapi tidak ada material QA atau jalur Low Stock dengan material. Dropdown hanya berisi Item non-material dan satuan yang tersedia bukan Gram/G; penyimpanan kosong hanya mempertahankan form tanpa membuat PR. Quantity 200 G, estimated price 150, multi-item, total 130.000, dan validasi material tidak dapat diuji karena prasyarat material 800 G/reorder 200 G tidak tersedia. Expected Result tidak terpenuhi. Akun ACCOUNT #1 — Insinyur 3D, workspace Uni-Inside Craft. Bukti: test-evidence/session-82-91/UNX-S06-007/01-no-material-low-stock-or-prerequisite.png.'
$notes[84] = 'Daftar Permintaan Pembelian menampilkan Belum Ada Permintaan Pembelian. PR utama Draft dan PR sekunder untuk skenario penolakan tidak tersedia, sehingga transisi Draft ke Submitted ke Approved/Rejected, dialog batal, alasan penolakan, audit, tombol Buat PO, dan kontrol lifecycle Draft tidak dapat diverifikasi lengkap. Expected Result tidak terpenuhi. Akun ACCOUNT #1 — Insinyur 3D, workspace Uni-Inside Craft. Bukti: test-evidence/session-82-91/UNX-S06-008/01-no-prerequisite-pr-list.png.'
$notes[85] = 'Halaman Pesanan Pembelian menampilkan Belum Ada Pesanan Pembelian. PR Approved dengan sisa item material/non-material dan fondasi supplier/material tidak tersedia, sehingga pembuatan PO parsial, batas remaining quantity, mapping item, subtotal 65.000, total 80.000, dan pembaruan PR tidak dapat dijalankan. Expected Result tidak terpenuhi. Akun ACCOUNT #1 — Insinyur 3D, workspace Uni-Inside Craft. Bukti: test-evidence/session-82-91/UNX-S06-009/01-no-approved-pr-or-po.png.'
$notes[86] = 'Tidak ada PR dengan sisa 100 G dan 1 PCS. Form PO langsung hanya menampilkan QA Supplier Primary dan pilihan item Non-material tanpa material aktif; karena itu PO kedua, status PR ORDERED, perlindungan over-order, serta PO langsung final tidak dapat diselesaikan sesuai langkah. Expected Result tidak terpenuhi. Akun ACCOUNT #1 — Insinyur 3D, workspace Uni-Inside Craft. Bukti: test-evidence/session-82-91/UNX-S06-010/01-no-pr-remaining-and-direct-po-form.png.'
$notes[87] = 'Tidak ada PO Draft yang dapat dibuka. Percobaan menyimpan form PO kosong mempertahankan form dan fokus pada pemasok wajib tanpa membuat PO. Karena tidak ada PO sumber, PDF, Send, Confirm, Cancel, audit transisi, kontrol receipt, dan verifikasi Document Center tidak dapat dilakukan. Expected Result tidak terpenuhi. Akun ACCOUNT #1 — Insinyur 3D, workspace Uni-Inside Craft. Bukti: test-evidence/session-82-91/UNX-S06-011/01-po-lifecycle-no-orders.png.'
$notes[88] = 'Form Terima Barang terbuka, tetapi dropdown PO hanya berisi Pilih PO dapat diterima dan tombol Simpan Penerimaan disabled. Tidak ada PO Sent/Confirmed, sehingga accepted/rejected quantity, alasan penolakan, batch, spool, stock-in, movement, dan status Partial tidak dapat diuji. Expected Result tidak terpenuhi. Akun ACCOUNT #1 — Insinyur 3D, workspace Uni-Inside Craft. Bukti: test-evidence/session-82-91/UNX-S06-012/01-no-receivable-po.png.'
$notes[89] = 'Daftar Penerimaan Barang menampilkan Belum Ada Penerimaan Barang. PO Partial/Confirmed, saldo stok 860 G, receipt pertama, dan remaining 40 G tidak tersedia. Karena itu penolakan over-receipt, penerimaan lanjutan, rollback, penyelesaian PO, pembatasan PO Received, dan rekonsiliasi 1.000 G tidak dapat dijalankan. Expected Result tidak terpenuhi. Akun ACCOUNT #1 — Insinyur 3D, workspace Uni-Inside Craft. Bukti: test-evidence/session-82-91/UNX-S06-013/01-no-partial-po-or-receipts.png.'
$notes[90] = 'Halaman Tagihan Pemasok menampilkan Belum Ada Tagihan Pemasok. Modal menyediakan pemasok QA Supplier Primary, nomor, tanggal, jatuh tempo, dan total; submit kosong mempertahankan form tanpa invoice. Invoice QA-INV-0601/open invoice, duplicate/void, AP, blokir deaktivasi supplier, dan verifikasi PO/notes/dokumen tidak dapat diselesaikan karena data sumber tidak tersedia. Expected Result tidak terpenuhi. Akun ACCOUNT #1 — Insinyur 3D, workspace Uni-Inside Craft. Bukti: test-evidence/session-82-91/UNX-S06-014/01-invoice-empty-and-fields.png.'
$notes[91] = 'Ringkasan Pengadaan menampilkan seluruh KPI 0/Rp0, material stok menipis 0, dan tidak ada exception. URL daftar requests rejected serta orders received menampilkan empty state. Riwayat hanya memuat event pembuatan/pembaruan supplier dan dua kontak; detail supplier menunjukkan Total PO 0, PO terbuka 0, PO diterima 0, nilai Rp0, tanpa material/PO terkait. Dataset PR/PO/receipt/invoice dan rekonsiliasi sesi tidak tersedia, sehingga Expected Result tidak terpenuhi. Akun ACCOUNT #1 — Insinyur 3D, workspace Uni-Inside Craft. Bukti: test-evidence/session-82-91/UNX-S06-015/01-procurement-summary-empty.png, 02-orders-query-received-empty.png, 03-procurement-history-limited-controls.png, dan 04-supplier-performance-zero-and-history.png.'
foreach($row in $targetRows){$expectedStatus[$row]='Bug/Failed'}
function Read-ZipEntryText($archive,$name){$entry=$archive.GetEntry($name);if($null -eq $entry){throw "ZIP entry missing: $name"};$stream=$entry.Open();try{$reader=New-Object System.IO.StreamReader($stream,(New-Object System.Text.UTF8Encoding($false)));try{return $reader.ReadToEnd()}finally{$reader.Dispose()}}finally{$stream.Dispose()}}
function Get-XmlBytes($doc){$settings=New-Object System.Xml.XmlWriterSettings;$settings.Encoding=New-Object System.Text.UTF8Encoding($false);$settings.OmitXmlDeclaration=$false;$settings.Indent=$false;$memory=New-Object System.IO.MemoryStream;try{$writer=[System.Xml.XmlWriter]::Create($memory,$settings);try{$doc.Save($writer);$writer.Flush()}finally{$writer.Dispose()};return $memory.ToArray()}finally{$memory.Dispose()}}
function Get-Docs($archive){$sst=New-Object System.Xml.XmlDocument;$sst.PreserveWhitespace=$true;$sst.LoadXml((Read-ZipEntryText $archive 'xl/sharedStrings.xml'));$sheet=New-Object System.Xml.XmlDocument;$sheet.PreserveWhitespace=$true;$sheet.LoadXml((Read-ZipEntryText $archive 'xl/worksheets/sheet1.xml'));$manager=New-Object System.Xml.XmlNamespaceManager($sheet.NameTable);$manager.AddNamespace('x',$mainNs);return @{Shared=$sst;Sheet=$sheet;Ns=$manager}}
function Get-CellValue($cell,$docs){if($null -eq $cell){return $null};$v=$cell.SelectSingleNode('./x:v',$docs.Ns);$type=$cell.GetAttribute('t');if($type -eq 's' -and $null -ne $v){$items=$docs.Shared.SelectNodes('/x:sst/x:si',$docs.Ns);return $items[[int]$v.InnerText.Trim()].InnerText};if($type -eq 'inlineStr'){return $cell.InnerText};if($null -ne $v){return $v.InnerText};return ''}
function Get-LogicalSheet($docs){$map=@{};foreach($cell in $docs.Sheet.SelectNodes('//x:sheetData/x:row/x:c',$docs.Ns)){$map[$cell.GetAttribute('r')]=Get-CellValue $cell $docs};return $map}
function Get-SharedIndex($docs,$value){$items=$docs.Shared.SelectNodes('/x:sst/x:si',$docs.Ns);for($i=0;$i -lt $items.Count;$i++){if($items[$i].InnerText -eq $value){return $i}};$si=$docs.Shared.CreateElement('si',$mainNs);$t=$docs.Shared.CreateElement('t',$mainNs);[void]$t.SetAttribute('space',$xmlNs,'preserve');[void]($t.InnerText=$value);[void]$si.AppendChild($t);[void]$docs.Shared.DocumentElement.AppendChild($si);$count=$items.Count+1;[void]$docs.Shared.DocumentElement.SetAttribute('uniqueCount',[string]$count);[void]$docs.Shared.DocumentElement.SetAttribute('count',[string]$count);return [int]$items.Count}
function Set-SharedCell($docs,$address,$value){$cell=$docs.Sheet.SelectSingleNode("//x:sheetData/x:row/x:c[@r='$address']",$docs.Ns);if($null -eq $cell){throw "Cell missing: $address"};$index=Get-SharedIndex $docs $value;[void]$cell.SetAttribute('t','s');$v=$cell.SelectSingleNode('./x:v',$docs.Ns);if($null -eq $v){$v=$docs.Sheet.CreateElement('v',$mainNs);[void]$cell.AppendChild($v)};$v.InnerText=[string]$index}
if(-not(Test-Path -LiteralPath $workbook)){throw 'Workbook missing.'};$lockStream=[System.IO.File]::Open($workbook,[System.IO.FileMode]::Open,[System.IO.FileAccess]::Read,[System.IO.FileShare]::Read);$lockStream.Dispose();if(Test-Path -LiteralPath $tempWorkbook){Remove-Item -LiteralPath $tempWorkbook -Force};$sourceArchive=[System.IO.Compression.ZipFile]::OpenRead($workbook);try{$beforeDocs=Get-Docs $sourceArchive;$beforeLogical=Get-LogicalSheet $beforeDocs;foreach($row in $targetRows){if($beforeLogical["F$row"] -ne '' -or $beforeLogical["H$row"] -ne ''){throw "Target row already has a result: $row"}};Copy-Item -LiteralPath $workbook -Destination $tempWorkbook}finally{$sourceArchive.Dispose()}
$updateArchive=[System.IO.Compression.ZipFile]::Open($tempWorkbook,[System.IO.Compression.ZipArchiveMode]::Update);try{$docs=Get-Docs $updateArchive;foreach($row in $targetRows){Set-SharedCell $docs "F$row" $expectedStatus[$row];Set-SharedCell $docs "H$row" $notes[$row]};$sharedBytes=Get-XmlBytes $docs.Shared;$sheetBytes=Get-XmlBytes $docs.Sheet;foreach($name in @('xl/sharedStrings.xml','xl/worksheets/sheet1.xml')){$old=$updateArchive.GetEntry($name);if($null -eq $old){throw "ZIP entry missing during write: $name"};$old.Delete()};$newShared=$updateArchive.CreateEntry('xl/sharedStrings.xml');$stream=$newShared.Open();try{$stream.Write($sharedBytes,0,$sharedBytes.Length)}finally{$stream.Dispose()};$newSheet=$updateArchive.CreateEntry('xl/worksheets/sheet1.xml');$stream=$newSheet.Open();try{$stream.Write($sheetBytes,0,$sheetBytes.Length)}finally{$stream.Dispose()}}finally{$updateArchive.Dispose()}
$checkArchive=[System.IO.Compression.ZipFile]::OpenRead($tempWorkbook);try{$afterDocs=Get-Docs $checkArchive;$afterLogical=Get-LogicalSheet $afterDocs;foreach($row in $targetRows){if($afterLogical["F$row"] -ne $expectedStatus[$row]){throw "Status validation failed: F$row"};if($afterLogical["H$row"] -ne $notes[$row]){throw "Note validation failed: H$row"}};foreach($address in $beforeLogical.Keys){if($address -notmatch '^(F|H)(82|83|84|85|86|87|88|89|90|91)$'){if($afterLogical[$address] -ne $beforeLogical[$address]){throw "Unexpected logical cell change: $address"}}}}finally{$checkArchive.Dispose()}
$replacementBackup="$workbook.qa-replace-backup";if(Test-Path -LiteralPath $replacementBackup){Remove-Item -LiteralPath $replacementBackup -Force};[System.IO.File]::Replace($tempWorkbook,$workbook,$replacementBackup,$true);if(Test-Path -LiteralPath $replacementBackup){Remove-Item -LiteralPath $replacementBackup -Force};Write-Output 'Workbook update and pre-replacement validation succeeded.'
