import React, { useEffect, useState } from 'react';
import { CalendarDays, CreditCard, Receipt, X } from 'lucide-react';
import { Button } from '../../../../components/ui/Button';
import { craftOrdersApi } from '../../../../services/api/craft-orders.api';
import type { PaymentMethodOption } from '../../../../types/craft-orders';

interface Props { orderId: number; isOpen: boolean; onClose: () => void; onSuccess: () => void; }
export function PaymentModal({ orderId, isOpen, onClose, onSuccess }: Props) {
  const [amount, setAmount] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 16)); const [methodId, setMethodId] = useState(''); const [methods, setMethods] = useState<PaymentMethodOption[]>([]); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { if (isOpen) void craftOrdersApi.getPaymentMethods().then(setMethods).catch(requestError => setError(requestError instanceof Error ? requestError.message : 'Gagal memuat metode pembayaran.')); }, [isOpen]);
  if (!isOpen) return null;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(null); try { await craftOrdersApi.recordPayment(orderId, { amount: Number(amount), payment_date: date, payment_method_id: Number(methodId) }); onSuccess(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Gagal mencatat pembayaran.'); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[var(--nexus-charcoal)]/45 p-4 backdrop-blur-[2px]"><form onSubmit={submit} className="w-full max-w-md overflow-hidden rounded-xl border border-[var(--nexus-border)] bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-[var(--nexus-border)] p-5"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-[var(--nexus-yellow)]/20 text-[var(--nexus-yellow-deep)]"><CreditCard className="h-5 w-5" /></span><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[var(--nexus-muted)]">Pembayaran pesanan</p><h2 className="mt-1 text-lg font-bold text-[var(--nexus-charcoal)]">Catat Pembayaran</h2></div></div><button type="button" className="rounded-lg p-2 text-[var(--nexus-muted)] hover:bg-[var(--nexus-cream-soft)]" onClick={onClose} aria-label="Tutup"><X className="h-4 w-4" /></button></div><div className="space-y-4 p-5">{error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<label className="orders-field"><span className="orders-field-label">Jumlah</span><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-xs font-semibold text-[var(--nexus-muted)]">Rp</span><input required type="number" min="1" className="orders-input pl-9" value={amount} onChange={event => setAmount(event.target.value)} placeholder="0" /></div></label><label className="orders-field"><span className="orders-field-label">Tanggal</span><span className="relative"><CalendarDays className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--nexus-muted)]" /><input required type="datetime-local" className="orders-input pl-10" value={date} onChange={event => setDate(event.target.value)} /></span></label><label className="orders-field"><span className="orders-field-label">Metode pembayaran</span><select required className="orders-input" value={methodId} onChange={event => setMethodId(event.target.value)}><option value="">Pilih metode</option>{methods.map(method => <option key={method.id} value={method.id}>{method.name} ({method.method_type})</option>)}</select></label></div><div className="flex justify-end gap-2 border-t border-[var(--nexus-border)] bg-[var(--nexus-cream-soft)]/45 p-4"><Button type="button" variant="outline" onClick={onClose}>Batal</Button><Button type="submit" disabled={saving}><Receipt className="h-4 w-4" />{saving ? 'Menyimpan...' : 'Simpan Pembayaran'}</Button></div></form></div>;
}
