import React, { useEffect, useState } from 'react';
import { Button } from '../../../../components/ui/Button';
import { craftOrdersApi } from '../../../../services/api/craft-orders.api';
import type { PaymentMethodOption } from '../../../../types/craft-orders';

interface Props { orderId: number; isOpen: boolean; onClose: () => void; onSuccess: () => void; }
export function PaymentModal({ orderId, isOpen, onClose, onSuccess }: Props) {
  const [amount, setAmount] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 16)); const [methodId, setMethodId] = useState(''); const [methods, setMethods] = useState<PaymentMethodOption[]>([]); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { if (isOpen) void craftOrdersApi.getPaymentMethods().then(setMethods).catch(requestError => setError(requestError instanceof Error ? requestError.message : 'Gagal memuat metode pembayaran.')); }, [isOpen]);
  if (!isOpen) return null;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(null); try { await craftOrdersApi.recordPayment(orderId, { amount: Number(amount), payment_date: date, payment_method_id: Number(methodId) }); onSuccess(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Gagal mencatat pembayaran.'); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={submit} className="w-full max-w-md rounded-xl bg-white p-6 space-y-4"><h2 className="text-lg font-semibold">Catat Pembayaran</h2>{error && <div className="rounded bg-red-50 p-2 text-sm text-red-700">{error}</div>}<label className="block text-sm">Jumlah<input required type="number" min="1" className="mt-1 w-full border rounded p-2" value={amount} onChange={event => setAmount(event.target.value)} /></label><label className="block text-sm">Tanggal<input required type="datetime-local" className="mt-1 w-full border rounded p-2" value={date} onChange={event => setDate(event.target.value)} /></label><label className="block text-sm">Metode<select required className="mt-1 w-full border rounded p-2" value={methodId} onChange={event => setMethodId(event.target.value)}><option value="">Pilih metode</option>{methods.map(method => <option key={method.id} value={method.id}>{method.name} ({method.method_type})</option>)}</select></label><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Batal</Button><Button type="submit" disabled={saving}>{saving ? 'Menyimpan...' : 'Simpan'}</Button></div></form></div>;
}
