import React, { useEffect, useState } from 'react';
import { CreditCard, Receipt, X } from 'lucide-react';
import { Button } from '../../../../components/ui/Button';
import { craftOrdersApi } from '../../../../services/api/craft-orders.api';
import type { PaymentMethodOption, TreasuryAccountOption } from '../../../../types/craft-orders';
import { OrdersCurrencyInput } from './OrderInputs';

interface Props { orderId: number; isOpen: boolean; onClose: () => void; onSuccess: () => void; }
export function PaymentModal({ orderId, isOpen, onClose, onSuccess }: Props) {
  const [amount, setAmount] = useState<number | ''>(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 16)); const [methodId, setMethodId] = useState(''); const [treasuryId, setTreasuryId] = useState(''); const [methods, setMethods] = useState<PaymentMethodOption[]>([]); const [treasuries, setTreasuries] = useState<TreasuryAccountOption[]>([]); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { if (isOpen) void Promise.all([craftOrdersApi.getPaymentMethods(), craftOrdersApi.getTreasuryAccounts()]).then(([paymentMethods, accounts]) => { setMethods(paymentMethods); setTreasuries(accounts); }).catch(requestError => setError(requestError instanceof Error ? requestError.message : 'Gagal memuat referensi pembayaran.')); }, [isOpen]);
  if (!isOpen) return null;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (amount === '' || Number(amount) < 1 || !methodId || !treasuryId) { setError('Jumlah, metode, dan akun kas wajib diisi.'); return; } setSaving(true); setError(null); try { await craftOrdersApi.recordPayment(orderId, { amount: Number(amount), payment_date: date, payment_method_id: Number(methodId), treasury_account_id: Number(treasuryId) }); onSuccess(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Gagal mencatat pembayaran.'); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[var(--nexus-charcoal)]/45 p-4 backdrop-blur-[2px]"><form onSubmit={submit} className="w-full max-w-md overflow-hidden rounded-xl border border-[var(--nexus-border)] bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-[var(--nexus-border)] p-5"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-[var(--nexus-yellow)]/20 text-[var(--nexus-yellow-deep)]"><CreditCard className="h-5 w-5" /></span><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[var(--nexus-muted)]">Pembayaran pesanan</p><h2 className="mt-1 text-lg font-bold text-[var(--nexus-charcoal)]">Catat Pembayaran</h2></div></div><button type="button" className="rounded-lg p-2 text-[var(--nexus-muted)] hover:bg-[var(--nexus-cream-soft)]" onClick={onClose} aria-label="Tutup"><X className="h-4 w-4" /></button></div><div className="space-y-4 p-5">{error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<label className="orders-field"><span className="orders-field-label">Jumlah</span><OrdersCurrencyInput value={amount} onChange={setAmount} /></label><label className="orders-field"><span className="orders-field-label">Tanggal</span><input required type="datetime-local" className="orders-input" value={date} onChange={event => setDate(event.target.value)} /></label><label className="orders-field"><span className="orders-field-label">Metode pembayaran</span><select required className="orders-input orders-select" value={methodId} onChange={event => setMethodId(event.target.value)}><option value="">Pilih metode</option>{methods.map(method => <option key={method.id} value={method.id}>{method.name} ({method.method_type})</option>)}</select></label><label className="orders-field"><span className="orders-field-label">Akun kas / bank</span><select required className="orders-input orders-select" value={treasuryId} onChange={event => setTreasuryId(event.target.value)}><option value="">Pilih akun kas</option>{treasuries.map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label></div><div className="flex justify-end gap-2 border-t border-[var(--nexus-border)] bg-[var(--nexus-cream-soft)]/45 p-4"><Button type="button" variant="outline" onClick={onClose}>Batal</Button><Button type="submit" disabled={saving}><Receipt className="h-4 w-4" />{saving ? 'Menyimpan...' : 'Simpan Pembayaran'}</Button></div></form></div>;
}
