import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowDownRight, ArrowUpRight, Landmark, Plus, RefreshCw, Wallet } from 'lucide-react';
import { Button } from '../../../components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '../../../components/ui/Card';
import { formatCurrency } from '../../../lib/utils';
import { craftFinanceApi } from '../../../services/api/craft-finance.api';

const Loading=()=> <div className="p-8 text-sm text-[var(--nexus-muted)]">Memuat data keuangan...</div>;
const ErrorView=({retry}:{retry:()=>void})=><div className="p-8 text-sm text-red-700">Gagal memuat data. <button className="underline" onClick={retry}>Coba Lagi</button></div>;
const date=(value:string)=>value?new Date(value).toLocaleDateString('id-ID'):'—';
export function FinanceOverviewPage(){const [data,setData]=useState<any>();const [error,setError]=useState(false);const load=()=>{setError(false);craftFinanceApi.overview().then(setData).catch(()=>setError(true));};useEffect(load,[]);if(error)return <ErrorView retry={load}/>;if(!data)return <Loading/>;const cards=[['Total Kas',data.cash,Wallet,'text-[var(--nexus-charcoal)]'],['Pemasukan Periode',data.income,ArrowUpRight,'text-emerald-600'],['Pengeluaran Periode',data.expense,ArrowDownRight,'text-red-600'],['Arus Kas Bersih',data.net_cash_flow,Landmark,data.net_cash_flow>=0?'text-emerald-600':'text-red-600']];return <div className="space-y-6 max-w-7xl mx-auto pb-12"><div className="flex items-start justify-between"><div><h1 className="text-2xl font-bold text-[var(--nexus-charcoal)]">Ringkasan Keuangan</h1><p className="mt-1 text-sm text-[var(--nexus-muted)]">Posisi kas dan aktivitas Craft dari database operasional.</p></div><Link to="treasury"><Button><Plus className="h-4 w-4"/> Tambah Akun</Button></Link></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,Icon,color]:any)=><Card key={label}><CardContent className="p-5"><div className="flex justify-between"><p className="text-xs font-semibold uppercase tracking-wider text-[var(--nexus-muted)]">{label}</p><Icon className={`h-4 w-4 ${color}`}/></div><p className={`mt-3 text-2xl font-bold ${color}`}>{formatCurrency(Number(value||0))}</p></CardContent></Card>)}</div><div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Perhatian</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>Piutang pelanggan: <b>{formatCurrency(Number(data.receivables||0))}</b></p><p>Hutang pemasok: <b>{formatCurrency(Number(data.payables||0))}</b></p><p className="text-[var(--nexus-muted)]">Tidak ada angka simulasi; nilai di atas dihitung dari transaksi yang tercatat.</p></CardContent></Card><Card><CardHeader><CardTitle>Transaksi Terbaru</CardTitle></CardHeader><CardContent>{data.transactions.length?<div className="space-y-3">{data.transactions.map((t:any)=><div key={t.id} className="flex justify-between border-b pb-2 text-sm"><span>{t.description}</span><b className={t.transaction_type==='income'?'text-emerald-600':'text-red-600'}>{t.transaction_type==='income'?'+':'-'}{formatCurrency(Number(t.amount))}</b></div>)}</div>:<p className="text-sm text-[var(--nexus-muted)]">Belum ada transaksi tercatat.</p>}</CardContent></Card></div></div>}
export function TreasuryPage(){const [rows,setRows]=useState<any[]>();const [error,setError]=useState(false);const load=()=>{setError(false);craftFinanceApi.treasury().then(setRows).catch(()=>setError(true));};useEffect(load,[]);if(error)return <ErrorView retry={load}/>;if(!rows)return <Loading/>;return <div className="space-y-6 max-w-7xl mx-auto pb-12"><div><h1 className="text-2xl font-bold">Kas & Bank</h1><p className="text-sm text-[var(--nexus-muted)]">Saldo saat ini adalah cache yang diperbarui oleh posting transaksi.</p></div>{!rows.length?<Card><CardContent className="p-8"><h2 className="font-bold">Belum Ada Akun Kas</h2><p className="mt-1 text-sm text-[var(--nexus-muted)]">Tambahkan akun kas, bank, e-wallet, atau saldo marketplace sebelum mencatat pembayaran.</p></CardContent></Card>:<Card><CardContent className="overflow-x-auto p-0"><table className="w-full text-sm"><thead className="bg-[var(--nexus-cream-soft)] text-left text-xs uppercase text-[var(--nexus-muted)]"><tr><th className="p-4">Akun</th><th>Jenis</th><th>Saldo</th><th>Status</th><th>Transaksi Terakhir</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-4 font-medium">{r.name}<div className="text-xs text-[var(--nexus-muted)]">{r.provider_name||'—'} · {r.account_number_masked||'—'}</div></td><td>{r.account_type}</td><td className="font-semibold">{formatCurrency(Number(r.current_balance))}</td><td>{r.is_active?'Aktif':'Nonaktif'}</td><td>{date(r.last_transaction_at)}</td></tr>)}</tbody></table></CardContent></Card>}</div>}
const endpointByPage:any={transactions:'transactions',receivables:'receivables',payables:'payables'};
export function FinanceListPage({page}:{page:'transactions'|'receivables'|'payables'}){const [rows,setRows]=useState<any[]>();const [error,setError]=useState(false);const load=()=>{setError(false);(craftFinanceApi as any)[endpointByPage[page]]().then(setRows).catch(()=>setError(true));};useEffect(load,[page]);if(error)return <ErrorView retry={load}/>;if(!rows)return <Loading/>;const title={transactions:'Transaksi',receivables:'Piutang Pelanggan',payables:'Hutang Pemasok'}[page];return <div className="space-y-6 max-w-7xl mx-auto pb-12"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">{title}</h1><p className="text-sm text-[var(--nexus-muted)]">Data aktual Craft.</p></div><Button variant="outline" onClick={load}><RefreshCw className="h-4 w-4"/> Muat ulang</Button></div><Card><CardContent className="overflow-x-auto p-0">{rows.length?<table className="w-full text-sm"><thead className="bg-[var(--nexus-cream-soft)] text-left text-xs uppercase text-[var(--nexus-muted)]"><tr><th className="p-4">Referensi</th><th>Pihak</th><th>Status</th><th>Nilai</th><th>Sisa</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-4">{r.transaction_code||r.invoice_number||r.supplier_invoice_number}<div className="text-xs text-[var(--nexus-muted)]">{r.description||date(r.transaction_date||r.issue_date||r.invoice_date)}</div></td><td>{r.party_name||'—'}</td><td>{r.status_code}</td><td>{formatCurrency(Number(r.amount||r.total_amount))}</td><td>{r.balance_due!==undefined?formatCurrency(Number(r.balance_due)):'—'}</td></tr>)}</tbody></table>:<div className="p-8 text-sm text-[var(--nexus-muted)]">Belum ada data.</div>}</CardContent></Card></div>}
