import type { AutomationTemplate } from './craft-automations.types';

export const AUTOMATION_TEMPLATES: AutomationTemplate[] = [
  { code: 'order-deadline-priority', name: 'Deadline Pesanan Mendekat', description: 'Naikkan prioritas pesanan dalam 24 jam menuju tenggat.', rule: { name: 'Deadline Pesanan Mendekat', trigger_type: 'sensor', trigger_event: 'order.deadline_approaching', trigger_config_json: { version: 1, schedule: { type: 'cron', expression: '*/15 * * * *', timezone: 'Asia/Jakarta' } }, condition_json: { logic: 'all', conditions: [{ field: 'order.deadline_at', operator: 'within_hours', value: 24 }] }, action_json: { version: 1, actions: [{ type: 'order.priority.set', config: { priority: 'critical' } }] }, cooldown_seconds: 3600 } },
  { code: 'ready-to-production', name: 'Pesanan Ready → Antrean Produksi', description: 'Antrikan item pesanan ketika status berubah menjadi Ready.', rule: { name: 'Pesanan Ready → Antrean Produksi', trigger_type: 'event', trigger_event: 'order.status_changed', condition_json: { logic: 'all', conditions: [{ field: 'order.new_status', operator: 'eq', value: 'ready' }] }, action_json: { version: 1, actions: [{ type: 'production.enqueue_order_items' }] } } },
  { code: 'low-stock-warning', name: 'Stok Material Menipis', description: 'Beri peringatan tim Craft saat stok melewati batas rendah.', rule: { name: 'Stok Material Menipis', trigger_type: 'event', trigger_event: 'material.low_stock', action_json: { version: 1, actions: [{ type: 'notification.create', config: { severity: 'warning', title_template: 'Stok rendah: {{material.name}}', message_template: 'Stok {{material.material_code}} berada di bawah titik pesan ulang.' } }] }, cooldown_seconds: 14400 } },
  { code: 'low-stock-pr', name: 'Stok Menipis → Buat Permintaan Pembelian', description: 'Buat draft PR untuk material rendah; tetap membutuhkan persetujuan manusia.', rule: { name: 'Stok Menipis → Buat Permintaan Pembelian', trigger_type: 'event', trigger_event: 'material.low_stock', action_json: { version: 1, actions: [{ type: 'procurement.create_purchase_request' }] }, cooldown_seconds: 86400 } },
  { code: 'print-failed-alert', name: 'Cetak Gagal', description: 'Kirim peringatan kritis saat pekerjaan cetak gagal.', rule: { name: 'Cetak Gagal', trigger_type: 'event', trigger_event: 'production.job_failed', action_json: { version: 1, actions: [{ type: 'notification.create', config: { severity: 'critical', title_template: 'Cetak gagal: {{production.job_code}}', message_template: 'Pekerjaan cetak gagal dan perlu ditinjau operator.' } }] }, cooldown_seconds: 900 } },
  { code: 'printer-maintenance', name: 'Perawatan Printer Mendekat', description: 'Peringatkan tim bila perawatan printer sudah jatuh tempo.', rule: { name: 'Perawatan Printer Mendekat', trigger_type: 'sensor', trigger_event: 'printer.maintenance_due', trigger_config_json: { version: 1, schedule: { type: 'cron', expression: '0 8 * * *', timezone: 'Asia/Jakarta' } }, action_json: { version: 1, actions: [{ type: 'notification.create', config: { severity: 'warning', title_template: 'Perawatan printer: {{printer.name}}', message_template: 'Printer {{printer.code}} telah mencapai jadwal perawatan.' } }] }, cooldown_seconds: 86400 } },
  { code: 'customer-invoice-overdue', name: 'Invoice Pelanggan Terlambat', description: 'Buat peringatan untuk invoice pelanggan yang lewat jatuh tempo.', rule: { name: 'Invoice Pelanggan Terlambat', trigger_type: 'sensor', trigger_event: 'finance.customer_invoice_overdue', trigger_config_json: { version: 1, schedule: { type: 'cron', expression: '0 9 * * *', timezone: 'Asia/Jakarta' } }, action_json: { version: 1, actions: [{ type: 'notification.create', config: { severity: 'warning', title_template: 'Invoice terlambat: {{invoice.invoice_code}}', message_template: 'Invoice memiliki saldo tertunggak {{invoice.outstanding_amount}}.' } }] }, cooldown_seconds: 86400 } },
  { code: 'supplier-invoice-overdue', name: 'Tagihan Pemasok Terlambat', description: 'Buat peringatan untuk tagihan pemasok yang lewat jatuh tempo.', rule: { name: 'Tagihan Pemasok Terlambat', trigger_type: 'sensor', trigger_event: 'procurement.supplier_invoice_overdue', trigger_config_json: { version: 1, schedule: { type: 'cron', expression: '0 9 * * *', timezone: 'Asia/Jakarta' } }, action_json: { version: 1, actions: [{ type: 'notification.create', config: { severity: 'warning', title_template: 'Tagihan pemasok terlambat: {{invoice.invoice_code}}', message_template: 'Tagihan pemasok memiliki saldo tertunggak {{invoice.outstanding_amount}}.' } }] }, cooldown_seconds: 86400 } },
  { code: 'marketplace-hourly-sync', name: 'Sinkronisasi Marketplace Berkala', description: 'Menjalankan connector marketplace yang benar-benar tersedia setiap jam.', rule: { name: 'Sinkronisasi Marketplace Berkala', trigger_type: 'schedule', trigger_event: 'schedule', trigger_config_json: { version: 1, schedule: { type: 'cron', expression: '0 * * * *', timezone: 'Asia/Jakarta' } }, action_json: { version: 1, actions: [{ type: 'marketplace.sync', config: { integration_id: 0 } }] } } },
  { code: 'weekly-craft-report', name: 'Laporan Craft Mingguan', description: 'Menjadwalkan generation laporan mingguan bila generator tersedia.', rule: { name: 'Laporan Craft Mingguan', trigger_type: 'schedule', trigger_event: 'schedule', trigger_config_json: { version: 1, schedule: { type: 'cron', expression: '0 8 * * 1', timezone: 'Asia/Jakarta' } }, action_json: { version: 1, actions: [{ type: 'analytics.generate_report', config: { format: 'xlsx' } }] } } },
];

export class AutomationTemplateService {
  list() { return AUTOMATION_TEMPLATES; }
  get(code: string) { return AUTOMATION_TEMPLATES.find((template) => template.code === code); }
}
