CREATE TABLE IF NOT EXISTS craft_order_drafts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  business_unit_id BIGINT UNSIGNED NOT NULL,
  draft_code VARCHAR(80) DEFAULT NULL,
  title VARCHAR(180) DEFAULT NULL,
  payload_json JSON NOT NULL,
  schema_version INT UNSIGNED NOT NULL DEFAULT 1,
  status_code VARCHAR(30) NOT NULL DEFAULT 'active',
  converted_order_id BIGINT UNSIGNED DEFAULT NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  updated_by BIGINT UNSIGNED DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  converted_at DATETIME(3) DEFAULT NULL,
  deleted_at DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_craft_order_drafts_code (draft_code),
  KEY idx_craft_order_drafts_active (business_unit_id, status_code, updated_at),
  KEY idx_craft_order_drafts_creator (created_by, status_code, updated_at),
  KEY idx_craft_order_drafts_converted_order (converted_order_id),
  KEY idx_craft_order_drafts_updated_by (updated_by),
  CONSTRAINT fk_craft_order_drafts_bu FOREIGN KEY (business_unit_id) REFERENCES business_units (id),
  CONSTRAINT fk_craft_order_drafts_converted_order FOREIGN KEY (converted_order_id) REFERENCES craft_orders (id) ON DELETE SET NULL,
  CONSTRAINT fk_craft_order_drafts_created_by FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT fk_craft_order_drafts_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
