-- GLOBAL CALENDAR & TASKS (MySQL 8.0)
-- The current development database was reconciled manually through phpMyAdmin.
-- This file is source-control migration history for clean/legacy installations only.
-- DO NOT execute it against the current development database from this repository.

SET @schema_name := DATABASE();

-- MySQL 8 does not support ADD COLUMN IF NOT EXISTS.  Each operation therefore
-- uses INFORMATION_SCHEMA plus PREPARE/EXECUTE and is safe for clean installs.
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='calendar_events' AND COLUMN_NAME='event_code')=0, 'ALTER TABLE calendar_events ADD COLUMN event_code VARCHAR(80) NULL AFTER business_unit_id', 'SELECT 1'); PREPARE calendar_ddl FROM @sql; EXECUTE calendar_ddl; DEALLOCATE PREPARE calendar_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='calendar_events' AND COLUMN_NAME='location_name')=0, 'ALTER TABLE calendar_events ADD COLUMN location_name VARCHAR(220) NULL AFTER description', 'SELECT 1'); PREPARE calendar_ddl FROM @sql; EXECUTE calendar_ddl; DEALLOCATE PREPARE calendar_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='calendar_events' AND COLUMN_NAME='source_module_code')=0, 'ALTER TABLE calendar_events ADD COLUMN source_module_code VARCHAR(80) NULL AFTER event_type', 'SELECT 1'); PREPARE calendar_ddl FROM @sql; EXECUTE calendar_ddl; DEALLOCATE PREPARE calendar_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='calendar_events' AND COLUMN_NAME='status_code')=0, 'ALTER TABLE calendar_events ADD COLUMN status_code VARCHAR(30) NOT NULL DEFAULT ''scheduled'' AFTER all_day', 'SELECT 1'); PREPARE calendar_ddl FROM @sql; EXECUTE calendar_ddl; DEALLOCATE PREPARE calendar_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='calendar_events' AND COLUMN_NAME='reminder_minutes_before')=0, 'ALTER TABLE calendar_events ADD COLUMN reminder_minutes_before INT UNSIGNED NULL AFTER status_code', 'SELECT 1'); PREPARE calendar_ddl FROM @sql; EXECUTE calendar_ddl; DEALLOCATE PREPARE calendar_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='calendar_events' AND COLUMN_NAME='source_code')=0, 'ALTER TABLE calendar_events ADD COLUMN source_code VARCHAR(120) NULL AFTER source_id', 'SELECT 1'); PREPARE calendar_ddl FROM @sql; EXECUTE calendar_ddl; DEALLOCATE PREPARE calendar_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='calendar_events' AND COLUMN_NAME='source_key')=0, 'ALTER TABLE calendar_events ADD COLUMN source_key VARCHAR(190) NULL AFTER source_code', 'SELECT 1'); PREPARE calendar_ddl FROM @sql; EXECUTE calendar_ddl; DEALLOCATE PREPARE calendar_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='calendar_events' AND COLUMN_NAME='updated_by')=0, 'ALTER TABLE calendar_events ADD COLUMN updated_by BIGINT UNSIGNED NULL AFTER created_by', 'SELECT 1'); PREPARE calendar_ddl FROM @sql; EXECUTE calendar_ddl; DEALLOCATE PREPARE calendar_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='calendar_events' AND COLUMN_NAME='deleted_at')=0, 'ALTER TABLE calendar_events ADD COLUMN deleted_at DATETIME(3) NULL AFTER updated_at', 'SELECT 1'); PREPARE calendar_ddl FROM @sql; EXECUTE calendar_ddl; DEALLOCATE PREPARE calendar_ddl;

SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='tasks' AND COLUMN_NAME='start_at')=0, 'ALTER TABLE tasks ADD COLUMN start_at DATETIME(3) NULL AFTER priority_code', 'SELECT 1'); PREPARE task_ddl FROM @sql; EXECUTE task_ddl; DEALLOCATE PREPARE task_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='tasks' AND COLUMN_NAME='reminder_minutes_before')=0, 'ALTER TABLE tasks ADD COLUMN reminder_minutes_before INT UNSIGNED NULL AFTER due_at', 'SELECT 1'); PREPARE task_ddl FROM @sql; EXECUTE task_ddl; DEALLOCATE PREPARE task_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='tasks' AND COLUMN_NAME='source_module_code')=0, 'ALTER TABLE tasks ADD COLUMN source_module_code VARCHAR(80) NULL AFTER reminder_minutes_before', 'SELECT 1'); PREPARE task_ddl FROM @sql; EXECUTE task_ddl; DEALLOCATE PREPARE task_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='tasks' AND COLUMN_NAME='source_code')=0, 'ALTER TABLE tasks ADD COLUMN source_code VARCHAR(120) NULL AFTER source_id', 'SELECT 1'); PREPARE task_ddl FROM @sql; EXECUTE task_ddl; DEALLOCATE PREPARE task_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='tasks' AND COLUMN_NAME='source_key')=0, 'ALTER TABLE tasks ADD COLUMN source_key VARCHAR(190) NULL AFTER source_code', 'SELECT 1'); PREPARE task_ddl FROM @sql; EXECUTE task_ddl; DEALLOCATE PREPARE task_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='tasks' AND COLUMN_NAME='updated_by')=0, 'ALTER TABLE tasks ADD COLUMN updated_by BIGINT UNSIGNED NULL AFTER created_by', 'SELECT 1'); PREPARE task_ddl FROM @sql; EXECUTE task_ddl; DEALLOCATE PREPARE task_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='tasks' AND COLUMN_NAME='deleted_at')=0, 'ALTER TABLE tasks ADD COLUMN deleted_at DATETIME(3) NULL AFTER updated_at', 'SELECT 1'); PREPARE task_ddl FROM @sql; EXECUTE task_ddl; DEALLOCATE PREPARE task_ddl;

SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='task_assignees')=0, 'CREATE TABLE task_assignees (task_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,assigned_by BIGINT UNSIGNED NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),PRIMARY KEY(task_id,user_id),KEY idx_task_assignees_user(user_id,task_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4', 'SELECT 1'); PREPARE task_ddl FROM @sql; EXECUTE task_ddl; DEALLOCATE PREPARE task_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='task_assignees' AND COLUMN_NAME='assigned_by')=0, 'ALTER TABLE task_assignees ADD COLUMN assigned_by BIGINT UNSIGNED NULL AFTER user_id', 'SELECT 1'); PREPARE task_ddl FROM @sql; EXECUTE task_ddl; DEALLOCATE PREPARE task_ddl;

SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='calendar_event_attendees')=0, 'CREATE TABLE calendar_event_attendees (event_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,response_status_code VARCHAR(20) NOT NULL DEFAULT ''invited'',added_by BIGINT UNSIGNED NULL,responded_at DATETIME(3) NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),PRIMARY KEY(event_id,user_id),KEY idx_calendar_attendees_user(user_id,event_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4', 'SELECT 1'); PREPARE calendar_ddl FROM @sql; EXECUTE calendar_ddl; DEALLOCATE PREPARE calendar_ddl;

SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='calendar_events' AND INDEX_NAME='uq_calendar_events_org_source_key')=0, 'CREATE UNIQUE INDEX uq_calendar_events_org_source_key ON calendar_events (organization_id,source_key)', 'SELECT 1'); PREPARE calendar_ddl FROM @sql; EXECUTE calendar_ddl; DEALLOCATE PREPARE calendar_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='tasks' AND INDEX_NAME='uq_tasks_org_source_key')=0, 'CREATE UNIQUE INDEX uq_tasks_org_source_key ON tasks (organization_id,source_key)', 'SELECT 1'); PREPARE task_ddl FROM @sql; EXECUTE task_ddl; DEALLOCATE PREPARE task_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='calendar_events' AND INDEX_NAME='idx_calendar_events_org_scope_time')=0, 'CREATE INDEX idx_calendar_events_org_scope_time ON calendar_events (organization_id,business_unit_id,deleted_at,start_at,id)', 'SELECT 1'); PREPARE calendar_ddl FROM @sql; EXECUTE calendar_ddl; DEALLOCATE PREPARE calendar_ddl;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='tasks' AND INDEX_NAME='idx_tasks_org_scope_status_due')=0, 'CREATE INDEX idx_tasks_org_scope_status_due ON tasks (organization_id,business_unit_id,deleted_at,status_code,due_at,id)', 'SELECT 1'); PREPARE task_ddl FROM @sql; EXECUTE task_ddl; DEALLOCATE PREPARE task_ddl;

INSERT INTO permissions (code,module_code,name,description,created_at) VALUES
('calendar.read','calendar','Lihat Kalender','Melihat jadwal dan tenggat yang dapat diakses.',UTC_TIMESTAMP(3)),
('calendar.write','calendar','Kelola Kalender','Membuat dan mengubah acara manual dalam workspace yang dapat diakses.',UTC_TIMESTAMP(3)),
('calendar.manage','calendar','Administrasi Kalender','Mengelola acara global dan acara manual lintas pemilik.',UTC_TIMESTAMP(3)),
('tasks.read','tasks','Lihat Tugas','Melihat tugas yang dapat diakses.',UTC_TIMESTAMP(3)),
('tasks.write','tasks','Kelola Tugas','Membuat, memperbarui, dan menjalankan tugas yang ditugaskan.',UTC_TIMESTAMP(3)),
('tasks.manage','tasks','Administrasi Tugas','Mengelola tugas global dan penugasan lintas pemilik.',UTC_TIMESTAMP(3))
ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description);
