import React, { useState } from 'react';
import { Check, Pencil, Plus, Power, X } from 'lucide-react';
import { Button } from '../../../../components/ui/Button';
import { craftProductsApi } from '../../../../services/api/craft-products.api';
import type { ProductCategory } from '../../../../types/craft-products';

const input = 'h-9 w-full rounded-lg border border-[var(--nexus-border)] bg-white px-3 text-sm outline-none focus:border-[var(--nexus-yellow-deep)]';

export function CategoryManager({ categories, open, onClose, onChanged }: { categories: ProductCategory[]; open: boolean; onClose: () => void; onChanged: () => Promise<void> }) {
  const [name, setName] = useState(''); const [code, setCode] = useState(''); const [parentId, setParentId] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [editing, setEditing] = useState<number | null>(null);
  if (!open) return null;
  const create = async (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) return; setSaving(true); setError(null); try { await craftProductsApi.createCategory({ name: name.trim(), code: code.trim() || null, parent_id: parentId ? Number(parentId) : null }); setName(''); setCode(''); setParentId(''); await onChanged(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Kategori gagal dibuat.'); } finally { setSaving(false); } };
  const toggle = async (category: ProductCategory) => { setSaving(true); setError(null); try { if (category.is_active) await craftProductsApi.deactivateCategory(category.id); else await craftProductsApi.updateCategory(category.id, { is_active: true }); await onChanged(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Status kategori gagal diubah.'); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-[var(--nexus-charcoal)]/50 p-4 backdrop-blur-sm"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-xl border border-[var(--nexus-border)] bg-white shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="category-manager-title"><div className="sticky top-0 flex items-start justify-between border-b border-[var(--nexus-border)] bg-white p-5"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[var(--nexus-muted)]">Master data</p><h2 id="category-manager-title" className="mt-1 text-lg font-bold text-[var(--nexus-charcoal)]">Kelola Kategori Produk</h2></div><button className="rounded-lg p-2 text-[var(--nexus-muted)] hover:bg-[var(--nexus-cream-soft)]" onClick={onClose} aria-label="Tutup"><X className="h-4 w-4" /></button></div><div className="space-y-5 p-5">{error && <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<form onSubmit={create} className="grid gap-3 rounded-xl bg-[var(--nexus-cream-soft)]/60 p-4 md:grid-cols-[1fr_150px_1fr_auto]"><input className={input} value={name} onChange={event => setName(event.target.value)} placeholder="Nama kategori baru" /><input className={input} value={code} onChange={event => setCode(event.target.value)} placeholder="Kode otomatis" /><select className={input} value={parentId} onChange={event => setParentId(event.target.value)}><option value="">Kategori induk (opsional)</option>{categories.filter(category => category.is_active).map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select><Button type="submit" size="sm" disabled={saving}><Plus className="h-3.5 w-3.5" />Tambah</Button></form><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-[var(--nexus-border)] text-xs text-[var(--nexus-muted)]"><tr><th className="p-3">Kategori</th><th className="p-3">Kode</th><th className="p-3">Induk</th><th className="p-3 text-center">Produk</th><th className="p-3 text-right">Aksi</th></tr></thead><tbody>{categories.map(category => <CategoryRow key={category.id} category={category} categories={categories} saving={saving} editing={editing === category.id} setEditing={setEditing} onChanged={onChanged} onToggle={toggle} onError={setError} />)}</tbody></table>{categories.length === 0 && <div className="p-8 text-center text-sm text-[var(--nexus-muted)]">Belum ada kategori. Buat kategori pertama untuk mengelompokkan produk.</div>}</div></div></div></div>;
}

function CategoryRow({ category, categories, saving, editing, setEditing, onChanged, onToggle, onError }: { category: ProductCategory; categories: ProductCategory[]; saving: boolean; editing: boolean; setEditing: (id: number | null) => void; onChanged: () => Promise<void>; onToggle: (category: ProductCategory) => Promise<void>; onError: (value: string | null) => void; key?: React.Key }) {
  const [name, setName] = useState(category.name); const [code, setCode] = useState(category.code); const [parentId, setParentId] = useState(category.parent_id ? String(category.parent_id) : '');
  const save = async () => { onError(null); try { await craftProductsApi.updateCategory(category.id, { name: name.trim(), code: code.trim(), parent_id: parentId ? Number(parentId) : null }); setEditing(null); await onChanged(); } catch (error) { onError(error instanceof Error ? error.message : 'Kategori gagal diperbarui.'); } };
  return <tr className="border-b border-[var(--nexus-border)]/60 last:border-0">{editing ? <><td className="p-3"><input className={input} value={name} onChange={event => setName(event.target.value)} /></td><td className="p-3"><input className={input} value={code} onChange={event => setCode(event.target.value)} /></td><td className="p-3"><select className={input} value={parentId} onChange={event => setParentId(event.target.value)}><option value="">–</option>{categories.filter(item => item.id !== category.id).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></td><td className="p-3 text-center">{category.product_count}</td><td className="p-3 text-right"><Button size="sm" onClick={() => void save()}><Check className="h-3.5 w-3.5" />Simpan</Button></td></> : <><td className="p-3"><span className={category.is_active ? 'font-semibold text-[var(--nexus-charcoal)]' : 'text-[var(--nexus-muted)]'}>{category.name}{!category.is_active && <span className="ml-2 text-xs">(nonaktif)</span>}</span></td><td className="p-3 font-mono text-xs text-[var(--nexus-muted)]">{category.code}</td><td className="p-3 text-[var(--nexus-muted)]">{category.parent_name || '–'}</td><td className="p-3 text-center">{category.product_count}</td><td className="p-3"><div className="flex justify-end gap-1"><Button variant="ghost" size="sm" onClick={() => setEditing(category.id)} disabled={saving}><Pencil className="h-3.5 w-3.5" />Edit</Button><Button variant="ghost" size="sm" onClick={() => void onToggle(category)} disabled={saving} className={category.is_active ? 'text-amber-700' : 'text-emerald-700'}><Power className="h-3.5 w-3.5" />{category.is_active ? 'Nonaktifkan' : 'Aktifkan'}</Button></div></td></>}</tr>;
}
