#!/usr/bin/env node
import { createHmac, randomBytes } from 'node:crypto';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { setTimeout as delay } from 'node:timers/promises';
import dotenv from 'dotenv';
import mysql from 'mysql2/promise';

const root = path.resolve(import.meta.dirname, '..', '..'); dotenv.config({ path: path.join(root, 'server', '.env'), quiet: true });
const frontend = process.env.AUDIT_BROWSER_BASE_URL || 'http://localhost:5173'; const chrome = process.env.CHROME_PATH || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const assert = (value, message) => { if (!value) throw new Error(message); };
const tokenFor = user => { const now = Math.floor(Date.now() / 1000); const head = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url'); const payload = Buffer.from(JSON.stringify({ id: user.id, organization_id: user.organization_id, username: user.username, iat: now, exp: now + 900 })).toString('base64url'); return `${head}.${payload}.${createHmac('sha256', process.env.JWT_SECRET).update(`${head}.${payload}`).digest('base64url')}`; };
const database = () => mysql.createConnection({ host: process.env.DB_HOST, port: Number(process.env.DB_PORT), user: process.env.DB_USER, password: process.env.DB_PASSWORD, database: process.env.DB_NAME });
async function waitPort(profile, child) { const file = path.join(profile, 'DevToolsActivePort'); const until = Date.now() + 20_000; while (Date.now() < until) { if (child.exitCode !== null) throw new Error(`Chrome exited (${child.exitCode}).`); try { const [port] = (await readFile(file, 'utf8')).trim().split(/\r?\n/); if (Number(port)) return Number(port); } catch {} await delay(100); } throw new Error('Chrome DevTools did not start.'); }
function connect(url) { const socket = new WebSocket(url); let id = 0; const pending = new Map(); socket.addEventListener('message', async event => { const message = JSON.parse(typeof event.data === 'string' ? event.data : await event.data.text()); if (message.id && pending.has(message.id)) { const call = pending.get(message.id); pending.delete(message.id); call.resolve(message.error ? { __cdp_error: message.error.message } : message.result || {}); } }); const ready = new Promise((resolve, reject) => { socket.addEventListener('open', resolve, { once: true }); socket.addEventListener('error', () => reject(new Error('Cannot connect to Chrome DevTools.')), { once: true }); }); return { socket, send: async (method, params = {}) => { await ready; return new Promise((resolve, reject) => { pending.set(++id, { resolve, reject }); socket.send(JSON.stringify({ id, method, params })); }); } }; }
const evaluate = async (cdp, expression) => (await cdp.send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true })).result?.value;
async function waitFor(cdp, expression, timeout = 15_000) { const until = Date.now() + timeout; while (Date.now() < until) { if (await evaluate(cdp, expression)) return; await delay(200); } throw new Error(`Browser condition timed out: ${expression}`); }

async function run() {
  const suffix = randomBytes(5).toString('hex'); const username = `audit_browser_${suffix}`; const viewUsername = `audit_browser_view_${suffix}`; const deniedUsername = `audit_browser_none_${suffix}`; const fixture = `Audit Browser Fixture ${suffix}`; const secret = `browser-secret-${suffix}`;
  const db = await database(); const userIds = []; let roleId = 0; let viewRoleId = 0; let child; let profile;
  try {
    const [[craft]] = await db.execute("SELECT id FROM business_units WHERE LOWER(code)='craft' AND is_active=1 LIMIT 1"); assert(craft?.id, 'An active Craft workspace is required.');
    const [permissions] = await db.execute("SELECT id,code FROM permissions WHERE code IN ('audit.read','reports.export')"); const auditPermission = permissions.find(row => row.code === 'audit.read')?.id; const exportPermission = permissions.find(row => row.code === 'reports.export')?.id; assert(auditPermission && exportPermission, 'Audit permissions are missing.');
    const [role] = await db.execute("INSERT INTO roles (organization_id,code,name,scope_code,is_system,is_active) VALUES (1,?,?, 'global',0,1)", [`AUDIT_BROWSER_${suffix}`.toUpperCase(), `Audit browser ${suffix}`]); roleId = Number(role.insertId);
    const [viewRole] = await db.execute("INSERT INTO roles (organization_id,code,name,scope_code,is_system,is_active) VALUES (1,?,?, 'global',0,1)", [`AUDIT_BROWSER_VIEW_${suffix}`.toUpperCase(), `Audit browser view ${suffix}`]); viewRoleId = Number(viewRole.insertId);
    await db.execute('INSERT INTO role_permissions (role_id,permission_id) VALUES (?,?),(?,?),(?,?)', [roleId, auditPermission, roleId, exportPermission, viewRoleId, auditPermission]);
    const makeUser = async (handle, name) => { const [result] = await db.execute("INSERT INTO users (organization_id,full_name,username,email,password_hash,status_code,approval_status_code,registration_source,default_workspace_code,approval_requested_at) VALUES (1,?,?,?,?,?,?,'browser','craft',UTC_TIMESTAMP(3))", [name, handle, `${handle}@example.invalid`, '$2b$10$fixturehashonlyneverused', 'active', 'approved']); userIds.push(Number(result.insertId)); return Number(result.insertId); };
    const auditorId = await makeUser(username, 'Audit Browser Auditor'); const viewId = await makeUser(viewUsername, 'Audit Browser Viewer'); const deniedId = await makeUser(deniedUsername, 'Audit Browser Denied');
    await db.execute('INSERT INTO user_roles (user_id,role_id) VALUES (?,?),(?,?)', [auditorId, roleId, viewId, viewRoleId]); await db.execute('INSERT INTO user_business_units (user_id,business_unit_id,can_access) VALUES (?, ?, 1),(?, ?, 1)', [auditorId, craft.id, viewId, craft.id]);
    await db.execute("INSERT INTO audit_logs (organization_id,user_id,module_code,action_code,entity_type,entity_code,description,created_at) VALUES (?,?, 'auth','login','fixture',?,'Browser Login fixture',UTC_TIMESTAMP(3)),(?,?, 'auth','logout','fixture',?,'Browser Logout fixture',UTC_TIMESTAMP(3))", [1, auditorId, `LOGIN-${suffix}`, 1, auditorId, `LOGOUT-${suffix}`]);
    for (let index = 0; index < 28; index += 1) await db.execute("INSERT INTO audit_logs (organization_id,business_unit_id,user_id,module_code,action_code,entity_type,entity_code,description,created_at) VALUES (?,?,?,?, 'fixture.update','fixture',?,?,UTC_TIMESTAMP(3))", [1, craft.id, auditorId, 'smoke_browser', `PAGE-${suffix}-${index}`, `Pagination fixture ${suffix} ${index}`]);
    await db.execute("INSERT INTO audit_logs (organization_id,user_id,module_code,action_code,entity_type,entity_code,description,new_values,created_at) VALUES (?,?, 'smoke_browser','fixture.update','fixture',?,?,JSON_OBJECT('password',?,'api_key',?),UTC_TIMESTAMP(3))", [1, auditorId, `BROWSER-${suffix}`, fixture, secret, secret]);
    console.log('Audit browser: fixtures ready');
    profile = await mkdtemp(path.join(os.tmpdir(), 'uni-nexus-audit-browser-')); child = spawn(chrome, ['--headless=new', '--disable-gpu', '--remote-debugging-port=0', '--remote-allow-origins=*', `--user-data-dir=${profile}`, '--window-size=1280,900', 'about:blank'], { windowsHide: true });
    const port = await waitPort(profile, child); console.log('Audit browser: Chrome ready'); const targets = await (await fetch(`http://127.0.0.1:${port}/json/list`)).json(); const page = targets.find(target => target.type === 'page'); assert(page?.webSocketDebuggerUrl, 'No browser page is available.'); const cdp = connect(page.webSocketDebuggerUrl); await cdp.send('Page.enable'); await cdp.send('Runtime.enable');
    await cdp.send('Page.addScriptToEvaluateOnNewDocument', { source: `if (!localStorage.getItem('token')) localStorage.setItem('token', ${JSON.stringify(tokenFor({ id: auditorId, organization_id: 1, username }))}); window.__auditErrors=[]; window.addEventListener('error',event=>window.__auditErrors.push(event.message)); window.addEventListener('unhandledrejection',event=>window.__auditErrors.push(String(event.reason?.message||event.reason||'Unhandled promise rejection')));` });
    void cdp.send('Page.navigate', { url: `${frontend}/app/audit-log` }).catch(() => undefined); await delay(700); console.log(`Audit browser: initial ${JSON.stringify(await evaluate(cdp, '({href:location.href,body:document.body?.innerText?.slice(0,500),title:document.querySelector(\"main h1\")?.textContent})'))}`); await waitFor(cdp, "document.querySelector('main h1')?.textContent?.includes('Log Audit')"); console.log('Audit browser: page title ready'); await waitFor(cdp, `document.body.innerText.includes(${JSON.stringify(fixture)})`); console.log('Audit browser: fixture visible');
    let state = JSON.parse(await evaluate(cdp, "JSON.stringify({title:document.querySelector('main h1')?.textContent,body:document.body.innerText.slice(0,12000),errors:window.__auditErrors||[],exportButtons:[...document.querySelectorAll('button')].map(x=>x.textContent).filter(Boolean),filters:[...document.querySelectorAll('select')].map(x=>x.getAttribute('aria-label'))})")); assert(state.title.includes('Log Audit'), 'Audit title is missing.'); assert(state.body.includes(fixture), 'Audit fixture is missing.'); assert(state.filters.length >= 6, 'Audit filters did not render.'); assert(state.exportButtons.some(text => text.includes('CSV')) && state.exportButtons.some(text => text.includes('Excel')), 'Export controls are missing for reports.export.'); assert(!state.errors.length, `Audit page browser errors: ${state.errors.join('; ')}`); console.log('Audit browser: initial assertions passed');
    await evaluate(cdp, `(function(){const select=document.querySelector('[aria-label="Grup tindakan"]');const set=Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set;set.call(select,'authentication');select.dispatchEvent(new Event('change',{bubbles:true}));})()`); await waitFor(cdp, "document.body.innerText.includes('Browser Login fixture') && document.body.innerText.includes('Browser Logout fixture')"); console.log('Audit browser: authentication filter passed');
    await evaluate(cdp, `(function(){const select=document.querySelector('[aria-label="Grup tindakan"]');const set=Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set;set.call(select,'');select.dispatchEvent(new Event('change',{bubbles:true}));return true;})()`); console.log('Audit browser: authentication filter cleared'); await evaluate(cdp, `(function(){const input=document.querySelector('input[placeholder*="Cari"]');const inputSet=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;inputSet.call(input,${JSON.stringify(fixture)});input.dispatchEvent(new Event('input',{bubbles:true}));return true;})()`); console.log('Audit browser: search entered'); await delay(700); await waitFor(cdp, `document.body.innerText.includes(${JSON.stringify(fixture)})`);
    const opened = await evaluate(cdp, `(function(){const row=[...document.querySelectorAll('tr')].find(x=>x.textContent?.includes(${JSON.stringify(fixture)}));const button=row?.querySelector('button');button?.click();return Boolean(button);})()`); assert(opened, 'Audit detail button is missing.'); await delay(800); console.log(`Audit browser: detail attempt ${JSON.stringify(await evaluate(cdp, '({body:document.body.innerText.slice(0,1000),dialog:!!document.querySelector("[role=dialog]")})'))}`); await waitFor(cdp, "!!document.querySelector('[role=dialog][aria-modal=true]')"); state = JSON.parse(await evaluate(cdp, 'JSON.stringify({body:document.body.innerText.slice(0,12000),dialog:!!document.querySelector("[role=dialog]")})')); assert(state.body.includes('[REDACTED]') && !state.body.includes(secret), 'Audit detail exposed a secret or failed redaction.'); await evaluate(cdp, "document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))"); await waitFor(cdp, "!document.querySelector('[role=dialog][aria-modal=true]')");
    await evaluate(cdp, `(function(){const input=document.querySelector('input[placeholder*="Cari"]');const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;set.call(input,'');input.dispatchEvent(new Event('input',{bubbles:true}));})()`); await waitFor(cdp, "document.querySelectorAll('button[aria-label=\"Halaman berikutnya\"]').length === 1");
    await cdp.send('Emulation.setDeviceMetricsOverride', { width: 375, height: 800, deviceScaleFactor: 1, mobile: true }); await delay(150); state = JSON.parse(await evaluate(cdp, 'JSON.stringify({scrollWidth:document.documentElement.scrollWidth,viewport:innerWidth})')); assert(state.scrollWidth <= state.viewport + 1, 'Audit page has horizontal mobile overflow.');
    await evaluate(cdp, `localStorage.setItem('token',${JSON.stringify(tokenFor({ id: viewId, organization_id: 1, username: viewUsername }))});location.reload()`); await waitFor(cdp, "document.querySelector('main h1')?.textContent?.includes('Log Audit')"); state = JSON.parse(await evaluate(cdp, "JSON.stringify({buttons:[...document.querySelectorAll('button')].map(x=>x.textContent).filter(Boolean),sidebar:[...document.querySelectorAll('a')].map(x=>x.textContent).filter(Boolean)})")); assert(!state.buttons.some(text => text.includes('CSV') || text.includes('Excel')), 'Export controls leaked without reports.export.'); assert(state.sidebar.some(text => text.includes('Log Audit')), 'Audit sidebar item is hidden for a user with audit.read.');
    await evaluate(cdp, `localStorage.setItem('token',${JSON.stringify(tokenFor({ id: deniedId, organization_id: 1, username: deniedUsername }))});location.reload()`); await waitFor(cdp, "document.body.innerText.includes('Akses Ditolak')"); state = JSON.parse(await evaluate(cdp, "JSON.stringify({sidebar:[...document.querySelectorAll('a')].map(x=>x.textContent).filter(Boolean),errors:window.__auditErrors||[]})")); assert(!state.sidebar.some(text => text.includes('Log Audit')), 'Audit sidebar item is visible without audit.read.'); assert(!state.errors.length, `Browser errors after authorization checks: ${state.errors.join('; ')}`);
    cdp.socket.close(); console.log('Audit browser acceptance: PASS');
  } finally {
    if (child) child.kill(); if (profile) { await delay(300); await rm(profile, { recursive: true, force: true, maxRetries: 3, retryDelay: 150 }); }
    if (userIds.length) { const slots = userIds.map(() => '?').join(','); await db.execute(`DELETE FROM audit_logs WHERE user_id IN (${slots})`, userIds); await db.execute(`DELETE FROM user_presence_sessions WHERE user_id IN (${slots})`, userIds); await db.execute(`DELETE FROM user_business_units WHERE user_id IN (${slots})`, userIds); await db.execute(`DELETE FROM user_roles WHERE user_id IN (${slots})`, userIds); await db.execute(`DELETE FROM users WHERE id IN (${slots})`, userIds); }
    if (roleId) { await db.execute('DELETE FROM role_permissions WHERE role_id=?', [roleId]); await db.execute('DELETE FROM roles WHERE id=?', [roleId]); }
    if (viewRoleId) { await db.execute('DELETE FROM role_permissions WHERE role_id=?', [viewRoleId]); await db.execute('DELETE FROM roles WHERE id=?', [viewRoleId]); }
    await db.end();
  }
}
run().catch(error => { console.error('Audit browser acceptance: FAIL', error); process.exitCode = 1; });
