import { pool } from '../src/config/database';
import { documentRegistryService, type SourceDocumentInput } from '../src/shared/documents/document-registry.service';

const apply = process.argv.includes('--apply');
type Candidate = SourceDocumentInput;
const candidates: Candidate[] = [];
const add = (rows: any[], sourceModuleCode: string, documentType: string, entityType: string, title: (row: any) => string) => rows.forEach(row => candidates.push({ organizationId:Number(row.organization_id), businessUnitId:Number(row.business_unit_id), sourceModuleCode, documentType, title:title(row), fileName:row.file_name, storagePath:row.storage_path, mimeType:row.mime_type, fileSizeBytes:row.file_size_bytes == null ? null : Number(row.file_size_bytes), entityType, entityId:Number(row.entity_id), entityCode:row.entity_code || null, uploadedBy:row.uploaded_by == null ? null : Number(row.uploaded_by) }));

async function main() {
  // Read-only discovery; --apply only registers metadata for existing physical source keys.
  const [attachments]: any = await pool.execute(`SELECT bu.organization_id,o.business_unit_id,a.id entity_id,o.order_code entity_code,a.file_name,a.file_type mime_type,a.file_size_bytes,a.storage_path,a.uploaded_by FROM order_attachments a JOIN craft_orders o ON o.id=a.order_id JOIN business_units bu ON bu.id=o.business_unit_id WHERE o.deleted_at IS NULL AND a.storage_path IS NOT NULL`); add(attachments,'craft_orders','attachment','order_attachment',row=>`Lampiran pesanan ${row.entity_code}`);
  const [deliverables]: any = await pool.execute(`SELECT bu.organization_id,p.business_unit_id,pd.id entity_id,p.project_code entity_code,pd.title file_name,NULL mime_type,NULL file_size_bytes,pd.storage_path,NULL uploaded_by FROM project_deliverables pd JOIN studio_projects p ON p.id=pd.project_id JOIN business_units bu ON bu.id=p.business_unit_id WHERE p.deleted_at IS NULL AND pd.storage_path IS NOT NULL`); add(deliverables,'studio_projects','deliverable','project_deliverable',row=>row.file_name);
  const [supplierInvoices]: any = await pool.execute(`SELECT bu.organization_id,si.business_unit_id,si.id entity_id,si.supplier_invoice_number entity_code,CONCAT('supplier-invoice-',si.id) file_name,NULL mime_type,NULL file_size_bytes,si.document_path storage_path,NULL uploaded_by FROM supplier_invoices si JOIN business_units bu ON bu.id=si.business_unit_id WHERE si.document_path IS NOT NULL`); add(supplierInvoices,'craft_procurement','invoice','supplier_invoice',row=>`Tagihan pemasok ${row.entity_code}`);
  const [receipts]: any = await pool.execute(`SELECT e.organization_id,e.business_unit_id,e.id entity_id,e.expense_code entity_code,CONCAT('expense-receipt-',e.id) file_name,NULL mime_type,NULL file_size_bytes,e.receipt_path storage_path,e.created_by uploaded_by FROM expenses e WHERE e.receipt_path IS NOT NULL`); add(receipts,'studio_finance','receipt','expense',row=>`Bukti pengeluaran ${row.entity_code}`);
  const [exports]: any = await pool.execute(`SELECT organization_id,business_unit_id,id entity_id,CONCAT(report_name,':',export_format) entity_code,CONCAT('report-',id,'.',export_format) file_name,NULL mime_type,NULL file_size_bytes,storage_path,generated_by uploaded_by,report_name FROM report_exports WHERE storage_path IS NOT NULL`); add(exports,'studio_analytics','report','report_export',row=>row.report_name);
  const [billing]: any = await pool.execute(`SELECT organization_id,business_unit_id,id entity_id,document_code entity_code,file_name,mime_type,file_size_bytes,storage_path,uploaded_by,document_type,title FROM documents WHERE document_type IN ('quotation','invoice') AND storage_path IS NOT NULL AND (source_module_code='studio_billing' OR source_module_code IS NULL)`); billing.forEach((row:any)=>candidates.push({organizationId:Number(row.organization_id),businessUnitId:Number(row.business_unit_id),sourceModuleCode:'studio_billing',documentType:row.document_type,title:row.title,fileName:row.file_name,storagePath:row.storage_path,mimeType:row.mime_type,fileSizeBytes:row.file_size_bytes == null?null:Number(row.file_size_bytes),entityType:row.document_type,entityId:Number(row.entity_id),entityCode:row.entity_code||row.document_code,uploadedBy:row.uploaded_by == null?null:Number(row.uploaded_by)}));
  console.log(`Document registry reconciliation: ${apply ? 'APPLY' : 'DRY RUN'}; ${candidates.length} source files discovered.`);
  if (!apply) { for (const item of candidates) console.log(`would register ${item.sourceModuleCode}:${item.entityType}#${item.entityId} -> ${item.storagePath}`); return; }
  const connection=await pool.getConnection(); let done=0; try { await connection.beginTransaction(); for(const item of candidates){await documentRegistryService.registerSourceDocument(item,connection);done++;} await connection.commit(); console.log(`registered/updated ${done} metadata records; no physical file was copied, moved, or deleted.`); } catch(error){await connection.rollback();throw error;} finally{connection.release();}
}
main().catch(error=>{console.error('Document registry reconciliation failed:',error);process.exitCode=1;}).finally(()=>pool.end());
