import assert from 'node:assert/strict';
import { createHmac, randomUUID } from 'node:crypto';
import { createServer, type Server } from 'node:http';
import app from '../src/app';
import { pool } from '../src/config/database';
import { env } from '../src/config/env';
import { calendarRegistry } from '../src/shared/calendar/calendar-registry.service';
import { calendarReminderService } from '../src/shared/calendar/calendar-reminder.service';
import { tasksService } from '../src/modules/tasks/tasks.service';

type FixtureUser = { id: number; username: string; organizationId: number };
const tokenFor = (user: FixtureUser) => { const now = Math.floor(Date.now() / 1000); const header = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url'); const payload = Buffer.from(JSON.stringify({ id: user.id, organization_id: user.organizationId, username: user.username, iat: now, exp: now + 600 })).toString('base64url'); return `${header}.${payload}.${createHmac('sha256', env.JWT_SECRET).update(`${header}.${payload}`).digest('base64url')}`; };

async function main() {
  const suffix = randomUUID().slice(0, 10); const userIds: number[] = []; const eventIds: number[] = []; const taskIds: number[] = []; let roleId = 0; let limitedRoleId = 0; let server: Server | undefined;
  const [units]: any = await pool.execute(`SELECT id,organization_id,code FROM business_units WHERE code IN ('CRAFT','STUDIO') AND is_active=1 ORDER BY code`); const craft = units.find((row: any) => row.code === 'CRAFT'); const studio = units.find((row: any) => row.code === 'STUDIO'); assert(craft && studio, 'Active Craft and Studio workspaces are required.');
  const permissionCodes = ['calendar.read','calendar.write','calendar.manage','tasks.read','tasks.write','tasks.manage','craft.orders.read'];
  const [permissions]: any = await pool.execute(`SELECT id,code FROM permissions WHERE code IN (${permissionCodes.map(() => '?').join(',')})`, permissionCodes); assert.equal(permissions.length, permissionCodes.length, 'Calendar/Task permissions must already be reconciled manually.');
  const permission = new Map<string, number>(permissions.map((row: any) => [row.code, Number(row.id)]));
  const createUser = async (label: string): Promise<FixtureUser> => { const username = `smokecal_${label}_${suffix}`; const [result]: any = await pool.execute(`INSERT INTO users (organization_id,full_name,username,email,password_hash,status_code,approval_status_code,registration_source,default_workspace_code,approval_requested_at) VALUES (?,?,?,?,?,'active','approved','legacy','craft',UTC_TIMESTAMP(3))`, [Number(craft.organization_id), `Smoke calendar ${label}`, username, `${username}@example.invalid`, '$2b$10$fixturehashonlyneverused']); const user = { id: Number(result.insertId), username, organizationId: Number(craft.organization_id) }; userIds.push(user.id); return user; };
  const request = async (token: string, path: string, method = 'GET', body?: any) => { const response = await fetch(`http://127.0.0.1:${(server!.address() as any).port}/api/v1${path}`, { method, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) }); return { response, json: await response.json() as any }; };
  try {
    const [role]: any = await pool.execute(`INSERT INTO roles (organization_id,code,name,scope_code,is_system,is_active) VALUES (?,?,?,'global',0,1)`, [Number(craft.organization_id), `SMOKE_CAL_${suffix}`.toUpperCase(), `Smoke Calendar ${suffix}`]); roleId = Number(role.insertId); for (const code of permissionCodes) await pool.execute('INSERT INTO role_permissions (role_id,permission_id) VALUES (?,?)', [roleId, permission.get(code)]);
    const owner = await createUser('owner'); const attendee = await createUser('attendee'); const limited = await createUser('limited');
    for (const user of [owner, attendee]) { await pool.execute('INSERT INTO user_roles (user_id,role_id) VALUES (?,?)', [user.id, roleId]); for (const unit of [craft, studio]) await pool.execute('INSERT INTO user_business_units (user_id,business_unit_id,can_access) VALUES (?,?,1)', [user.id, Number(unit.id)]); }
    // The limited user has Calendar, but cannot read Craft sources or Tasks.
    const [limitedRole]: any = await pool.execute(`INSERT INTO roles (organization_id,code,name,scope_code,is_system,is_active) VALUES (?,?,?,'global',0,1)`, [Number(craft.organization_id), `SMOKE_CAL_LIMIT_${suffix}`.toUpperCase(), `Smoke Calendar limited ${suffix}`]); limitedRoleId = Number(limitedRole.insertId); await pool.execute('INSERT INTO role_permissions (role_id,permission_id) VALUES (?,?)', [limitedRoleId, permission.get('calendar.read')]); await pool.execute('INSERT INTO user_roles (user_id,role_id) VALUES (?,?)', [limited.id, limitedRoleId]); await pool.execute('INSERT INTO user_business_units (user_id,business_unit_id,can_access) VALUES (?,?,1)', [limited.id, Number(craft.id)]);
    server = createServer(app); await new Promise<void>(resolve => server!.listen(0, '127.0.0.1', resolve)); const ownerToken = tokenFor(owner); const attendeeToken = tokenFor(attendee); const limitedToken = tokenFor(limited);
    const deniedTasks = await request(limitedToken, '/tasks'); assert.equal(deniedTasks.response.status, 403, 'tasks.read is not enforced');
    const globalDenied = await request(ownerToken, '/calendar/events', 'POST', { title: `Global denied ${suffix}`, all_day: true, start_date: '2026-09-02' }); assert.equal(globalDenied.response.status, 201, 'manager fixture should create a global event'); eventIds.push(Number(globalDenied.json.data.id));
    const start = '2026-09-03T09:00:00+07:00'; const end = '2026-09-03T10:00:00+07:00'; const created = await request(ownerToken, '/calendar/events', 'POST', { title: `Acara API ${suffix}`, description: 'Fixture functional', business_unit_id: Number(craft.id), event_type: 'meeting', all_day: false, start_at: start, end_at: end, reminder_minutes_before: 15, attendee_ids: [attendee.id] }); assert.equal(created.response.status, 201, JSON.stringify(created.json)); const event = created.json.data; eventIds.push(Number(event.id)); assert.match(event.event_code, /^EVT-\d{6,}$/); assert.equal(new Date(event.start_at).toISOString(), '2026-09-03T02:00:00.000Z', 'timed event is not stored in UTC');
    const allDay = await request(ownerToken, '/calendar/events', 'POST', { title: `Seharian ${suffix}`, business_unit_id: Number(craft.id), all_day: true, start_date: '2026-09-04', end_date: '2026-09-05' }); assert.equal(allDay.response.status, 201); eventIds.push(Number(allDay.json.data.id)); assert.equal(new Date(allDay.json.data.start_at).toISOString(), '2026-09-03T17:00:00.000Z'); assert.equal(new Date(allDay.json.data.end_at).toISOString(), '2026-09-05T17:00:00.000Z');
    const invalidRange = await request(ownerToken, '/calendar/events', 'POST', { title: `Invalid ${suffix}`, business_unit_id: Number(craft.id), all_day: false, start_at: end, end_at: start }); assert.equal(invalidRange.response.status, 400, 'invalid event range accepted');
    const rsvp = await request(attendeeToken, `/calendar/events/${event.id}/response`, 'PATCH', { response_status_code: 'accepted' }); assert.equal(rsvp.response.status, 200); assert.equal(rsvp.json.data.attendees.find((row: any) => row.id === attendee.id).response_status, 'accepted');
    const task = await request(ownerToken, '/tasks', 'POST', { title: `Tugas API ${suffix}`, business_unit_id: Number(craft.id), priority_code: 'high', start_at: '2026-09-03T08:00:00+07:00', due_at: '2026-09-03T11:00:00+07:00', reminder_minutes_before: 15, assignee_ids: [attendee.id] }); assert.equal(task.response.status, 201, JSON.stringify(task.json)); taskIds.push(Number(task.json.data.id)); assert.match(task.json.data.task_code, /^TSK-\d{6,}$/); const taskStatus = await request(attendeeToken, `/tasks/${task.json.data.id}/status`, 'PATCH', { status_code: 'in_progress' }); assert.equal(taskStatus.response.status, 200); const taskDone = await request(attendeeToken, `/tasks/${task.json.data.id}/status`, 'PATCH', { status_code: 'done' }); assert.equal(taskDone.response.status, 200); assert(taskDone.json.data.completed_at, 'completed_at was not set');
    const eventUpdate = await request(ownerToken, `/calendar/events/${event.id}`, 'PATCH', { location_name: 'Ruang smoke' }); assert.equal(eventUpdate.response.status, 200); assert.equal(eventUpdate.json.data.location, 'Ruang smoke'); const attendeeUpdate = await request(ownerToken, `/calendar/events/${event.id}/attendees`, 'PUT', { attendee_ids: [attendee.id] }); assert.equal(attendeeUpdate.response.status, 200);
    const taskUpdate = await request(ownerToken, `/tasks/${task.json.data.id}`, 'PATCH', { title: `Tugas API diperbarui ${suffix}` }); assert.equal(taskUpdate.response.status, 200); assert.equal(taskUpdate.json.data.title, `Tugas API diperbarui ${suffix}`); const assigneeUpdate = await request(ownerToken, `/tasks/${task.json.data.id}/assignees`, 'PUT', { assignee_ids: [attendee.id] }); assert.equal(assigneeUpdate.response.status, 200);
    const generatedInput = { organizationId: owner.organizationId, businessUnitId: Number(craft.id), title: `Automated ${suffix}`, sourceModuleCode: 'craft_orders', sourceType: 'craft_order', sourceId: 987654321, sourceCode: 'SMOKE', sourceKey: `smoke:automation:${suffix}`, actorId: owner.id }; const generatedOne = await tasksService.createGenerated(generatedInput); const generatedTwo = await tasksService.createGenerated(generatedInput); assert.equal(generatedOne.id, generatedTwo.id, 'automation task retry created a duplicate'); taskIds.push(generatedOne.id);
    const sourceTaskUpdate = await request(ownerToken, `/tasks/${generatedOne.id}`, 'PATCH', { title: 'Tidak boleh diubah' }); assert.equal(sourceTaskUpdate.response.status, 409, 'source-owned task was editable');
    await calendarRegistry.upsertSourceEvent({ organizationId: owner.organizationId, businessUnitId: Number(craft.id), sourceKey: `smoke:source:${suffix}`, sourceModuleCode: 'craft_orders', sourceType: 'craft_order', sourceId: 987654322, sourceCode: 'SMOKE', title: `Source ${suffix}`, eventType: 'order_deadline', startAt: start }); await calendarRegistry.upsertSourceEvent({ organizationId: owner.organizationId, businessUnitId: Number(craft.id), sourceKey: `smoke:source:${suffix}`, sourceModuleCode: 'craft_orders', sourceType: 'craft_order', sourceId: 987654322, sourceCode: 'SMOKE', title: `Source updated ${suffix}`, eventType: 'order_deadline', startAt: end }); const [sourceRows]: any = await pool.execute('SELECT id,title FROM calendar_events WHERE organization_id=? AND source_key=?', [owner.organizationId, `smoke:source:${suffix}`]); assert.equal(sourceRows.length, 1, 'source projection is not idempotent'); assert.equal(sourceRows[0].title, `Source updated ${suffix}`); eventIds.push(Number(sourceRows[0].id));
    const ownerFeed = await request(ownerToken, '/calendar/feed?from=2026-09-01&to=2026-09-10&include_tasks=true'); assert.equal(ownerFeed.response.status, 200, JSON.stringify(ownerFeed.json)); assert(ownerFeed.json.data.items.some((item: any) => item.kind === 'task' && Number(item.id) === Number(task.json.data.id)), 'task overlay is missing from calendar feed'); const limitedFeed = await request(limitedToken, '/calendar/feed?from=2026-09-01&to=2026-09-10&include_tasks=true'); assert.equal(limitedFeed.response.status, 200, JSON.stringify(limitedFeed.json)); assert(!limitedFeed.json.data.items.some((item: any) => item.source?.key === `smoke:source:${suffix}`), 'calendar feed bypassed source permission');
    const reminderEvent = await request(ownerToken, '/calendar/events', 'POST', { title: `Reminder ${suffix}`, business_unit_id: Number(craft.id), all_day: false, start_at: new Date(Date.now() + 20_000).toISOString(), reminder_minutes_before: 1, attendee_ids: [attendee.id] }); assert.equal(reminderEvent.response.status, 201); eventIds.push(Number(reminderEvent.json.data.id)); await calendarReminderService.runOnce(); await calendarReminderService.runOnce(); const [reminders]: any = await pool.execute(`SELECT COUNT(*) AS count FROM notifications WHERE title='Pengingat acara' AND entity_id=?`, [Number(reminderEvent.json.data.id)]); assert.equal(Number(reminders[0].count), 1, 'event reminder dedupe failed');
    console.log('Calendar & Tasks smoke: PASS');
  } finally {
    if (server) await new Promise<void>(resolve => server!.close(() => resolve()));
    if (eventIds.length) { const keys = eventIds.map(() => '?').join(','); await pool.execute(`DELETE FROM notifications WHERE entity_type='calendar_event' AND entity_id IN (${keys})`, eventIds); await pool.execute(`DELETE FROM audit_logs WHERE entity_type='calendar_event' AND entity_id IN (${keys})`, eventIds); await pool.execute(`DELETE FROM calendar_events WHERE id IN (${keys})`, eventIds); }
    if (taskIds.length) { const keys = taskIds.map(() => '?').join(','); await pool.execute(`DELETE FROM notifications WHERE entity_type='task' AND entity_id IN (${keys})`, taskIds); await pool.execute(`DELETE FROM audit_logs WHERE entity_type='task' AND entity_id IN (${keys})`, taskIds); await pool.execute(`DELETE FROM task_assignees WHERE task_id IN (${keys})`, taskIds); await pool.execute(`DELETE FROM tasks WHERE id IN (${keys})`, taskIds); }
    if (userIds.length) { const keys = userIds.map(() => '?').join(','); await pool.execute(`DELETE FROM notifications WHERE user_id IN (${keys})`, userIds); await pool.execute(`DELETE FROM user_business_units WHERE user_id IN (${keys})`, userIds); await pool.execute(`DELETE FROM user_roles WHERE user_id IN (${keys})`, userIds); await pool.execute(`DELETE FROM users WHERE id IN (${keys})`, userIds); }
    for (const id of [roleId, limitedRoleId].filter(Boolean)) { await pool.execute('DELETE FROM role_permissions WHERE role_id=?', [id]); await pool.execute('DELETE FROM roles WHERE id=?', [id]); }
    await pool.end();
  }
}
main().catch(error => { console.error('Calendar & Tasks smoke: FAIL', error); process.exitCode = 1; });
