import { randomBytes } from 'node:crypto';
import { pool } from '../src/config/database';
import { studioVendorsService } from '../src/modules/studio-vendors/studio-vendors.service';
import { getStudioBusinessUnit } from '../src/modules/studio-projects/studio-projects.helpers';
import { studioClientService } from '../src/shared/party/studio-client.service';

const assert: (value: unknown, message: string) => asserts value = (value, message) => { if (!value) throw new Error(message); };
const suffix = randomBytes(4).toString('hex').toUpperCase();
async function actor() { const [rows]: any = await pool.execute(`SELECT DISTINCT u.id FROM users u JOIN user_roles ur ON ur.user_id = u.id JOIN role_permissions rp ON rp.role_id = ur.role_id JOIN permissions p ON p.id = rp.permission_id WHERE u.deleted_at IS NULL AND u.status_code = 'active' AND u.approval_status_code = 'approved' AND p.code = 'studio.vendors.write' LIMIT 1`); assert(rows.length, 'No active user has studio.vendors.write.'); return Number(rows[0].id); }
async function run() {
  const studio = await getStudioBusinessUnit(); const userId = await actor(); let externalId = 0; let clientId = 0; let projectId = 0; let assetId = 0;
  try {
    const created = await studioVendorsService.create({ display_name: `Vendor Smoke ${suffix}`, party_kind: 'company', email: `vendor-${suffix.toLowerCase()}@example.test`, roles: ['vendor', 'freelancer'], contacts: [], confirm_duplicate: false }, userId, studio);
    externalId = created.id; assert(created.code === `EXT-${String(externalId).padStart(6, '0')}`, 'External Party did not use safe EXT-{ID} generation.');
    const detail = await studioVendorsService.detail(externalId, studio); assert(detail.roles.length === 2 && detail.roles.every(role => role.is_active), 'Multi-role Party was not created.');
    await studioVendorsService.createContact(externalId, { full_name: 'Contact One' }, userId, studio); const second = await studioVendorsService.createContact(externalId, { full_name: 'Contact Two', is_primary: true }, userId, studio); const contacts = await studioVendorsService.contacts(externalId, studio); assert(contacts.filter(contact => contact.is_primary).length === 1 && contacts.some(contact => contact.id === second.id && contact.is_primary), 'Primary-contact enforcement failed.');
    const connection = await pool.getConnection();
    try { await connection.beginTransaction(); const client = await studioClientService.createStudioClient(connection, { display_name: `Client Vendor Smoke ${suffix}`, party_kind: 'company', email: `client-${suffix.toLowerCase()}@example.test` }, studio); clientId = client.id; const [project]: any = await connection.execute(`INSERT INTO studio_projects (business_unit_id, project_code, client_party_id, project_name, status_code, priority_code, currency_code, contract_value) VALUES (?, ?, ?, ?, 'approved', 'normal', 'IDR', 0)`, [studio.id, `SMK-VND-${suffix}`, clientId, `Vendor Smoke Project ${suffix}`]); projectId = Number(project.insertId); const [asset]: any = await connection.execute(`INSERT INTO assets (business_unit_id, asset_code, name, category, status_code) VALUES (?, ?, ?, 'Camera', 'available')`, [studio.id, `SMK-AST-${suffix}`, `Vendor Smoke Asset ${suffix}`]); assetId = Number(asset.insertId); await connection.commit(); } catch (error) { await connection.rollback(); throw error; } finally { connection.release(); }
    const assignment = await studioVendorsService.addAssignment(externalId, { project_id: projectId, assignment_role: 'freelancer', scope_description: 'Video editing', agreed_fee: 2_000_000, start_date: '2026-08-01' }, userId, studio); const assignments = await studioVendorsService.assignments(externalId, studio); assert(assignments.some(row => row.id === assignment.id && row.agreed_fee === 2_000_000), 'Canonical project assignment was not visible from Vendor detail.');
    await studioVendorsService.updateAssignment(externalId, assignment.id, { scope_description: 'Video editing final', agreed_fee: 2_100_000 }, userId, studio); await studioVendorsService.endAssignment(externalId, assignment.id, '2026-08-02', userId, studio);
    await pool.execute(`INSERT INTO expenses (organization_id, business_unit_id, expense_code, party_id, studio_project_id, expense_date, description, amount, status_code) VALUES (?, ?, ?, ?, ?, UTC_TIMESTAMP(3), ?, ?, 'approved')`, [studio.organizationId, studio.id, `SMK-EXP-${suffix}`, externalId, projectId, 'Fixture recorded expense', 1_000_000]); await pool.execute(`INSERT INTO asset_maintenance_records (asset_id, maintenance_type, performed_at, performed_by_party_id, cost, notes) VALUES (?, 'Cleaning', UTC_TIMESTAMP(3), ?, 250000, 'Fixture maintenance')`, [assetId, externalId]);
    const commercial = await studioVendorsService.commercial(externalId, studio); const maintenance = await studioVendorsService.maintenance(externalId, studio); assert(commercial.total_agreed_fee === 2_100_000 && commercial.recorded_expenses === 1_000_000, 'Agreed fee and recorded expense were not kept distinct.'); assert(maintenance.some(record => record.asset_id === assetId), 'Maintenance-provider history was not visible.');
    await studioVendorsService.deactivateRole(externalId, 'vendor', null, false, userId, studio); const afterDeactivate = await studioVendorsService.detail(externalId, studio); assert(!afterDeactivate.roles.find(role => role.role_code === 'vendor')?.is_active && afterDeactivate.roles.find(role => role.role_code === 'freelancer')?.is_active, 'Deactivating Vendor changed another external role.'); await studioVendorsService.activateRole(externalId, 'vendor', userId, studio);
    await studioVendorsService.create({ display_name: 'Ignored on adoption', party_kind: 'individual', roles: ['studio_partner'], contacts: [], use_existing_party_id: clientId, confirm_duplicate: false }, userId, studio); const adopted = await studioVendorsService.detail(clientId, studio); assert(adopted.party.code.startsWith('CLI-') && adopted.roles.some(role => role.role_code === 'studio_partner'), 'Existing Party adoption changed its original code or did not preserve its role.');
    console.log('Studio Vendors smoke test passed.');
  } finally {
    const connection = await pool.getConnection();
    try { await connection.beginTransaction(); if (externalId) { await connection.execute('DELETE FROM expenses WHERE party_id = ?', [externalId]); await connection.execute('DELETE FROM asset_maintenance_records WHERE performed_by_party_id = ?', [externalId]); await connection.execute('DELETE FROM project_external_assignments WHERE party_id = ?', [externalId]); await connection.execute(`DELETE FROM audit_logs WHERE module_code = 'studio_vendors' AND entity_type = 'party' AND entity_id = ?`, [externalId]); await connection.execute(`DELETE FROM domain_events WHERE module_code = 'studio_vendors' AND entity_type = 'party' AND entity_id = ?`, [externalId]); await connection.execute('DELETE FROM party_contacts WHERE party_id = ?', [externalId]); await connection.execute('DELETE FROM party_roles WHERE party_id = ?', [externalId]); await connection.execute('DELETE FROM parties WHERE id = ?', [externalId]); } if (assetId) await connection.execute('DELETE FROM assets WHERE id = ?', [assetId]); if (projectId) await connection.execute('DELETE FROM studio_projects WHERE id = ?', [projectId]); if (clientId) { await connection.execute('DELETE FROM party_roles WHERE party_id = ?', [clientId]); await connection.execute('DELETE FROM parties WHERE id = ?', [clientId]); } await connection.commit(); } catch (error) { await connection.rollback(); throw error; } finally { connection.release(); }
  }
}
run().then(() => pool.end()).catch(async error => { console.error(error); await pool.end(); process.exit(1); });
