import React from 'react';
import { Download, Filter, Plus, Search, Users } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Badge } from '../../../components/ui/Badge';
import { Button } from '../../../components/ui/Button';
import { Card } from '../../../components/ui/Card';
import { useAuth } from '../../../context/AuthContext';
import { formatCurrency } from '../../../lib/utils';
import { studioVendorsApi } from '../../../services/api/studio-vendors.api';
import type { StudioExternalRole, StudioVendorFilters, StudioVendorsOverview } from '../../../types/studio-vendors';

const labels: Record<StudioExternalRole, string> = { vendor: 'Vendor', freelancer: 'Freelancer', studio_partner: 'Mitra Studio' };
const titleFor = (role?: StudioExternalRole, assignments?: boolean) => assignments ? 'Penugasan Eksternal' : role ? labels[role] : 'Vendor / Freelancer / Mitra';
export function VendorsDirectoryPage({ role, assignmentsView }: { role?: StudioExternalRole; assignmentsView?: boolean }) {
  const navigate = useNavigate(); const { hasPermission } = useAuth(); const canWrite = hasPermission('studio.vendors.write');
  const [search, setSearch] = React.useState(''); const [filters, setFilters] = React.useState<StudioVendorFilters>({ role, sort_by: assignmentsView ? 'active_assignments' : 'name', sort_order: assignmentsView ? 'desc' : 'asc' });
  const [data, setData] = React.useState<Awaited<ReturnType<typeof studioVendorsApi.list>> | null>(null); const [summary, setSummary] = React.useState<StudioVendorsOverview | null>(null); const [error, setError] = React.useState<string | null>(null); const [loading, setLoading] = React.useState(true);
  const load = React.useCallback(async () => { setLoading(true); try { const result = await studioVendorsApi.list({ ...filters, role, search: search || undefined }); setData(result); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Gagal memuat direktori.'); } finally { setLoading(false); } }, [filters, role, search]);
  React.useEffect(() => { void studioVendorsApi.summary().then(setSummary).catch(cause => setError(cause instanceof Error ? cause.message : 'Gagal memuat ringkasan.')); }, []); React.useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer); }, [load]);
  const exportCsv = async () => { try { await studioVendorsApi.export({ ...filters, role, search: search || undefined }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Gagal mengekspor data.'); } };
  return <div className="space-y-6 pb-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--nexus-yellow-deep)]">Uni-Inside Studio · Bisnis</p><h1 className="mt-1 text-2xl font-bold text-[var(--nexus-charcoal)]">{titleFor(role, assignmentsView)}</h1><p className="mt-1 text-sm text-[var(--nexus-muted)]">Direktori relasi pihak eksternal, kontak, penugasan proyek, dan komitmen biaya.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => void exportCsv()}><Download className="h-4 w-4" /> Ekspor CSV</Button>{canWrite && <Button onClick={() => navigate('/app/studio/vendors/new')}><Plus className="h-4 w-4" /> Tambah Pihak</Button>}</div></div>
    {error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="Pihak Aktif" value={summary?.active_parties ?? '—'} /><Kpi label="Vendor" value={summary?.vendors ?? '—'} /><Kpi label="Freelancer" value={summary?.freelancers ?? '—'} /><Kpi label="Mitra Studio" value={summary?.studio_partners ?? '—'} /><Kpi label="Komitmen Fee" value={summary ? formatCurrency(summary.total_agreed_fee) : '—'} /></div>
    <Card><div className="space-y-4 p-5"><div className="flex flex-col gap-3 md:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-[var(--nexus-muted)]" /><input className="studio-input pl-9" placeholder="Cari kode, nama, email, telepon, atau kontak..." value={search} onChange={event => setSearch(event.target.value)} /></label><select className="studio-input md:w-52" value={filters.relationship_status || ''} onChange={event => setFilters(value => ({ ...value, relationship_status: event.target.value as StudioVendorFilters['relationship_status'] || undefined }))}><option value="">Semua status</option><option value="active">Hubungan aktif</option><option value="role_inactive">Peran nonaktif</option><option value="party_inactive">Party global nonaktif</option></select><Button variant="outline" onClick={() => setFilters(value => ({ ...value, has_active_assignment: !value.has_active_assignment }))}><Filter className="h-4 w-4" /> {filters.has_active_assignment ? 'Semua' : 'Penugasan aktif'}</Button></div>
      {loading ? <p className="py-12 text-center text-sm text-[var(--nexus-muted)]">Memuat direktori...</p> : data?.items.length ? <div className="overflow-x-auto"><table className="w-full min-w-[940px] text-sm"><thead className="studio-table-head"><tr><th>Pihak</th><th>Peran</th><th>Kontak Utama</th><th>Penugasan</th><th className="text-right">Proyek</th><th className="text-right">Agreed Fee</th><th className="text-right">Recorded Expense</th><th>Status</th></tr></thead><tbody>{data.items.map(item => <tr key={item.id} className="studio-table-row cursor-pointer" onClick={() => navigate(`/app/studio/vendors/${item.id}`)}><td><p className="font-semibold text-[var(--nexus-charcoal)]">{item.display_name}</p><p className="studio-code">{item.code} · {item.city || '—'}</p></td><td><div className="flex flex-wrap gap-1">{item.managed_roles.map(value => <Badge key={value} variant="info">{labels[value]}</Badge>)}</div></td><td>{item.primary_contact_name || item.email || item.phone || '—'}</td><td>{item.active_assignment_count} aktif</td><td className="text-right">{item.total_project_count}</td><td className="text-right font-semibold">{formatCurrency(item.total_agreed_fee)}</td><td className="text-right">{formatCurrency(item.recorded_expenses)}</td><td><Badge variant={item.relationship_status === 'active' ? 'success' : item.relationship_status === 'party_inactive' ? 'error' : 'warning'}>{item.relationship_status === 'active' ? 'Aktif' : item.relationship_status === 'party_inactive' ? 'Party nonaktif' : 'Peran nonaktif'}</Badge></td></tr>)}</tbody></table></div> : <div className="py-12 text-center"><Users className="mx-auto h-8 w-8 text-[var(--nexus-muted)]" /><p className="mt-3 font-semibold text-[var(--nexus-charcoal)]">Belum ada pihak eksternal</p><p className="mt-1 text-sm text-[var(--nexus-muted)]">Tambahkan Vendor, Freelancer, atau Mitra Studio untuk memulai.</p></div>}</div></Card></div>;
}
function Kpi({ label, value }: { label: string; value: string | number }) { return <div className="studio-kpi"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[var(--nexus-muted)]">{label}</p><p className="mt-1 text-xl font-bold text-[var(--nexus-charcoal)]">{value}</p></div>; }
