import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Navigate, Link, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { Activity, AlertTriangle, CheckCircle2, Clock3, FileClock, FlaskConical, Pause, Play, Plus, RefreshCw, ShieldCheck, Workflow, Zap } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { studioAutomationsApi } from '../../services/api/studio-automations.api';
import type { AutomationCatalog, AutomationOverview, AutomationRule, AutomationRun, AutomationTemplate, DomainEventSummary } from '../../types/studio-automations';

const input = 'w-full rounded-lg border border-[var(--nexus-border)] bg-white px-3 py-2 text-sm outline-none focus:border-[var(--nexus-yellow-deep)]';
const status = (value: string) => ({ active: 'bg-emerald-100 text-emerald-800', success: 'bg-emerald-100 text-emerald-800', failed: 'bg-red-100 text-red-800', disabled: 'bg-red-100 text-red-800', paused: 'bg-amber-100 text-amber-800', skipped: 'bg-amber-100 text-amber-800', queued: 'bg-sky-100 text-sky-800', running: 'bg-sky-100 text-sky-800' }[value] || 'bg-slate-100 text-slate-700');
const label = (value: string) => ({ draft: 'Draf', active: 'Aktif', paused: 'Dijeda', disabled: 'Dinonaktifkan', queued: 'Antrean', running: 'Berjalan', success: 'Berhasil', failed: 'Gagal', skipped: 'Dilewati' }[value] || value);
const date = (value?: string | null) => value ? new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';
const errorText = (error: unknown) => error instanceof Error ? error.message : 'Operasi tidak dapat diselesaikan.';
const Pill = ({ value }: { value: string }) => <span className={`inline-flex rounded-full px-2 py-0.5 text-xs font-semibold ${status(value)}`}>{label(value)}</span>;
const Header = ({ title, children }: { title: string; children?: React.ReactNode }) => <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[var(--nexus-yellow-deep)]">Sistem Studio</p><h1 className="mt-1 text-2xl font-bold text-[var(--nexus-charcoal)]">{title}</h1><p className="mt-1 text-sm text-[var(--nexus-muted)]">Atur alur Studio yang aman, terukur, dan dapat diaudit.</p></div>{children && <div className="flex flex-wrap gap-2">{children}</div>}</div>;
const Action = ({ children, onClick, secondary = false, disabled = false }: { children: React.ReactNode; onClick?: () => void; secondary?: boolean; disabled?: boolean }) => <button disabled={disabled} onClick={onClick} className={`inline-flex items-center justify-center gap-1.5 rounded-lg px-3 py-2 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-50 ${secondary ? 'border border-[var(--nexus-border)] bg-white text-[var(--nexus-charcoal)]' : 'bg-[var(--nexus-yellow-deep)] text-white hover:bg-[var(--nexus-charcoal)]'}`}>{children}</button>;
const Card = ({ children, className = '' }: { children: React.ReactNode; className?: string; key?: React.Key }) => <section className={`rounded-xl border border-[var(--nexus-border)] bg-white shadow-sm ${className}`}>{children}</section>;
const Empty = ({ children }: { children: React.ReactNode }) => <Card><div className="p-10 text-center text-sm text-[var(--nexus-muted)]"><Workflow className="mx-auto mb-3 h-8 w-8" />{children}</div></Card>;

function Overview() {
  const [data, setData] = useState<AutomationOverview | null>(null); const [error, setError] = useState('');
  const load = useCallback(() => { studioAutomationsApi.overview().then(setData).catch((reason) => setError(errorText(reason))); }, []); useEffect(() => { load(); }, [load]);
  const write = useAuth().hasPermission('studio.automations.write');
  if (!data) return <div className="space-y-6"><Header title="Otomasi Studio" />{error ? <Empty><p>{error}</p><button className="mt-3 underline" onClick={load}>Coba lagi</button></Empty> : <Empty>Memuat otomasi Studio…</Empty>}</div>;
  const metrics = [{ name: 'Aturan aktif', value: data.active_rules, Icon: Zap }, { name: 'Dijeda', value: data.paused_rules, Icon: Pause }, { name: 'Run hari ini', value: data.runs_today, Icon: Activity }, { name: 'Berhasil', value: data.success_rate === null ? '—' : `${data.success_rate}%`, Icon: CheckCircle2 }, { name: 'Gagal', value: data.failed_today, Icon: AlertTriangle }, { name: 'Event menunggu', value: data.pending_events, Icon: Clock3 }];
  return <div className="space-y-6"><Header title="Otomasi Studio">{write && <Link to="/app/studio/automations/rules/new"><Action><Plus className="h-4 w-4" />Buat aturan</Action></Link>}<Link to="/app/studio/automations/templates"><Action secondary>Template</Action></Link></Header><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{metrics.map(({ name, value, Icon }) => <Card key={name}><div className="flex items-start justify-between p-5"><div><p className="text-2xl font-bold">{value}</p><p className="text-xs text-[var(--nexus-muted)]">{name}</p></div><Icon className="h-5 w-5 text-[var(--nexus-yellow-deep)]" /></div></Card>)}</div><Card><div className="grid gap-3 p-5 text-sm sm:grid-cols-2 xl:grid-cols-4"><p>Run terakhir<br /><b>{date(data.health.last_run)}</b></p><p>Berhasil terakhir<br /><b>{date(data.health.last_success)}</b></p><p>Gagal terakhir<br /><b>{date(data.health.last_failure)}</b></p><p>Event pending tertua<br /><b>{date(data.health.oldest_pending_event)}</b></p>{data.health.worker_warning && <p className="sm:col-span-2 xl:col-span-4 rounded bg-amber-50 p-3 text-amber-800">{data.health.worker_warning}</p>}</div></Card><Card><div className="border-b p-5 font-bold">Eksekusi terbaru</div>{data.recent_runs.length ? <Table>{data.recent_runs.map(run => <tr key={run.id}><td><Link className="font-semibold underline" to={`/app/studio/automations/rules/${run.rule_id}`}>{run.rule_name || run.rule_code}</Link></td><td>{run.trigger_event}</td><td><Pill value={run.status_code} /></td><td>{date(run.started_at)}</td><td><Link className="underline" to={`/app/studio/automations/runs/${run.id}`}>Detail</Link></td></tr>)}</Table> : <div className="p-5 text-sm text-[var(--nexus-muted)]">Belum ada eksekusi Studio.</div>}</Card></div>;
}

const Table = ({ children }: { children: React.ReactNode }) => <div className="overflow-auto"><table className="w-full min-w-[660px] text-left text-sm"><thead className="bg-[var(--nexus-cream-soft)] text-xs uppercase text-[var(--nexus-muted)]"><tr><th className="p-4">Nama</th><th>Pemicu</th><th>Status</th><th>Waktu</th><th className="p-4">Detail</th></tr></thead><tbody className="divide-y divide-[var(--nexus-border)]">{children}</tbody></table></div>;

function Rules() {
  const [rules, setRules] = useState<AutomationRule[] | null>(null); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const write = useAuth().hasPermission('studio.automations.write');
  const load = useCallback(() => { studioAutomationsApi.rules({ search }).then(setRules).catch((reason) => setError(errorText(reason))); }, [search]); useEffect(() => { load(); }, [load]);
  const call = async (work: () => Promise<unknown>) => { try { await work(); load(); } catch (reason) { setError(errorText(reason)); } };
  return <div className="space-y-6"><Header title="Aturan Otomasi">{write && <Link to="/app/studio/automations/rules/new"><Action><Plus className="h-4 w-4" />Buat aturan</Action></Link>}</Header><input className={input} value={search} onChange={event => setSearch(event.target.value)} placeholder="Cari aturan Studio" />{error && <p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{!rules ? <Empty>Memuat aturan…</Empty> : !rules.length ? <Empty>Belum ada aturan Studio. Gunakan template untuk membuat draf yang aman.</Empty> : <Card><Table>{rules.map(rule => <tr key={rule.id}><td className="p-4"><Link className="font-semibold underline" to={`/app/studio/automations/rules/${rule.id}`}>{rule.name}</Link><div className="text-xs text-[var(--nexus-muted)]">{rule.rule_code}</div></td><td>{rule.trigger_event}<div className="text-xs text-[var(--nexus-muted)]">{rule.trigger_type}</div></td><td><Pill value={rule.status_code} /></td><td>{date(rule.last_run_at)}</td><td className="p-4"><div className="flex gap-1">{write && rule.status_code === 'draft' && <Action onClick={() => void call(() => studioAutomationsApi.activate(rule.id))}>Aktifkan</Action>}{write && rule.status_code === 'active' && <Action secondary onClick={() => void call(() => studioAutomationsApi.pause(rule.id))}>Jeda</Action>}{write && rule.status_code === 'paused' && <Action onClick={() => void call(() => studioAutomationsApi.resume(rule.id))}>Lanjut</Action>}</div></td></tr>)}</Table></Card>}</div>;
}

function RuleEditor() {
  const { id } = useParams(); const nav = useNavigate(); const write = useAuth().hasPermission('studio.automations.write'); const [catalog, setCatalog] = useState<AutomationCatalog | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [form, setForm] = useState({ name: '', trigger_type: 'event', trigger_event: '', action_type: '', cron: '0 9 * * *' });
  useEffect(() => { Promise.all([studioAutomationsApi.catalog(), id ? studioAutomationsApi.rule(Number(id)) : Promise.resolve(null)]).then(([next, rule]) => { setCatalog(next); const trigger = rule?.trigger_event || next.triggers[0]?.code || ''; const action = rule?.action_json.actions[0]?.type || next.actions[0]?.type || ''; setForm({ name: rule?.name || '', trigger_type: rule?.trigger_type || next.triggers[0]?.triggerType || 'event', trigger_event: trigger, action_type: action, cron: rule?.trigger_config_json?.schedule?.expression || '0 9 * * *' }); }).catch(reason => setError(errorText(reason))); }, [id]);
  const triggers = useMemo(() => catalog?.triggers.filter(item => item.triggerType === form.trigger_type) || [], [catalog, form.trigger_type]); const actions = useMemo(() => catalog?.actions.filter(item => !item.supportedEvents || form.trigger_type === 'schedule' || item.supportedEvents.includes(form.trigger_event)) || [], [catalog, form.trigger_type, form.trigger_event]);
  useEffect(() => { if (triggers.length && !triggers.some(item => item.code === form.trigger_event)) setForm(current => ({ ...current, trigger_event: triggers[0].code })); }, [triggers, form.trigger_event]); useEffect(() => { if (actions.length && !actions.some(item => item.type === form.action_type)) setForm(current => ({ ...current, action_type: actions[0].type })); }, [actions, form.action_type]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!write || !catalog) return; setSaving(true); setError(''); try { const payload = { name: form.name, trigger_type: form.trigger_type, trigger_event: form.trigger_type === 'schedule' ? 'schedule' : form.trigger_event, trigger_config_json: ['schedule', 'sensor'].includes(form.trigger_type) ? { version: 1, schedule: { type: 'cron', expression: form.cron, timezone: 'Asia/Jakarta' } } : null, schedule_timezone: ['schedule', 'sensor'].includes(form.trigger_type) ? 'Asia/Jakarta' : null, condition_json: null, action_json: { version: 1, actions: [{ type: form.action_type, config: form.action_type === 'notification.create' ? { severity: 'warning', title_template: 'Notifikasi Studio', message_template: 'Aturan Studio membutuhkan perhatian.' } : form.action_type === 'tasks.create' ? { title_template: 'Tindak lanjut Studio', description_template: 'Tugas dibuat oleh otomasi Studio.' } : form.action_type === 'studio.project.priority.set' ? { priority: 'high' } : form.action_type === 'studio.analytics.generate_report' ? { report: 'overview', format: 'xlsx' } : {} }] }, priority: 100, cooldown_seconds: 0, max_retries: 0, status_code: 'draft' }; const result = id ? await studioAutomationsApi.updateRule(Number(id), payload) : await studioAutomationsApi.createRule(payload); nav(`/app/studio/automations/rules/${result.id}`); } catch (reason) { setError(errorText(reason)); } finally { setSaving(false); } };
  return <div className="space-y-6"><Header title={id ? 'Ubah Aturan Studio' : 'Buat Aturan Studio'}><Link to="/app/studio/automations/rules"><Action secondary>Kembali</Action></Link></Header>{!catalog ? <Empty>Memuat katalog Studio…</Empty> : <form onSubmit={submit} className="space-y-4"><Card><div className="grid gap-4 p-5 md:grid-cols-2"><label><span className="mb-1 block text-xs font-semibold">Nama aturan</span><input required className={input} value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /></label><label><span className="mb-1 block text-xs font-semibold">Jenis pemicu</span><select className={input} value={form.trigger_type} onChange={event => setForm({ ...form, trigger_type: event.target.value })}>{['event', 'sensor', 'schedule', 'manual'].map(value => <option key={value}>{value}</option>)}</select></label>{form.trigger_type !== 'schedule' && <label className="md:col-span-2"><span className="mb-1 block text-xs font-semibold">Pemicu Studio</span><select className={input} value={form.trigger_event} onChange={event => setForm({ ...form, trigger_event: event.target.value })}>{triggers.map(item => <option key={item.code} value={item.code}>{item.label}</option>)}</select></label>}{['schedule', 'sensor'].includes(form.trigger_type) && <label><span className="mb-1 block text-xs font-semibold">Cron (WIB)</span><input className={input} value={form.cron} onChange={event => setForm({ ...form, cron: event.target.value })} /></label>}<label className="md:col-span-2"><span className="mb-1 block text-xs font-semibold">Aksi aman</span><select className={input} value={form.action_type} onChange={event => setForm({ ...form, action_type: event.target.value })}>{actions.map(item => <option key={item.type} value={item.type}>{item.label} — {item.risk}</option>)}</select></label></div></Card>{error && <p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Action disabled={!write || saving}>{saving ? 'Menyimpan…' : 'Simpan sebagai draf'}</Action></form>}</div>;
}

function RuleDetail() {
  const { id } = useParams(); const [rule, setRule] = useState<AutomationRule | null>(null); const [test, setTest] = useState<unknown>(null); const [runMessage, setRunMessage] = useState(''); const [error, setError] = useState(''); const auth = useAuth(); const load = useCallback(() => { studioAutomationsApi.rule(Number(id)).then(setRule).catch(reason => setError(errorText(reason))); }, [id]); useEffect(() => { load(); }, [load]);
  if (!rule) return <div className="space-y-6"><Header title="Detail Aturan" />{error ? <Empty>{error}</Empty> : <Empty>Memuat aturan…</Empty>}</div>;
  const runTest = async () => { try { setTest(await studioAutomationsApi.test(rule.id, {})); } catch (reason) { setError(errorText(reason)); } };
  const runNow = async () => {
    if (!window.confirm('Jalankan aturan ini sekarang? Aksi yang disetujui aturan dapat dieksekusi.')) return;
    try { const result = await studioAutomationsApi.run(rule.id, {}); setRunMessage(result.message || 'Run manual telah masuk antrean.'); }
    catch (reason) { setError(errorText(reason)); }
  };
  return <div className="space-y-6"><Header title={rule.name}>{auth.hasPermission('studio.automations.write') && <Link to={`/app/studio/automations/rules/${rule.id}/edit`}><Action secondary>Ubah</Action></Link>}{auth.hasPermission('studio.automations.run') && <><Action secondary onClick={() => void runTest()}><FlaskConical className="h-4 w-4" />Uji aman</Action><Action onClick={() => void runNow()}><Play className="h-4 w-4" />Jalankan manual</Action></>}</Header><Card><div className="grid gap-4 p-5 sm:grid-cols-2"><p>Kode<br /><b>{rule.rule_code}</b></p><p>Status<br /><Pill value={rule.status_code} /></p><p>Pemicu<br /><b>{rule.trigger_event}</b></p><p>Versi<br /><b>{rule.version_no}</b></p><p className="sm:col-span-2">Aksi<br />{rule.action_json.actions.map(action => <span key={action.type} className="mr-2 inline-block rounded bg-slate-100 px-2 py-1 text-sm">{action.type}</span>)}</p></div></Card>{runMessage && <p className="rounded bg-emerald-50 p-3 text-sm text-emerald-800">{runMessage}</p>}{test && <Card><pre className="overflow-auto p-5 text-xs">{JSON.stringify(test, null, 2)}</pre></Card>}{error && <p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}</div>;
}

function Templates() { const [items, setItems] = useState<AutomationTemplate[] | null>(null); const [error, setError] = useState(''); const nav = useNavigate(); const write = useAuth().hasPermission('studio.automations.write'); useEffect(() => { studioAutomationsApi.templates().then(setItems).catch(reason => setError(errorText(reason))); }, []); const useTemplate = async (code: string) => { try { const result = await studioAutomationsApi.useTemplate(code); nav(`/app/studio/automations/rules/${result.id}`); } catch (reason) { setError(errorText(reason)); } }; return <div className="space-y-6"><Header title="Template Otomasi" />{error && <p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{!items ? <Empty>Memuat template…</Empty> : <div className="grid gap-3 md:grid-cols-2">{items.map(item => <Card key={item.code}><div className="p-5"><h2 className="font-bold">{item.name}</h2><p className="mt-1 text-sm text-[var(--nexus-muted)]">{item.description}</p><p className="mt-3 text-xs">{item.rule.trigger_event}</p>{write && <div className="mt-4"><Action onClick={() => void useTemplate(item.code)}>Gunakan sebagai draf</Action></div>}</div></Card>)}</div>}</div>; }
function Runs() { const [items, setItems] = useState<AutomationRun[] | null>(null); useEffect(() => { studioAutomationsApi.runs().then(setItems); }, []); return <div className="space-y-6"><Header title="Riwayat Eksekusi" />{!items ? <Empty>Memuat eksekusi…</Empty> : !items.length ? <Empty>Belum ada eksekusi Studio.</Empty> : <Card><Table>{items.map(item => <tr key={item.id}><td className="p-4">{item.rule_name || item.rule_code}</td><td>{item.trigger_event}</td><td><Pill value={item.status_code} /></td><td>{date(item.started_at)}</td><td className="p-4"><Link className="underline" to={`/app/studio/automations/runs/${item.id}`}>Detail</Link></td></tr>)}</Table></Card>}</div>; }
function RunDetail() { const { id } = useParams(); const [item, setItem] = useState<AutomationRun | null>(null); useEffect(() => { studioAutomationsApi.runDetail(Number(id)).then(setItem); }, [id]); return <div className="space-y-6"><Header title="Detail Eksekusi" />{!item ? <Empty>Memuat run…</Empty> : <Card><div className="p-5"><Pill value={item.status_code} /><pre className="mt-4 overflow-auto text-xs">{JSON.stringify({ input: item.input_json, snapshot: item.rule_snapshot_json, result: item.result_json, error: item.error_message }, null, 2)}</pre></div></Card>}</div>; }
function Catalog() { const [data, setData] = useState<AutomationCatalog | null>(null); useEffect(() => { studioAutomationsApi.catalog().then(setData); }, []); return <div className="space-y-6"><Header title="Pemicu & Aksi" />{!data ? <Empty>Memuat katalog…</Empty> : <div className="grid gap-4 xl:grid-cols-2"><Card><div className="border-b p-5 font-bold">Pemicu Studio</div><div className="divide-y">{data.triggers.map(item => <div className="p-4" key={item.code}><b>{item.label}</b><p className="text-sm text-[var(--nexus-muted)]">{item.code}</p></div>)}</div></Card><Card><div className="border-b p-5 font-bold">Aksi aman</div><div className="divide-y">{data.actions.map(item => <div className="p-4" key={item.type}><b>{item.label}</b><p className="text-sm text-[var(--nexus-muted)]">{item.type} · {item.risk}</p></div>)}</div></Card></div>}</div>; }
function Events() { const [items, setItems] = useState<DomainEventSummary[] | null>(null); useEffect(() => { studioAutomationsApi.events().then(setItems); }, []); return <div className="space-y-6"><Header title="Inbox Event Domain" />{!items ? <Empty>Memuat event…</Empty> : !items.length ? <Empty>Belum ada event Studio di inbox.</Empty> : <Card><Table>{items.map(item => <tr key={item.id}><td className="p-4">{item.event_name}</td><td>{item.entity_code || item.entity_type}</td><td><Pill value={item.status_code} /></td><td>{date(item.created_at)}</td><td className="p-4">{item.attempt_count}</td></tr>)}</Table></Card>}</div>; }

export function StudioAutomations() { return <Routes><Route index element={<Overview />} /><Route path="rules" element={<Rules />} /><Route path="rules/new" element={<RuleEditor />} /><Route path="rules/:id/edit" element={<RuleEditor />} /><Route path="rules/:id" element={<RuleDetail />} /><Route path="templates" element={<Templates />} /><Route path="runs" element={<Runs />} /><Route path="runs/:id" element={<RunDetail />} /><Route path="catalog" element={<Catalog />} /><Route path="events" element={<Events />} /><Route path="*" element={<Navigate to="." replace />} /></Routes>; }
