import { useEffect, useMemo, useState } from 'react';
import { Download, FileDown, Filter, RefreshCw, Search } from 'lucide-react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Button } from '../../components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/Card';
import { Modal } from '../../components/ui/Modal';
import { ApiError } from '../../lib/api';
import { reportsApi, type ExportFormat, type ReportCatalogItem, type ReportFilters, type ReportGroup, type ReportHistory, type ReportOverview, type ReportPreview } from '../../services/api/reports.api';

const groupLabels: Record<ReportGroup, string> = { global: 'Global', unified_finance: 'Keuangan Terpadu', craft: 'Craft', studio: 'Studio' };
const periodLabels: Record<string, string> = { today: 'Hari Ini', week: 'Minggu Ini', month: 'Bulan Ini', last_30_days: '30 Hari Terakhir', quarter: 'Kuartal Ini', year: 'Tahun Berjalan', custom: 'Kustom' };
const errorMessage = (error: unknown) => error instanceof ApiError ? error.message : 'Pusat Laporan tidak dapat dimuat.';
const money = (value: string | number | boolean | null | undefined, format?: string, currency = 'IDR') => { if (value == null) return '—'; if (typeof value === 'boolean') return value ? 'Ya' : 'Tidak'; if (format === 'percent') return `${Number(value).toLocaleString('id-ID', { maximumFractionDigits: 2 })}%`; if (format === 'currency') return new Intl.NumberFormat('id-ID', { style: 'currency', currency, maximumFractionDigits: 2 }).format(Number(value)); return typeof value === 'number' ? value.toLocaleString('id-ID', { maximumFractionDigits: 2 }) : value; };
const defaultFilters: ReportFilters = { period: 'last_30_days', workspace: 'all', page: 1, limit: 25 };

export function Reports() {
  const [overview, setOverview] = useState<ReportOverview | null>(null); const [catalog, setCatalog] = useState<ReportCatalogItem[]>([]); const [history, setHistory] = useState<ReportHistory | null>(null); const [selected, setSelected] = useState<string | null>(null); const [preview, setPreview] = useState<ReportPreview | null>(null); const [filters, setFilters] = useState<ReportFilters>(defaultFilters); const [search, setSearch] = useState(''); const [group, setGroup] = useState<'all' | ReportGroup>('all'); const [loading, setLoading] = useState(true); const [previewing, setPreviewing] = useState(false); const [error, setError] = useState<string | null>(null); const [exportOpen, setExportOpen] = useState(false);
  const selectedReport = catalog.find(item => item.report_code === selected) || null;
  const load = async () => { setLoading(true); setError(null); try { const [nextOverview, nextCatalog, nextHistory] = await Promise.all([reportsApi.overview(), reportsApi.catalog(), reportsApi.history()]); setOverview(nextOverview); setCatalog(nextCatalog); setHistory(nextHistory); setSelected(current => current && nextCatalog.some(item => item.report_code === current) ? current : nextCatalog[0]?.report_code || null); } catch (reason) { setError(errorMessage(reason)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const loadPreview = async (code = selected, nextFilters = filters) => { if (!code) return; setPreviewing(true); setError(null); try { setPreview(await reportsApi.preview(code, nextFilters)); } catch (reason) { setPreview(null); setError(errorMessage(reason)); } finally { setPreviewing(false); } };
  useEffect(() => { if (selected) void loadPreview(selected); }, [selected]);
  const visible = useMemo(() => catalog.filter(item => (group === 'all' || item.group === group) && `${item.name} ${item.description} ${groupLabels[item.group]}`.toLowerCase().includes(search.toLowerCase())), [catalog, group, search]);
  const choose = (code: string) => { setSelected(code); setPreview(null); setFilters(defaultFilters); };
  const download = async (id: number, filename = 'laporan') => { try { const blob = await reportsApi.download(id); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url); } catch (reason) { setError(errorMessage(reason)); } };
  return <main className="mx-auto w-full max-w-[1600px] space-y-6 p-4 sm:p-6 lg:p-8">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-[var(--nexus-yellow-deep)]">GLOBAL</p><h1 className="text-3xl font-bold text-[var(--nexus-charcoal)]">Pusat Laporan</h1><p className="mt-1 max-w-3xl text-sm text-gray-600">Hasilkan, tinjau, dan unduh laporan UNI-NEXUS dari Craft, Studio, serta Keuangan Terpadu dalam satu pusat.</p></div><Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className="h-4 w-4" />Refresh</Button></header>
    {error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><div className="flex flex-wrap items-center justify-between gap-3"><span>{error}</span><Button size="sm" variant="outline" onClick={() => void (selected ? loadPreview() : load())}>Coba lagi</Button></div></div>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[{ label: 'Laporan Tersedia', value: overview?.available_report_count }, { label: 'Craft', value: overview?.report_counts?.craft }, { label: 'Studio', value: overview?.report_counts?.studio }, { label: 'Keuangan', value: overview?.report_counts?.unified_finance }, { label: 'Ekspor Terbaru', value: overview?.recent_exports.length }].map(item => <Card key={item.label}><CardContent className="p-4"><p className="text-xs font-medium uppercase tracking-wide text-gray-500">{item.label}</p><p className="mt-2 text-2xl font-bold text-[var(--nexus-charcoal)]">{loading ? '…' : item.value ?? 0}</p></CardContent></Card>)}</section>
    <Card><CardContent className="space-y-4 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2" aria-label="Kategori laporan">{(['all', 'global', 'craft', 'studio', 'unified_finance'] as const).filter(value => value === 'all' || catalog.some(item => item.group === value)).map(value => <button key={value} onClick={() => setGroup(value)} className={`rounded-full px-3 py-2 text-sm ${group === value ? 'bg-[var(--nexus-yellow)] font-semibold text-black' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'}`}>{value === 'all' ? 'Semua Laporan' : groupLabels[value]}</button>)}</div><label className="relative block"><Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-gray-400" /><input aria-label="Cari laporan" value={search} onChange={event => setSearch(event.target.value)} placeholder="Cari laporan..." className="w-full rounded-lg border border-[var(--nexus-border)] py-2 pl-9 pr-3 text-sm lg:w-72" /></label></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{visible.map(item => <article key={item.report_code} className={`rounded-xl border p-4 ${selected === item.report_code ? 'border-[var(--nexus-yellow)] bg-[var(--nexus-cream-soft)]' : 'border-[var(--nexus-border)] bg-white'}`}><div className="flex items-start justify-between gap-2"><span className="rounded-full bg-gray-100 px-2 py-1 text-xs font-medium text-gray-600">{groupLabels[item.group]}</span><span className="text-xs text-gray-500">PDF · XLSX · CSV</span></div><h2 className="mt-3 font-semibold text-[var(--nexus-charcoal)]">{item.name}</h2><p className="mt-1 min-h-10 text-sm text-gray-600">{item.description}</p><div className="mt-4 flex gap-2"><Button size="sm" onClick={() => choose(item.report_code)}>Lihat Laporan</Button>{item.can_export && <Button size="sm" variant="outline" onClick={() => { choose(item.report_code); setExportOpen(true); }}><FileDown className="h-4 w-4" />Ekspor</Button>}</div></article>)}</div>{!loading && !visible.length && <p className="py-6 text-center text-sm text-gray-500">Tidak ada laporan yang sesuai atau dapat diakses.</p>}</CardContent></Card>
    {selectedReport && <ReportViewer report={selectedReport} preview={preview} filters={filters} setFilters={setFilters} loading={previewing} onApply={() => void loadPreview()} onExport={() => setExportOpen(true)} />}
    <ExportHistory history={history} onDownload={download} />
    {selectedReport && <ExportDialog open={exportOpen} report={selectedReport} filters={filters} onClose={() => setExportOpen(false)} onDownload={download} onSuccess={() => { setExportOpen(false); void load(); }} setError={setError} />}
  </main>;
}

function ReportViewer({ report, preview, filters, setFilters, loading, onApply, onExport }: { report: ReportCatalogItem; preview: ReportPreview | null; filters: ReportFilters; setFilters: (value: ReportFilters) => void; loading: boolean; onApply: () => void; onExport: () => void }) {
  const chartRows = preview?.chart?.rows || []; const keys = chartRows.length ? Object.keys(chartRows[0]).filter(key => key !== 'label' && typeof chartRows[0][key] === 'number') : [];
  return <section id="report-viewer" className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold text-[var(--nexus-yellow-deep)]">{groupLabels[report.group]}</p><h2 className="text-2xl font-bold text-[var(--nexus-charcoal)]">{report.name}</h2><p className="text-sm text-gray-600">{report.description}</p></div>{report.can_export && <Button onClick={onExport}><FileDown className="h-4 w-4" />Ekspor Laporan</Button>}</div><Card><CardContent className="flex flex-wrap items-end gap-3 p-4"><label className="text-sm font-medium">Periode<select value={filters.period || 'last_30_days'} onChange={event => setFilters({ ...filters, period: event.target.value as ReportFilters['period'] })} className="mt-1 block rounded-lg border p-2"><option value="today">Hari Ini</option><option value="week">Minggu Ini</option><option value="month">Bulan Ini</option><option value="last_30_days">30 Hari Terakhir</option><option value="quarter">Kuartal Ini</option><option value="year">Tahun Berjalan</option><option value="custom">Kustom</option></select></label>{filters.period === 'custom' && <><label className="text-sm font-medium">Tanggal Mulai<input type="date" value={filters.start_date || ''} onChange={event => setFilters({ ...filters, start_date: event.target.value })} className="mt-1 block rounded-lg border p-2" /></label><label className="text-sm font-medium">Tanggal Akhir<input type="date" value={filters.end_date || ''} onChange={event => setFilters({ ...filters, end_date: event.target.value })} className="mt-1 block rounded-lg border p-2" /></label></>}<Button onClick={onApply} disabled={loading}><Filter className="h-4 w-4" />{loading ? 'Memuat...' : 'Terapkan'}</Button></CardContent></Card>
    {loading && <Card><CardContent className="p-8 text-center text-sm text-gray-500">Memuat preview laporan…</CardContent></Card>}{preview && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{preview.kpis.map(item => <Card key={item.label}><CardContent className="p-4"><p className="text-xs font-medium text-gray-500">{item.label}</p><p className="mt-2 text-xl font-bold text-[var(--nexus-charcoal)]">{money(item.value, item.format, item.currency || preview.period.currency || 'IDR')}</p>{item.definition && <p className="mt-1 text-xs text-gray-500">{item.definition}</p>}</CardContent></Card>)}</div>{preview.chart && keys.length > 0 && <Card><CardHeader><CardTitle>{preview.chart.title}</CardTitle></CardHeader><CardContent className="h-72 p-4"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartRows}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="label" minTickGap={24} /><YAxis /><Tooltip />{keys.slice(0, 3).map((key, index) => <Line key={key} type="monotone" dataKey={key} stroke={['#E5B800', '#242424', '#6B7280'][index]} strokeWidth={2} dot={false} />)}</LineChart></ResponsiveContainer></CardContent></Card>}<ReportTable preview={preview} /></>}</section>;
}

function ReportTable({ preview }: { preview: ReportPreview }) { return <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle>Data Laporan</CardTitle><span className="text-xs text-gray-500">Dibuat {new Date(preview.generated_at).toLocaleString('id-ID', { timeZone: 'Asia/Jakarta' })}</span></div></CardHeader><CardContent className="p-0">{preview.notes.map(note => <p key={note} className="border-b bg-amber-50 px-4 py-3 text-sm text-amber-900">{note}</p>)}{preview.table.rows.length ? <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr>{preview.table.columns.map(column => <th key={column.key} className="whitespace-nowrap px-4 py-3">{column.label}</th>)}</tr></thead><tbody>{preview.table.rows.map((row, index) => <tr key={index} className="border-t border-gray-100">{preview.table.columns.map(column => <td key={column.key} className="whitespace-nowrap px-4 py-3">{money(row[column.key], column.format, preview.period.currency || 'IDR')}</td>)}</tr>)}</tbody></table></div> : <p className="p-8 text-center text-sm text-gray-500">Belum ada data pada periode ini.</p>}</CardContent></Card>; }

function ExportDialog({ open, report, filters, onClose, onDownload, onSuccess, setError }: { open: boolean; report: ReportCatalogItem; filters: ReportFilters; onClose: () => void; onDownload: (id: number, filename: string) => Promise<void>; onSuccess: () => void; setError: (message: string | null) => void }) { const [format, setFormat] = useState<ExportFormat>('pdf'); const [busy, setBusy] = useState(false); useEffect(() => { if (!report.supported_formats.includes(format)) setFormat(report.supported_formats[0]); }, [report, format]); const submit = async () => { setBusy(true); setError(null); try { const result = await reportsApi.export(report.report_code, format, filters); await onDownload(result.id, result.file_name); onSuccess(); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } }; return <Modal open={open} title="Ekspor Laporan" onClose={onClose} busy={busy}><div className="space-y-4 p-5"><div><p className="font-semibold">{report.name}</p><p className="text-sm text-gray-600">Pilih format untuk periode yang sedang dipreview.</p></div><fieldset><legend className="text-sm font-medium">Format</legend><div className="mt-2 grid gap-2 sm:grid-cols-3">{report.supported_formats.map(item => <label key={item} className={`cursor-pointer rounded-lg border p-3 text-sm ${format === item ? 'border-[var(--nexus-yellow)] bg-[var(--nexus-cream-soft)]' : ''}`}><input className="mr-2" type="radio" checked={format === item} onChange={() => setFormat(item)} />{item.toUpperCase()}</label>)}</div></fieldset><div className="flex justify-end gap-2"><Button variant="outline" onClick={onClose} disabled={busy}>Batal</Button><Button onClick={() => void submit()} disabled={busy}><Download className="h-4 w-4" />{busy ? 'Membuat…' : 'Buat & Unduh'}</Button></div></div></Modal>; }

function ExportHistory({ history, onDownload }: { history: ReportHistory | null; onDownload: (id: number, filename: string) => Promise<void> }) { return <Card><CardHeader><CardTitle>Riwayat Ekspor</CardTitle></CardHeader><CardContent className="p-0">{history?.items.length ? <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr>{['Nama Laporan', 'Kategori', 'Format', 'Dibuat Oleh', 'Tanggal', 'Aksi'].map(item => <th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody>{history.items.map(item => <tr key={item.id} className="border-t"><td className="px-4 py-3 font-medium">{item.report_name}</td><td className="px-4 py-3">{item.workspace}</td><td className="px-4 py-3 uppercase">{item.export_format}</td><td className="px-4 py-3">{item.generated_by}</td><td className="whitespace-nowrap px-4 py-3">{new Date(item.generated_at).toLocaleString('id-ID', { timeZone: 'Asia/Jakarta' })}</td><td className="px-4 py-3"><Button size="sm" variant="outline" onClick={() => void onDownload(item.id, item.report_name)} disabled={item.status_code !== 'generated'}><Download className="h-4 w-4" />Unduh</Button></td></tr>)}</tbody></table></div> : <p className="p-6 text-sm text-gray-500">Belum ada ekspor yang dapat diakses.</p>}</CardContent></Card>; }
