import React, { useEffect, useState } from 'react';
import { Button } from '../../../../components/ui/Button';
import type { CraftCustomer, CustomerFormData } from '../../../../types/craft-customers';

const emptyForm = (): CustomerFormData => ({ party_kind: 'individual', display_name: '', legal_name: '', email: '', phone: '', website: '', tax_id: '', address_line1: '', address_line2: '', city: '', province: '', postal_code: '', country_code: 'ID', notes: '', status_code: 'active' });
const text = (value?: string | null) => value || '';

export function CustomerForm({ customer, submitting, submitLabel, onSubmit, onCancel }: { customer?: CraftCustomer; submitting?: boolean; submitLabel: string; onSubmit: (data: CustomerFormData) => void; onCancel: () => void }) {
  const [form, setForm] = useState<CustomerFormData>(emptyForm());
  useEffect(() => { setForm(customer ? { party_kind: customer.party_kind === 'internal' ? 'individual' : customer.party_kind, display_name: customer.display_name, legal_name: text(customer.legal_name), email: text(customer.email), phone: text(customer.phone), website: text(customer.website), tax_id: text(customer.tax_id), address_line1: text(customer.address_line1), address_line2: text(customer.address_line2), city: text(customer.city), province: text(customer.province), postal_code: text(customer.postal_code), country_code: customer.country_code || 'ID', notes: text(customer.notes), status_code: customer.is_active ? 'active' : 'inactive' } : emptyForm()); }, [customer]);
  const set = <K extends keyof CustomerFormData>(key: K, value: CustomerFormData[K]) => setForm(current => ({ ...current, [key]: value }));
  const field = 'mt-1 w-full rounded-lg border border-[var(--nexus-border)] bg-white px-3 py-2.5 text-sm text-[var(--nexus-charcoal)] outline-none transition focus:border-amber-400 focus:ring-4 focus:ring-[var(--nexus-yellow)]/20';
  const label = 'text-xs font-semibold text-[var(--nexus-charcoal)]';
  const nullable = (value?: string | null) => value?.trim() || null;
  const submit = (event: React.FormEvent) => { event.preventDefault(); onSubmit({ ...form, display_name: form.display_name.trim(), legal_name: nullable(form.legal_name), email: nullable(form.email), phone: nullable(form.phone), website: nullable(form.website), tax_id: nullable(form.tax_id), address_line1: nullable(form.address_line1), address_line2: nullable(form.address_line2), city: nullable(form.city), province: nullable(form.province), postal_code: nullable(form.postal_code), country_code: (form.country_code || 'ID').toUpperCase(), notes: nullable(form.notes) }); };
  return <form onSubmit={submit} className="space-y-5"><section className="rounded-xl border border-[var(--nexus-border)] bg-white p-5 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[var(--nexus-yellow-deep)]">Identitas</p><div className="mt-4 grid gap-4 md:grid-cols-2"><label className={label}>Jenis Pelanggan *<select value={form.party_kind} onChange={event => set('party_kind', event.target.value as CustomerFormData['party_kind'])} className={field}><option value="individual">Individu</option><option value="company">Perusahaan</option><option value="institution">Institusi</option></select></label><label className={label}>Nama / Display Name *<input required value={form.display_name} onChange={event => set('display_name', event.target.value)} maxLength={200} className={field} /></label><label className={label}>Nama Legal<input value={form.legal_name || ''} onChange={event => set('legal_name', event.target.value)} maxLength={250} className={field} /></label><label className={label}>Email<input type="email" value={form.email || ''} onChange={event => set('email', event.target.value)} maxLength={190} className={field} /></label><label className={label}>Nomor Telepon<input value={form.phone || ''} onChange={event => set('phone', event.target.value)} maxLength={50} className={field} placeholder="Contoh: +62 812..." /></label><label className={label}>Website<input type="url" value={form.website || ''} onChange={event => set('website', event.target.value)} maxLength={255} className={field} placeholder="https://" /></label><label className={label}>NPWP / Tax ID<input value={form.tax_id || ''} onChange={event => set('tax_id', event.target.value)} maxLength={100} className={field} /></label><label className={label}>Status<select value={form.status_code || 'active'} onChange={event => set('status_code', event.target.value as CustomerFormData['status_code'])} className={field}><option value="active">Aktif</option><option value="inactive">Tidak Aktif</option></select></label></div></section>
    <section className="rounded-xl border border-[var(--nexus-border)] bg-white p-5 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[var(--nexus-yellow-deep)]">Alamat</p><div className="mt-4 grid gap-4 md:grid-cols-2"><label className={`${label} md:col-span-2`}>Alamat Baris 1<input value={form.address_line1 || ''} onChange={event => set('address_line1', event.target.value)} maxLength={255} className={field} /></label><label className={`${label} md:col-span-2`}>Alamat Baris 2<input value={form.address_line2 || ''} onChange={event => set('address_line2', event.target.value)} maxLength={255} className={field} /></label><label className={label}>Kota<input value={form.city || ''} onChange={event => set('city', event.target.value)} maxLength={100} className={field} /></label><label className={label}>Provinsi<input value={form.province || ''} onChange={event => set('province', event.target.value)} maxLength={100} className={field} /></label><label className={label}>Kode Pos<input value={form.postal_code || ''} onChange={event => set('postal_code', event.target.value)} maxLength={20} className={field} /></label><label className={label}>Negara<input value={form.country_code || 'ID'} onChange={event => set('country_code', event.target.value.toUpperCase())} minLength={2} maxLength={2} className={field} /></label></div></section>
    <section className="rounded-xl border border-[var(--nexus-border)] bg-white p-5 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[var(--nexus-yellow-deep)]">Informasi Tambahan</p><label className={`mt-4 block ${label}`}>Catatan<textarea value={form.notes || ''} onChange={event => set('notes', event.target.value)} maxLength={10000} rows={4} className={field} /></label></section>
    <div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={onCancel}>Batal</Button><Button type="submit" disabled={submitting}>{submitting ? 'Menyimpan...' : submitLabel}</Button></div></form>;
}
